// Auto-generated by the g-digital MCP distribution pipeline.
// Source MCP: @g-digital/mcp-gocertius (1.3.1)
// Architecture: REST-direct (Epic 12 ADR 0008) — pure fetch(), no MCP subprocess.
// Operations: evidence_create, evidence_list, evidence_seal, evidence_get, evidence_group_create, evidence_group_list, dossier_create, dossier_update, dossier_certify, dossier_list, dossier_get, dossier_template_list, dossier_preview, dossier_document_url, dossier_package_url, dossier_visibility, dossier_delete, dossier_group_certify, dossier_evidence_link, dossier_evidence_list_to_link, dossier_evidence_list, dossier_evidence_get, dossier_evidence_delete, notification_document_add, notification_request_create, notification_request_send, notification_request_status, notification_receiver_add, notification_certificate_get, case_file_create, case_file_list, case_file_get, chat_create, chat_get, chat_invitation_url, chat_certificate_create, chat_certificate_get, session_login, session_info

import { randomUUID } from 'node:crypto';
import {
  IDataObject,
  IExecuteFunctions,
  INodeExecutionData,
  INodeType,
  INodeTypeDescription,
  NodeApiError,
  NodeOperationError,
} from 'n8n-workflow';

export class Gocertius implements INodeType {
  description: INodeTypeDescription = {
    displayName: 'Gocertius',
    name: 'gocertius',
    group: ['transform'],
    version: 1,
    icon: 'file:icon.png',
    usableAsTool: true,
    description: "MCP server for GoCertius: certified evidence, dossiers, notifications and chats via AI agents.",
    defaults: { name: 'Gocertius' },
    inputs: ['main'],
    outputs: ['main'],
    credentials: [{ name: 'gocertiusApi', required: true }],
    properties: [
      {
        displayName: 'Resource',
        name: 'resource',
        type: 'options',
        noDataExpression: true,
        options: [
          { name: "Case File", value: 'caseFile' },
          { name: "Evidence", value: 'evidence' },
          { name: "Dossier Evidence", value: 'dossierEvidence' },
          { name: "Dossier", value: 'dossier' },
          { name: "Notification", value: 'notification' },
          { name: "Chat", value: 'chat' },
          { name: "Session", value: 'session' },
        ],
        default: 'caseFile',
      },
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['caseFile'] } },
        options: [
          {
            name: "Case File Create",
            value: 'case_file_create',
            description: "Creates a new case file — the top-level container for all related operations (evidence, notifications, dossiers, chats). Call this first before any other operation. Generate a UUID v4 for `id`. For `useCaseId`, use the general GoCertius use case: `063a016a-1d62-4b7b-a24f-7cf4d1d289bf` unless a specific use case is required. Returns caseFileId needed for all subsequent calls.",
            action: "Case File Create",
          },
          {
            name: "Case File List",
            value: 'case_file_list',
            description: "Lists all case files in your GoCertius account. Pass userId (from session_login or session_info) to scope results to your account. Returns paginated list with IDs, names, and status.",
            action: "Case File List",
          },
          {
            name: "Case File Get",
            value: 'case_file_get',
            description: "Retrieves details of a specific case file. Requires: caseFileId. Use to verify a case file exists before creating evidence groups, dossiers, or notifications.",
            action: "Case File Get",
          },
        ],
        default: 'case_file_create',
      },
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['evidence'] } },
        options: [
          {
            name: "Evidence Create",
            value: 'evidence_create',
            description: "Registers a new evidence record inside an evidence group. Requires: evidence_group_create → evidenceGroupId, case_file_create → caseFileId. Generate a UUID v4 for `id`. Compute the SHA-256 hex hash of the file BEFORE calling. custodyType INTERNAL = GoCertius stores the file; EXTERNAL = only hash is registered. Optional: pass `fileUrl` (a publicly accessible URL) to have the tool download and upload the file to S3 automatically — no separate PUT needed. If fileUrl is omitted, the response includes uploadFileUrl for manual upload. WARNING: the API sometimes returns {code:'EvidenceCreateError'} even when the evidence was successfully persisted — always verify with evidence_list before retrying.",
            action: "Evidence Create",
          },
          {
            name: "Evidence List",
            value: 'evidence_list',
            description: "Lists all evidence records in a specific evidence group. Use to review uploaded documents before sealing the group, or to find a specific evidenceId. Requires: caseFileId and evidenceGroupId. Returns paginated list with IDs, titles, status, and timestamps.",
            action: "Evidence List",
          },
          {
            name: "Evidence Seal",
            value: 'evidence_seal',
            description: "Seal and certify an evidence group. Closes the group to new additions and triggers async timestamping. Returns immediately — the group transitions OPEN → CLOSING → CLOSED. Poll evidence_group_list until status is CLOSED before linking to a dossier.",
            action: "Evidence Seal",
          },
          {
            name: "Evidence Get",
            value: 'evidence_get',
            description: "Retrieves a specific evidence record. Requires: evidence_create → evidenceId, evidence_group_create → evidenceGroupId, case_file_create → caseFileId. Returns status (COMPLETED|IN_PROCESS|ERROR), hash, and tspTimestamp when certified.",
            action: "Evidence Get",
          },
          {
            name: "Evidence Group Create",
            value: 'evidence_group_create',
            description: "Creates an evidence group inside a case file. Requires: case_file_create → caseFileId. Generate a UUID v4 for `id`. Set evidenceType to FILE, PHOTO, VIDEO, or WEB_PLUGIN. Returns evidenceGroupId. One group can contain multiple evidence records.",
            action: "Evidence Group Create",
          },
          {
            name: "Evidence Group List",
            value: 'evidence_group_list',
            description: "Lists all evidence groups in a case file with their current status (OPEN, CLOSING, CLOSED). Use to find an existing group or check which groups are ready for sealing. Requires: caseFileId.",
            action: "Evidence Group List",
          },
        ],
        default: 'evidence_create',
      },
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['dossierEvidence'] } },
        options: [
          {
            name: "Dossier Evidence Link",
            value: 'dossier_evidence_link',
            description: "Links specific evidence items to a DRAFT dossier. Call once per case file containing evidences to link. After linking all evidences, call dossier_certify to finalize. For a single-group dossier, use dossier_group_certify instead (one step). Example: dossier_evidence_link({ caseFileId: '...', dossierId: '...', caseFileToLinkId: '...', ids: ['ev-uuid-1', 'ev-uuid-2'] })",
            action: "Dossier Evidence Link",
          },
          {
            name: "Dossier Evidence List To Link",
            value: 'dossier_evidence_list_to_link',
            description: "Lists evidence items that are available to be linked to a dossier (CLOSED groups not yet linked). Requires: caseFileId and dossierId.",
            action: "Dossier Evidence List To Link",
          },
          {
            name: "Dossier Evidence List",
            value: 'dossier_evidence_list',
            description: "Lists all evidence items linked to a dossier. Requires: caseFileId and dossierId.",
            action: "Dossier Evidence List",
          },
          {
            name: "Dossier Evidence Get",
            value: 'dossier_evidence_get',
            description: "Retrieves details of a specific evidence item linked to a dossier. Requires: caseFileId, dossierId, evidenceId.",
            action: "Dossier Evidence Get",
          },
          {
            name: "Dossier Evidence Delete",
            value: 'dossier_evidence_delete',
            description: "Removes an evidence item from a dossier. Only available while dossier is in DRAFT status. Requires: caseFileId, dossierId, evidenceId.",
            action: "Dossier Evidence Delete",
          },
        ],
        default: 'dossier_evidence_link',
      },
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['dossier'] } },
        options: [
          {
            name: "Dossier Create",
            value: 'dossier_create',
            description: "Creates a dossier to aggregate certified evidence groups into a single tamper-evident PDF. Requires: case_file_create → caseFileId. Evidence groups must be in CLOSED status before linking. Generate a UUID v4 string for `id`. Returns dossierId. After creation, link evidence with dossier_evidence_link, then certify with dossier_certify.",
            action: "Dossier Create",
          },
          {
            name: "Dossier Update",
            value: 'dossier_update',
            description: "Updates the metadata of an existing dossier (name, template fields, expiry). Requires: dossier_create → dossierId, caseFileId. Only available while dossier is in DRAFT status.",
            action: "Dossier Update",
          },
          {
            name: "Dossier Certify",
            value: 'dossier_certify',
            description: "Certifies a DRAFT dossier, locking in all its associated evidence groups. The dossier must be in DRAFT status. After certification it transitions to CERTIFIED and a tamper-evident PDF is generated. Prerequisites: the dossier must exist (dossier_create) and have evidence groups linked. Use dossier_group_certify instead if you want to create + certify in one step from a single evidence group. Example: dossier_certify({ caseFileId: '...', dossierId: '...' })",
            action: "Dossier Certify",
          },
          {
            name: "Dossier List",
            value: 'dossier_list',
            description: "Lists all dossiers in a case file with their status and metadata. Use to find an existing dossierId or monitor certification progress. Requires: caseFileId. Returns paginated list with IDs, names, status, and creation dates.",
            action: "Dossier List",
          },
          {
            name: "Dossier Get",
            value: 'dossier_get',
            description: "Retrieves the full details of a specific dossier including status, linked evidence, and download URLs. Use to check current state or get certificate download URLs after CERTIFIED. Requires: caseFileId and dossierId.",
            action: "Dossier Get",
          },
          {
            name: "Dossier Template List",
            value: 'dossier_template_list',
            description: "Lists available dossier templates. No prerequisites. Returns template IDs and their translations per language. Use the returned id as dossierTemplateId in dossier_create.",
            action: "Dossier Template List",
          },
          {
            name: "Dossier Preview",
            value: 'dossier_preview',
            description: "Returns an HTML preview URL of a dossier before certification. Requires: caseFileId and dossierId.",
            action: "Dossier Preview",
          },
          {
            name: "Dossier Document Url",
            value: 'dossier_document_url',
            description: "Returns the download URL for the certified dossier PDF. Requires: dossier_certify (CERTIFIED status), caseFileId, dossierId.",
            action: "Dossier Document Url",
          },
          {
            name: "Dossier Package Url",
            value: 'dossier_package_url',
            description: "Returns the download URL for the full dossier package (PDF + evidence files). Requires: dossier_certify (CERTIFIED status), caseFileId, dossierId.",
            action: "Dossier Package Url",
          },
          {
            name: "Dossier Visibility",
            value: 'dossier_visibility',
            description: "Updates the visibility (public/private) of a certified dossier. Requires: dossier_certify (CERTIFIED status), caseFileId, dossierId.",
            action: "Dossier Visibility",
          },
          {
            name: "Dossier Delete",
            value: 'dossier_delete',
            description: "Deletes a dossier. Available in DRAFT status (to discard before certification) or in CERTIFIED status (to permanently remove the certified dossier). Irreversible. Requires: caseFileId and dossierId.",
            action: "Dossier Delete",
          },
          {
            name: "Dossier Group Certify",
            value: 'dossier_group_certify',
            description: "Creates AND certifies a dossier from a single sealed evidence group in one call (express path). Requires: evidence_seal (CLOSED status), case_file_create → caseFileId, evidence_group_create → evidenceGroupId. Generate a UUID v4 string for `id`. Use when you have exactly one sealed evidence group and don't need multi-group aggregation. Returns dossierId with CERTIFYING status → poll until CERTIFIED.",
            action: "Dossier Group Certify",
          },
        ],
        default: 'dossier_create',
      },
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['notification'] } },
        options: [
          {
            name: "Notification Document Add",
            value: 'notification_document_add',
            description: "Performs the notification_document_add operation. Review the API documentation for full field details.",
            action: "Notification Document Add",
          },
          {
            name: "Notification Request Create",
            value: 'notification_request_create',
            description: "Creates a certified notification request. Requires: case_file_create → caseFileId. Generate a UUID v4 for `id`. Set language to en_GB or es_ES. Returns notificationRequestId. Add at least one receiver with notification_receiver_add before sending. IMPORTANT: The `content` field must be valid HTML — plain text without HTML tags will not render on the recipient landing page. Only the following HTML formats are supported: paragraphs (<p>), bold (<strong>), italic (<em>), unordered lists (<ul><li>), ordered lists (<ol><li>). Do not use other HTML tags or CSS. Avoid special typographic characters (em dashes, smart quotes) in `subject`; use standard ASCII equivalents (hyphen, straight quotes) instead.",
            action: "Notification Request Create",
          },
          {
            name: "Notification Request Send",
            value: 'notification_request_send',
            description: "Trigger delivery of a certified notification to all added recipients. Returns immediately — delivery is async. Poll notification_request_status until status is DELIVERED before retrieving certificates.",
            action: "Notification Request Send",
          },
          {
            name: "Notification Request Status",
            value: 'notification_request_status',
            description: "Checks the delivery status of a certified notification. Requires: notificationRequestId, caseFileId. Returns status (CREATING|DRAFT|IN_PROCESS|SENT|PARTIALLY_READ|FULLY_READ|PARTIALLY_ANSWERED|FULLY_ANSWERED). Poll until status is SENT or beyond. Do not call notification_certificate_get while status is CREATING, DRAFT, or IN_PROCESS.",
            action: "Notification Request Status",
          },
          {
            name: "Notification Receiver Add",
            value: 'notification_receiver_add',
            description: "Adds a recipient to a notification request. Requires: notification_request_create → notificationRequestId, case_file_create → caseFileId. The `id` can be a UUID v4 or custom string (e.g. your internal user ID). Returns receiverId — save it for notification_certificate_get. Add all receivers before calling notification_request_send.",
            action: "Notification Receiver Add",
          },
          {
            name: "Notification Certificate Get",
            value: 'notification_certificate_get',
            description: "Generates a PDF certificate for a specific receiver proving delivery and/or reading of the notification. Requires: notification_request_send (delivered), notification_receiver_add → receiverId, notification_request_create → notificationRequestId, case_file_create → caseFileId. Generate a UUID v4 for `id`. Returns pdfUrl when status reaches CERTIFIED.",
            action: "Notification Certificate Get",
          },
        ],
        default: 'notification_document_add',
      },
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['chat'] } },
        options: [
          {
            name: "Chat Create",
            value: 'chat_create',
            description: "Creates a certified chat channel (Telegram). IMPORTANT: Chats can only be created in the user's personal case file (created automatically when the GoCertius account was opened). Do not use a manually created case file — use session_info → case_file_list to find the personal case file (oldest createdAt, owned by the user). Generate a UUID v4 for `id`. Set service to Telegram. Returns chatId. Use chat_invitation_url to get the shareable Telegram link.",
            action: "Chat Create",
          },
          {
            name: "Chat Get",
            value: 'chat_get',
            description: "Retrieves details of a certified chat. Requires: case_file_create → caseFileId, chat_create → chatId. Returns status, participants, and registeredAt timestamp.",
            action: "Chat Get",
          },
          {
            name: "Chat Invitation Url",
            value: 'chat_invitation_url',
            description: "Returns the Telegram invitation URL for a certified chat. Requires: chat_create → chatId, case_file_create → caseFileId. Share the returned invitationUrl with participants so they can join the certified channel.",
            action: "Chat Invitation Url",
          },
          {
            name: "Chat Certificate Create",
            value: 'chat_certificate_create',
            description: "Creates a certificate of a range of messages from a certified chat. Requires: chat_create → chatId, case_file_create → caseFileId, messages already present in the Telegram channel. Generate a UUID v4 for `id`. Specify chatMessagesFrom and chatMessagesTo as ISO timestamps (chatMessagesFrom must be AFTER the chat registeredAt timestamp). ASYNC: poll chat_certificate_get until status === CERTIFIED.",
            action: "Chat Certificate Create",
          },
          {
            name: "Chat Certificate Get",
            value: 'chat_certificate_get',
            description: "Retrieves a certified chat certificate including its status, message range, and PDF download URL. Prerequisites: the certificate must have been created with chat_certificate_create. Returns documentUrl when status is CERTIFIED. Example: chat_certificate_get({ caseFileId: '...', chatId: '...', id: '...' })",
            action: "Chat Certificate Get",
          },
        ],
        default: 'chat_create',
      },
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['session'] } },
        options: [
          {
            name: "Session Login",
            value: 'session_login',
            description: "Authenticate with GoCertius. Reads MCP_AUTH_EMAIL to discover the auth type (Password or OpenId) for that account. For Password accounts: uses MCP_AUTH_PASSWORD to obtain a session JWT. For OpenId accounts: starts an Azure AD device flow — on the FIRST call returns a browser link and code for the user to approve with Microsoft Authenticator; call session_login AGAIN after approving to complete authentication.",
            action: "Session Login",
          },
          {
            name: "Session Info",
            value: 'session_info',
            description: "Returns the authenticated user's session info including userId, session type (Password or OpenId), and for OpenId sessions: issuer, clientId, and scopes. Use this to retrieve the userId (UUID) required by case_file_list and other user-scoped operations. Prerequisites: a valid session (call session_login first if needed). Example: session_info() → { userId: '...uuid...', type: 'Password' }",
            action: "Session Info",
          },
        ],
        default: 'session_login',
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        description: "UUID of the case file",
        required: true,
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "Evidence Group ID",
        name: 'evidenceGroupId',
        type: 'string',
        default: "",
        description: "UUID of the evidence group",
        required: true,
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "Title",
        name: 'title',
        type: 'string',
        default: "",
        description: "Human-readable title for the evidence",
        required: true,
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "File Name",
        name: 'fileName',
        type: 'string',
        default: "",
        description: "Original file name including extension",
        required: true,
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "Hash",
        name: 'hash',
        type: 'string',
        default: "",
        description: "SHA-256 hex digest of the file content (64 hex chars)",
        required: true,
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "Custody Type",
        name: 'custodyType',
        type: 'options',
        options: [
          { name: "Internal", value: "INTERNAL" },
          { name: "External", value: "EXTERNAL" },
        ],
        default: "INTERNAL",
        description: "INTERNAL = GoCertius stores the file; EXTERNAL = only hash registered",
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "File URL",
        name: 'fileUrl',
        type: 'string',
        default: "",
        description: "Optional public URL to download and auto-upload the file to S3 (custodyType INTERNAL only). Eliminates the manual PUT step.",
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_list'] } },
      },
      {
        displayName: "Evidence Group ID",
        name: 'evidenceGroupId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_list'] } },
      },
      {
        displayName: "Filter",
        name: 'filter',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['evidence_list'] } },
      },
      {
        displayName: "Order",
        name: 'order',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['evidence_list'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['evidence_list'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "Evidences Count",
        name: 'evidencesCount',
        type: 'number',
        default: 0,
        required: true,
        typeOptions: {"minValue":1},
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "Device Model",
        name: 'deviceModel',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "Device Manufacturer",
        name: 'deviceManufacturer',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "Device OS",
        name: 'deviceOS',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "Latitude Location",
        name: 'latitudeLocation',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "Longitude Location",
        name: 'longitudeLocation',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "Altitude Location",
        name: 'altitudeLocation',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "Location Accuracy",
        name: 'locationAccuracy',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "User Agent",
        name: 'userAgent',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "Web URL",
        name: 'webUrl',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "Attestation",
        name: 'attestation',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_get'] } },
      },
      {
        displayName: "Evidence Group ID",
        name: 'evidenceGroupId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_get'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['evidence_get'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['evidence_group_create'] } },
      },
      {
        displayName: "Evidence Type",
        name: 'evidenceType',
        type: 'options',
        options: [
          { name: "File", value: "FILE" },
          { name: "Photo", value: "PHOTO" },
          { name: "Video", value: "VIDEO" },
          { name: "Web Plugin", value: "WEB_PLUGIN" },
        ],
        default: "FILE",
        required: true,
        displayOptions: { show: { operation: ['evidence_group_create'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_group_create'] } },
      },
      {
        displayName: "Item Description",
        name: 'description',
        type: 'string',
        default: "",
        description: "Short plain-text description (e.g. \"My case file\"). Required by the API.",
        required: true,
        displayOptions: { show: { operation: ['evidence_group_create'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_group_create'] } },
      },
      {
        displayName: "Attestation",
        name: 'attestation',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['evidence_group_create'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_group_list'] } },
      },
      {
        displayName: "Filter",
        name: 'filter',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['evidence_group_list'] } },
      },
      {
        displayName: "Order",
        name: 'order',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['evidence_group_list'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['evidence_group_list'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Dossier Template ID",
        name: 'dossierTemplateId',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Purpose",
        name: 'purpose',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Model ID",
        name: 'modelId',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "English (UK)", value: "en_GB" },
          { name: "Spanish (Spain)", value: "es_ES" },
          { name: "Portuguese (Portugal)", value: "pt_PT" },
        ],
        default: "en_GB",
        required: true,
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Filled Fields",
        name: 'filledFields',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Validity From",
        name: 'validityFrom',
        type: 'string',
        default: "",
        description: "ISO 8601 datetime (e.g. 2026-01-01T00:00:00.000Z). Leave empty — defaults to now.",
        required: true,
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Validity To",
        name: 'validityTo',
        type: 'string',
        default: "",
        description: "ISO 8601 datetime. Leave empty — defaults to 1 year from now.",
        required: true,
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Access Token",
        name: 'accessToken',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Dossier Template ID",
        name: 'dossierTemplateId',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Purpose",
        name: 'purpose',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Model ID",
        name: 'modelId',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "English (UK)", value: "en_GB" },
          { name: "Spanish (Spain)", value: "es_ES" },
          { name: "Portuguese (Portugal)", value: "pt_PT" },
        ],
        default: "en_GB",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Filled Fields",
        name: 'filledFields',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Validity From",
        name: 'validityFrom',
        type: 'string',
        default: "",
        description: "ISO 8601 datetime (e.g. 2026-01-01T00:00:00.000Z). Leave empty — defaults to now.",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Validity To",
        name: 'validityTo',
        type: 'string',
        default: "",
        description: "ISO 8601 datetime. Leave empty — defaults to 1 year from now.",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Access Token",
        name: 'accessToken',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        description: "UUID of the case file that owns this dossier",
        required: true,
        displayOptions: { show: { operation: ['dossier_certify'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        description: "UUID of the dossier to certify (must be in DRAFT status)",
        required: true,
        displayOptions: { show: { operation: ['dossier_certify'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_list'] } },
      },
      {
        displayName: "Filter",
        name: 'filter',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_list'] } },
      },
      {
        displayName: "Order",
        name: 'order',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_list'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_list'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_get'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_get'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_template_list'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_preview'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_preview'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_document_url'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_document_url'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_package_url'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_package_url'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_visibility'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_visibility'] } },
      },
      {
        displayName: "Visibility",
        name: 'visibility',
        type: 'options',
        options: [
          { name: "Accessible", value: "ACCESSIBLE" },
          { name: "Pending Recall", value: "PENDING_RECALL" },
          { name: "Recalled", value: "RECALLED" },
        ],
        default: "ACCESSIBLE",
        required: true,
        displayOptions: { show: { operation: ['dossier_visibility'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_delete'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_delete'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "Evidence Group ID",
        name: 'evidenceGroupId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "Model ID",
        name: 'modelId',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "Evidence IDS",
        name: 'evidenceIds',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "English (UK)", value: "en_GB" },
          { name: "Spanish (Spain)", value: "es_ES" },
          { name: "Portuguese (Portugal)", value: "pt_PT" },
        ],
        default: "en_GB",
        required: true,
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        description: "UUID of the case file that owns the dossier",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_link'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        description: "UUID of the DRAFT dossier to link evidences to",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_link'] } },
      },
      {
        displayName: "Case File To Link ID",
        name: 'caseFileToLinkId',
        type: 'string',
        default: "",
        description: "UUID of the case file containing the evidences (often same as caseFileId)",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_link'] } },
      },
      {
        displayName: "IDS",
        name: 'ids',
        type: 'json',
        default: {},
        description: "UUIDs of the evidence items to link",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_link'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_list_to_link'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_list_to_link'] } },
      },
      {
        displayName: "Case File To Link ID",
        name: 'caseFileToLinkId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_list_to_link'] } },
      },
      {
        displayName: "Filter",
        name: 'filter',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_evidence_list_to_link'] } },
      },
      {
        displayName: "Order",
        name: 'order',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_evidence_list_to_link'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_evidence_list_to_link'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_list'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_list'] } },
      },
      {
        displayName: "Dossier Evidence Group ID",
        name: 'dossierEvidenceGroupId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_list'] } },
      },
      {
        displayName: "Filter",
        name: 'filter',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_evidence_list'] } },
      },
      {
        displayName: "Order",
        name: 'order',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_evidence_list'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_evidence_list'] } },
      },
      {
        displayName: "Dossier Evidence Group ID",
        name: 'dossierEvidenceGroupId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_get'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_get'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_get'] } },
      },
      {
        displayName: "Dossier Evidence ID",
        name: 'dossierEvidenceId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_get'] } },
      },
      {
        displayName: "Dossier Evidence Group ID",
        name: 'dossierEvidenceGroupId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_delete'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_delete'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_delete'] } },
      },
      {
        displayName: "Dossier Evidence ID",
        name: 'dossierEvidenceId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_delete'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_document_add'] } },
      },
      {
        displayName: "Notification Request ID",
        name: 'notificationRequestId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_document_add'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['notification_document_add'] } },
      },
      {
        displayName: "File Name",
        name: 'fileName',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_document_add'] } },
      },
      {
        displayName: "Hash",
        name: 'hash',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_document_add'] } },
      },
      {
        displayName: "File Size",
        name: 'fileSize',
        type: 'number',
        default: 0,
        displayOptions: { show: { operation: ['notification_document_add'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "Type",
        name: 'type',
        type: 'options',
        options: [
          { name: "No Response", value: "NO_RESPONSE" },
          { name: "Accepted Or Not", value: "ACCEPTED_OR_NOT" },
          { name: "Received Agree", value: "RECEIVED_AGREE" },
        ],
        default: "NO_RESPONSE",
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "Subject",
        name: 'subject',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "Content (HTML)",
        name: 'content',
        type: 'string',
        default: "",
        description: "Must be valid HTML. Supported tags only: <p>, <strong>, <em>, <ul><li>, <ol><li>. No other tags or CSS. Example: <p>Your document is <strong>ready</strong> for review.</p>",
        required: true,
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "English (UK)", value: "en_GB" },
          { name: "Spanish (Spain)", value: "es_ES" },
        ],
        default: "en_GB",
        required: true,
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "OTP By Default",
        name: 'otpByDefault',
        type: 'boolean',
        default: false,
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "Send WA URL By Default",
        name: 'sendWaUrlByDefault',
        type: 'boolean',
        default: false,
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_request_send'] } },
      },
      {
        displayName: "Notification Request ID",
        name: 'notificationRequestId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_request_send'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_request_status'] } },
      },
      {
        displayName: "Notification Request ID",
        name: 'notificationRequestId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_request_status'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "Notification Request ID",
        name: 'notificationRequestId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "First Name",
        name: 'firstName',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "Last Name",
        name: 'lastName',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "Email",
        name: 'email',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "Phone Number",
        name: 'phoneNumber',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "Phone Prefix",
        name: 'phonePrefix',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "OTP Required",
        name: 'otpRequired',
        type: 'boolean',
        default: false,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "Send WA URL",
        name: 'sendWaUrl',
        type: 'boolean',
        default: false,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_certificate_get'] } },
      },
      {
        displayName: "Notification Request ID",
        name: 'notificationRequestId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_certificate_get'] } },
      },
      {
        displayName: "Receiver ID",
        name: 'receiverId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_certificate_get'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['notification_certificate_get'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "English (UK)", value: "en_GB" },
          { name: "Spanish (Spain)", value: "es_ES" },
        ],
        default: "en_GB",
        displayOptions: { show: { operation: ['notification_certificate_get'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['case_file_create'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['case_file_create'] } },
      },
      {
        displayName: "Reference",
        name: 'reference',
        type: 'string',
        default: "",
        description: "Optional user-defined reference code (max 32 chars, e.g. \"EXP-2026-001\"). Do not use a UUID.",
        displayOptions: { show: { operation: ['case_file_create'] } },
      },
      {
        displayName: "Item Description",
        name: 'description',
        type: 'string',
        default: "",
        description: "Short plain-text description (e.g. \"My case file\"). Required by the API.",
        required: true,
        displayOptions: { show: { operation: ['case_file_create'] } },
      },
      {
        displayName: "Use Case ID",
        name: 'useCaseId',
        type: 'string',
        default: "063a016a-1d62-4b7b-a24f-7cf4d1d289bf",
        description: "UUID of the use case. Default is the general GoCertius use case (063a016a-1d62-4b7b-a24f-7cf4d1d289bf). Change only if you need a specific use case.",
        required: true,
        displayOptions: { show: { operation: ['case_file_create'] } },
      },
      {
        displayName: "User ID",
        name: 'userId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['case_file_list'] } },
      },
      {
        displayName: "Filter",
        name: 'filter',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['case_file_list'] } },
      },
      {
        displayName: "Order",
        name: 'order',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['case_file_list'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['case_file_list'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['case_file_get'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "Title",
        name: 'title',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "Service Title",
        name: 'serviceTitle',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "Service Description",
        name: 'serviceDescription',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "Service",
        name: 'service',
        type: 'options',
        options: [
          { name: "Telegram", value: "Telegram" },
        ],
        default: "Telegram",
        required: true,
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "English (UK)", value: "en_GB" },
          { name: "Spanish (Spain)", value: "es_ES" },
        ],
        default: "en_GB",
        required: true,
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_get'] } },
      },
      {
        displayName: "Chat ID",
        name: 'chatId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_get'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_invitation_url'] } },
      },
      {
        displayName: "Chat ID",
        name: 'chatId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_invitation_url'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "Chat ID",
        name: 'chatId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "English (UK)", value: "en_GB" },
          { name: "Spanish (Spain)", value: "es_ES" },
        ],
        default: "en_GB",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "Chat Messages From",
        name: 'chatMessagesFrom',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "Chat Messages To",
        name: 'chatMessagesTo',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        description: "UUID of the case file that owns the chat",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_get'] } },
      },
      {
        displayName: "Chat ID",
        name: 'chatId',
        type: 'string',
        default: "",
        description: "UUID of the chat",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_get'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_get'] } },
      },
    ],
  };

  async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
    const items = this.getInputData();
    const out: INodeExecutionData[] = [];
    const creds = await this.getCredentials('gocertiusApi');
    const baseUrl = String(creds.baseUrl ?? '').replace(/\/$/, '');

    // --- Obtain Bearer token (once per execute call) ---
    const loginRes = await fetch(`${baseUrl}/session`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        email: String(creds.email ?? ''),
        password: String(creds.password ?? ''),
      }),
    });
    if (!loginRes.ok) {
      const loginErr = await loginRes.json().catch(() => ({ message: `HTTP ${loginRes.status}` }));
      throw new NodeApiError(this.getNode(), loginErr as never, { httpCode: String(loginRes.status) });
    }
    const loginBody = await loginRes.json() as { jwt?: string; token?: string; accessToken?: string };
    const bearer = loginBody.jwt ?? loginBody.token ?? loginBody.accessToken ?? '';

    // --- Per-item REST calls ---
    for (let i = 0; i < items.length; i++) {
      try {
        const operation = this.getNodeParameter('operation', i) as string;
        const meta = OPERATION_META[operation];
        if (!meta) {
          throw new NodeOperationError(this.getNode(), `Unknown operation: ${operation}`, { itemIndex: i });
        }
        if (meta.stub) {
          throw new NodeOperationError(
            this.getNode(),
            `Operation '${operation}' requires n8n self-hosted with the @g-digital/mcp-* package. It is not available in n8n Cloud via this connector.`,
            { itemIndex: i },
          );
        }

        // Replace URL path params {paramName} from input; remaining args → body/query
        let url = `${baseUrl}${meta.urlTemplate}`;
        const propsForOp = OPERATION_PROPERTY_NAMES[operation] ?? [];
        const body: IDataObject = {};
        const isCreateOrAdd = operation.endsWith('_create') || operation.endsWith('_add');
        let generatedId: string | undefined;
        for (const propName of propsForOp) {
          let val = this.getNodeParameter(propName, i);
          // Auto-generate UUID for 'id' in _create/_add BEFORE the skip check
          if (propName === 'id' && isCreateOrAdd && (val === '' || val === null || val === undefined)) {
            val = randomUUID();
            generatedId = val as string;
          }
          if (val === '' || val === null || val === undefined) continue;
          if (typeof val === 'object' && !Array.isArray(val) && Object.keys(val as object).length === 0) continue;
          const placeholder = `{${propName}}`;
          if (url.includes(placeholder)) {
            url = url.replace(placeholder, encodeURIComponent(String(val)));
          } else {
            body[propName] = val;
          }
        }
        // Substitute any remaining {placeholder} patterns from credentials.
        // First try exact credential key names, then common API→credential aliases
        // (e.g. {email} in session_info maps to the 'email' credential field).
        const credAliases: Record<string, string> = { email: 'email' };
        for (const [credKey, credVal] of Object.entries(creds)) {
          const placeholder = `{${credKey}}`;
          if (url.includes(placeholder) && credVal) {
            url = url.replace(placeholder, encodeURIComponent(String(credVal)));
          }
        }
        for (const [alias, credKey] of Object.entries(credAliases)) {
          const placeholder = `{${alias}}`;
          if (url.includes(placeholder) && creds[credKey]) {
            url = url.replace(placeholder, encodeURIComponent(String(creds[credKey])));
          }
        }

        // --- Smart defaults for remaining body fields ---
        // validityFrom: default to now (ISO 8601)
        if ('validityFrom' in body && (body.validityFrom === '' || body.validityFrom === null || body.validityFrom === undefined)) {
          body.validityFrom = new Date().toISOString();
        }
        // validityTo: default to 1 year from now
        if ('validityTo' in body && (body.validityTo === '' || body.validityTo === null || body.validityTo === undefined)) {
          const oneYearLater = new Date();
          oneYearLater.setFullYear(oneYearLater.getFullYear() + 1);
          body.validityTo = oneYearLater.toISOString();
        }

        const isBodyless = meta.method === 'GET' || meta.method === 'DELETE';
        if (isBodyless && Object.keys(body).length > 0) {
          // hey-api client uses bracket notation for nested object query params,
          // matching the qs library used by NestJS on the server:
          // { filter: { ownerId: 'uuid' }, page: { number: 1, size: 20 } }
          //   → filter[ownerId]=uuid&page[number]=1&page[size]=20
          const flattenQs = (obj: IDataObject, prefix = ''): Array<[string, string]> => {
            const pairs: Array<[string, string]> = [];
            for (const [k, v] of Object.entries(obj)) {
              if (v === null || v === undefined || v === '') continue;
              const key = prefix ? `${prefix}[${k}]` : k;
              if (typeof v === 'object' && !Array.isArray(v)) {
                if (Object.keys(v as object).length === 0) continue;
                pairs.push(...flattenQs(v as IDataObject, key));
              } else if (Array.isArray(v)) {
                for (const item of v) pairs.push([`${key}[]`, String(item)]);
              } else {
                pairs.push([key, String(v)]);
              }
            }
            return pairs;
          };
          const pairs = flattenQs(body);
          if (pairs.length > 0) {
            url = `${url}?${new URLSearchParams(pairs).toString()}`;
          }
        }

        const apiRes = await fetch(url, {
          method: meta.method,
          headers: {
            Authorization: `Bearer ${bearer}`,
            ...(isBodyless ? {} : { 'Content-Type': 'application/json' }),
          },
          ...(isBodyless ? {} : { body: JSON.stringify(body) }),
        });

        if (!apiRes.ok) {
          const errBody = await apiRes.json().catch(() => ({ message: `${operation} failed: HTTP ${apiRes.status}` }));
          throw new NodeApiError(this.getNode(), errBody as never, {
            httpCode: String(apiRes.status),
            itemIndex: i,
          });
        }

        // 204 No Content or empty body → return empty object
        const contentLength = apiRes.headers.get('content-length');
        const hasBody = apiRes.status !== 204 && contentLength !== '0';
        const json: IDataObject = hasBody
          ? await apiRes.json().catch(() => ({})) as IDataObject
          : {};
        // Inject auto-generated id with semantic field name so downstream nodes
        // can reference it directly (e.g. $json.caseFileId, $json.chatId).
        if (generatedId) {
          const semanticId = AUTO_ID_OUTPUT_FIELD[operation];
          if (semanticId && !json[semanticId]) json[semanticId] = generatedId;
          if (!json['id']) json['id'] = generatedId;
        }
        // chat_certificate_get: when CERTIFIED, fetch documentUrl via a second call
        if (operation === 'chat_certificate_get' && (json as IDataObject).status === 'CERTIFIED' && !json['documentUrl']) {
          try {
            const docUrlRes = await fetch(`${url}/document-url`, {
              headers: { Authorization: `Bearer ${bearer}` },
            });
            if (docUrlRes.ok) {
              const docData = await docUrlRes.json().catch(() => ({})) as IDataObject;
              if (docData.documentUrl) (json as IDataObject).documentUrl = docData.documentUrl;
            }
          } catch { /* non-fatal */ }
        }
        // session_info: inject userId decoded from JWT sub claim so callers
        // don't need a separate step to obtain the userId required by most operations.
        if (operation === 'session_info' && bearer) {
          try {
            const parts = bearer.split('.');
            if (parts.length === 3) {
              const pad = (s: string) => s + '='.repeat((4 - s.length % 4) % 4);
              const payload = JSON.parse(Buffer.from(pad(parts[1] ?? ''), 'base64').toString('utf8')) as IDataObject;
              const sub = payload.sub ?? payload.userId ?? payload.user_id;
              if (sub && !(json as IDataObject).userId) {
                (json as IDataObject).userId = sub;
              }
            }
          } catch { /* ignore decode errors */ }
        }
        out.push({ json: json as IDataObject });
      } catch (error) {
        if (this.continueOnFail()) {
          out.push({ json: this.getInputData(i)[0].json, error: error as NodeOperationError });
          continue;
        }
        throw error;
      }
    }

    return [out];
  }
}

// Semantic output field name for auto-generated 'id' values.
// When a _create/_add operation auto-generates a UUID for 'id', it is also
// injected into the output under this field name so downstream nodes can
// reference it with its domain-specific name (e.g. $json.caseFileId).
const AUTO_ID_OUTPUT_FIELD: Record<string, string> = {
  case_file_create: 'caseFileId',
  evidence_create: 'evidenceId',
  evidence_group_create: 'evidenceGroupId',
  dossier_create: 'dossierId',
  dossier_group_certify: 'dossierId',
  notification_request_create: 'notificationRequestId',
  notification_receiver_add: 'receiverId',
  notification_document_add: 'documentId',
  chat_create: 'chatId',
  chat_certificate_create: 'certificateId',
  signature_request_create: 'requestId',
  signature_group_create: 'groupId',
  signature_participant_create: 'signatoryId',
};

// HTTP metadata per operation — method + URL template.
// 'stub: true' means the tool has no REST annotation and requires self-hosted n8n.
const OPERATION_META: Record<string, { method: string; urlTemplate: string; stub?: true }> = {
  'evidence_create': { method: 'POST', urlTemplate: "/evidences" },
  'evidence_list': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences" },
  'evidence_seal': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/evidence-groups/{id}/close" },
  'evidence_get': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences/{id}" },
  'evidence_group_create': { method: 'POST', urlTemplate: "/evidence-groups" },
  'evidence_group_list': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/evidence-groups" },
  'dossier_create': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/dossiers" },
  'dossier_update': { method: 'PUT', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}" },
  'dossier_certify': { method: 'PUT', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/certify" },
  'dossier_list': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers" },
  'dossier_get': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}" },
  'dossier_template_list': { method: 'GET', urlTemplate: "/dossier-templates" },
  'dossier_preview': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/report-preview" },
  'dossier_document_url': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/document-url" },
  'dossier_package_url': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/package-url" },
  'dossier_visibility': { method: 'PUT', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/visibility" },
  'dossier_delete': { method: 'DELETE', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}" },
  'dossier_group_certify': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/dossier-express" },
  'dossier_evidence_link': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/case-files-to-link/{caseFileToLinkId}/link-evidences" },
  'dossier_evidence_list_to_link': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/case-files-to-link/{caseFileToLinkId}/evidences-to-link" },
  'dossier_evidence_list': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/evidence-groups/{dossierEvidenceGroupId}/evidences" },
  'dossier_evidence_get': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/evidence-groups/{dossierEvidenceGroupId}/evidences/{dossierEvidenceId}" },
  'dossier_evidence_delete': { method: 'DELETE', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/evidence-groups/{dossierEvidenceGroupId}/evidences/{dossierEvidenceId}" },
  'notification_document_add': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/notification-requests/{notificationRequestId}/documents" },
  'notification_request_create': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/notification-requests" },
  'notification_request_send': { method: 'PUT', urlTemplate: "/case-files/{caseFileId}/notification-requests/{notificationRequestId}/send" },
  'notification_request_status': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/notification-requests/{notificationRequestId}" },
  'notification_receiver_add': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers" },
  'notification_certificate_get': { method: 'STUB', urlTemplate: "", stub: true },
  'case_file_create': { method: 'POST', urlTemplate: "/case-files" },
  'case_file_list': { method: 'GET', urlTemplate: "/users/{userId}/case-files" },
  'case_file_get': { method: 'GET', urlTemplate: "/case-files/{caseFileId}" },
  'chat_create': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/chats" },
  'chat_get': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/chats/{chatId}" },
  'chat_invitation_url': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/chats/{chatId}/invitation-url" },
  'chat_certificate_create': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/chats/{chatId}/certificate-express" },
  'chat_certificate_get': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/chats/{chatId}/certificates/{id}" },
  'session_login': { method: 'POST', urlTemplate: "/session" },
  'session_info': { method: 'GET', urlTemplate: "/session-info/{email}" },
};

// Per-operation input property names for argument gathering.
const OPERATION_PROPERTY_NAMES: Record<string, readonly string[]> = {
  'evidence_create': ['caseFileId', 'evidenceGroupId', 'id', 'title', 'fileName', 'hash', 'custodyType', 'fileUrl'],
  'evidence_list': ['caseFileId', 'evidenceGroupId', 'filter', 'order', 'page'],
  'evidence_seal': ['caseFileId', 'id', 'evidencesCount', 'deviceModel', 'deviceManufacturer', 'deviceOS', 'latitudeLocation', 'longitudeLocation', 'altitudeLocation', 'locationAccuracy', 'userAgent', 'webUrl', 'attestation'],
  'evidence_get': ['caseFileId', 'evidenceGroupId', 'id'],
  'evidence_group_create': ['id', 'evidenceType', 'name', 'description', 'caseFileId', 'attestation'],
  'evidence_group_list': ['caseFileId', 'filter', 'order', 'page'],
  'dossier_create': ['caseFileId', 'dossierTemplateId', 'purpose', 'id', 'modelId', 'name', 'language', 'filledFields', 'validityFrom', 'validityTo', 'accessToken'],
  'dossier_update': ['caseFileId', 'dossierId', 'dossierTemplateId', 'purpose', 'modelId', 'name', 'language', 'filledFields', 'validityFrom', 'validityTo', 'accessToken'],
  'dossier_certify': ['caseFileId', 'dossierId'],
  'dossier_list': ['caseFileId', 'filter', 'order', 'page'],
  'dossier_get': ['caseFileId', 'dossierId'],
  'dossier_template_list': ['page'],
  'dossier_preview': ['caseFileId', 'dossierId'],
  'dossier_document_url': ['caseFileId', 'dossierId'],
  'dossier_package_url': ['caseFileId', 'dossierId'],
  'dossier_visibility': ['caseFileId', 'dossierId', 'visibility'],
  'dossier_delete': ['caseFileId', 'dossierId'],
  'dossier_group_certify': ['caseFileId', 'evidenceGroupId', 'id', 'modelId', 'evidenceIds', 'name', 'language'],
  'dossier_evidence_link': ['caseFileId', 'dossierId', 'caseFileToLinkId', 'ids'],
  'dossier_evidence_list_to_link': ['caseFileId', 'dossierId', 'caseFileToLinkId', 'filter', 'order', 'page'],
  'dossier_evidence_list': ['caseFileId', 'dossierId', 'dossierEvidenceGroupId', 'filter', 'order', 'page'],
  'dossier_evidence_get': ['dossierEvidenceGroupId', 'dossierId', 'caseFileId', 'dossierEvidenceId'],
  'dossier_evidence_delete': ['dossierEvidenceGroupId', 'dossierId', 'caseFileId', 'dossierEvidenceId'],
  'notification_document_add': ['caseFileId', 'notificationRequestId', 'id', 'fileName', 'hash', 'fileSize'],
  'notification_request_create': ['caseFileId', 'id', 'type', 'subject', 'content', 'language', 'otpByDefault', 'sendWaUrlByDefault'],
  'notification_request_send': ['caseFileId', 'notificationRequestId'],
  'notification_request_status': ['caseFileId', 'notificationRequestId'],
  'notification_receiver_add': ['caseFileId', 'notificationRequestId', 'id', 'firstName', 'lastName', 'email', 'phoneNumber', 'phonePrefix', 'otpRequired', 'sendWaUrl'],
  'notification_certificate_get': ['caseFileId', 'notificationRequestId', 'receiverId', 'id', 'language'],
  'case_file_create': ['id', 'name', 'reference', 'description', 'useCaseId'],
  'case_file_list': ['userId', 'filter', 'order', 'page'],
  'case_file_get': ['caseFileId'],
  'chat_create': ['caseFileId', 'id', 'title', 'serviceTitle', 'serviceDescription', 'service', 'language'],
  'chat_get': ['caseFileId', 'chatId'],
  'chat_invitation_url': ['caseFileId', 'chatId'],
  'chat_certificate_create': ['caseFileId', 'chatId', 'id', 'name', 'language', 'chatMessagesFrom', 'chatMessagesTo'],
  'chat_certificate_get': ['caseFileId', 'chatId', 'id'],
  'session_login': [],
  'session_info': [],
 };
