// Auto-generated by the g-digital MCP distribution pipeline.
// Source MCP: @g-digital/mcp-gocertius (1.2.19)
// Architecture: REST-direct (Epic 12 ADR 0008) — pure fetch(), no MCP subprocess.
// Operations: evidence_create, evidence_list, evidence_seal, evidence_get, evidence_group_create, evidence_group_list, dossier_create, dossier_update, dossier_certify, dossier_list, dossier_get, dossier_template_list, dossier_preview, dossier_document_url, dossier_package_url, dossier_visibility, dossier_delete, dossier_group_certify, dossier_evidence_link, dossier_evidence_list_to_link, dossier_evidence_list, dossier_evidence_get, dossier_evidence_delete, notification_document_add, notification_request_create, notification_request_send, notification_request_status, notification_receiver_add, notification_certificate_get, case_file_create, case_file_list, case_file_get, chat_create, chat_get, chat_invitation_url, chat_certificate_create, chat_certificate_get, session_login, session_info

import { randomUUID } from 'node:crypto';
import {
  IDataObject,
  IExecuteFunctions,
  INodeExecutionData,
  INodeType,
  INodeTypeDescription,
  NodeOperationError,
} from 'n8n-workflow';

export class Gocertius implements INodeType {
  description: INodeTypeDescription = {
    displayName: 'Gocertius',
    name: 'gocertius',
    group: ['transform'],
    version: 1,
    icon: 'file:icon.png',
    usableAsTool: true,
    codex: { categories: ['AI', 'Langchain'] },
    description: "Send and certify evidence, dossiers, notifications, and chats via the GoCertius platform.",
    defaults: { name: 'Gocertius' },
    inputs: ['main'],
    outputs: ['main'],
    credentials: [{ name: 'gocertiusApi', required: true }],
    properties: [
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        options: [
          {
            name: "Create Evidence",
            value: 'evidence_create',
            description: "Registers a new evidence record inside an evidence group.",
            action: "Create Evidence",
          },
          {
            name: "List Evidence",
            value: 'evidence_list',
            description: "Lists all evidence records within a specific evidence group.",
            action: "List Evidence",
          },
          {
            name: "Seal Evidence Group",
            value: 'evidence_seal',
            description: "Closes an evidence group and triggers certified timestamping.",
            action: "Seal Evidence Group",
          },
          {
            name: "Get Evidence",
            value: 'evidence_get',
            description: "Retrieves details and certification status of a specific evidence record.",
            action: "Get Evidence",
          },
          {
            name: "Create Evidence Group",
            value: 'evidence_group_create',
            description: "Creates a new evidence group inside an existing case file.",
            action: "Create Evidence Group",
          },
          {
            name: "List Evidence Groups",
            value: 'evidence_group_list',
            description: "Lists all evidence groups in a case file with their current status.",
            action: "List Evidence Groups",
          },
          {
            name: "Create Dossier",
            value: 'dossier_create',
            description: "Creates a dossier to aggregate certified evidence groups into a PDF.",
            action: "Create Dossier",
          },
          {
            name: "Update Dossier",
            value: 'dossier_update',
            description: "Updates metadata of a dossier that is still in draft status.",
            action: "Update Dossier",
          },
          {
            name: "Certify Dossier",
            value: 'dossier_certify',
            description: "Certifies a draft dossier, locking evidence and generating a tamper-evident PDF.",
            action: "Certify Dossier",
          },
          {
            name: "List Dossiers",
            value: 'dossier_list',
            description: "Lists all dossiers in a case file with their status and metadata.",
            action: "List Dossiers",
          },
          {
            name: "Get Dossier",
            value: 'dossier_get',
            description: "Retrieves full details of a dossier, including status and download URLs.",
            action: "Get Dossier",
          },
          {
            name: "List Dossier Templates",
            value: 'dossier_template_list',
            description: "Lists all available dossier templates with their IDs and translations.",
            action: "List Dossier Templates",
          },
          {
            name: "Preview Dossier",
            value: 'dossier_preview',
            description: "Returns an HTML preview URL for a dossier before certification.",
            action: "Preview Dossier",
          },
          {
            name: "Get Document URL",
            value: 'dossier_document_url',
            description: "Returns the download URL for a certified dossier PDF.",
            action: "Get Document URL",
          },
          {
            name: "Get Package URL",
            value: 'dossier_package_url',
            description: "Returns the download URL for the full certified dossier package including evidence files.",
            action: "Get Package URL",
          },
          {
            name: "Set Dossier Visibility",
            value: 'dossier_visibility',
            description: "Updates the public or private visibility of a certified dossier.",
            action: "Set Dossier Visibility",
          },
          {
            name: "Delete Dossier",
            value: 'dossier_delete',
            description: "Permanently deletes a dossier in draft or certified status.",
            action: "Delete Dossier",
          },
          {
            name: "Certify Group Dossier",
            value: 'dossier_group_certify',
            description: "Creates and certifies a dossier from a single sealed evidence group in one step.",
            action: "Certify Group Dossier",
          },
          {
            name: "Link Dossier Evidence",
            value: 'dossier_evidence_link',
            description: "Links specific evidence items to a draft dossier before certification.",
            action: "Link Dossier Evidence",
          },
          {
            name: "List Linkable Evidence",
            value: 'dossier_evidence_list_to_link',
            description: "Lists evidence items available to be linked to a dossier.",
            action: "List Linkable Evidence",
          },
          {
            name: "List Dossier Evidence",
            value: 'dossier_evidence_list',
            description: "Lists all evidence items currently linked to a dossier.",
            action: "List Dossier Evidence",
          },
          {
            name: "Get Dossier Evidence",
            value: 'dossier_evidence_get',
            description: "Retrieves details of a specific evidence item linked to a dossier.",
            action: "Get Dossier Evidence",
          },
          {
            name: "Delete Dossier Evidence",
            value: 'dossier_evidence_delete',
            description: "Removes an evidence item from a dossier while it is in draft status.",
            action: "Delete Dossier Evidence",
          },
          {
            name: "Add Notification Document",
            value: 'notification_document_add',
            description: "Attaches a document to an existing certified notification request.",
            action: "Add Notification Document",
          },
          {
            name: "Create Notification",
            value: 'notification_request_create',
            description: "Creates a certified notification request with HTML content for one or more recipients.",
            action: "Create Notification",
          },
          {
            name: "Send Notification",
            value: 'notification_request_send',
            description: "Triggers delivery of a certified notification to all added recipients.",
            action: "Send Notification",
          },
          {
            name: "Get Notification Status",
            value: 'notification_request_status',
            description: "Returns the current delivery status of a certified notification request.",
            action: "Get Notification Status",
          },
          {
            name: "Add Receiver",
            value: 'notification_receiver_add',
            description: "Adds a recipient to a certified notification request before sending.",
            action: "Add Receiver",
          },
          {
            name: "Get Notification Certificate",
            value: 'notification_certificate_get',
            description: "Generates a PDF delivery certificate for a specific notification recipient.",
            action: "Get Notification Certificate",
          },
          {
            name: "Create Case File",
            value: 'case_file_create',
            description: "Creates a top-level case file container for all GoCertius operations.",
            action: "Create Case File",
          },
          {
            name: "List Case Files",
            value: 'case_file_list',
            description: "Lists all case files in your GoCertius account with their status.",
            action: "List Case Files",
          },
          {
            name: "Get Case File",
            value: 'case_file_get',
            description: "Retrieves details of a specific case file by its ID.",
            action: "Get Case File",
          },
          {
            name: "Create Chat",
            value: 'chat_create',
            description: "Creates a certified Telegram chat channel linked to a personal case file.",
            action: "Create Chat",
          },
          {
            name: "Get Chat",
            value: 'chat_get',
            description: "Retrieves status and participant details of a certified chat channel.",
            action: "Get Chat",
          },
          {
            name: "Get Invitation URL",
            value: 'chat_invitation_url',
            description: "Returns the Telegram invitation URL for participants to join a certified chat.",
            action: "Get Invitation URL",
          },
          {
            name: "Create Chat Certificate",
            value: 'chat_certificate_create',
            description: "Creates a certificate for a range of messages from a certified chat channel.",
            action: "Create Chat Certificate",
          },
          {
            name: "Get Chat Certificate",
            value: 'chat_certificate_get',
            description: "Retrieves a chat certificate status and PDF download URL after certification.",
            action: "Get Chat Certificate",
          },
          {
            name: "Log In",
            value: 'session_login',
            description: "Authenticates with GoCertius using password or OpenID and returns a session.",
            action: "Log In",
          },
          {
            name: "Get Session Info",
            value: 'session_info',
            description: "Returns the authenticated user's session details including userId and session type.",
            action: "Get Session Info",
          },
        ],
        default: 'evidence_create',
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        description: "UUID of the case file",
        required: true,
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "EvidenceGroupId",
        name: 'evidenceGroupId',
        type: 'string',
        default: "",
        description: "UUID of the evidence group",
        required: true,
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "Id",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "Title",
        name: 'title',
        type: 'string',
        default: "",
        description: "Human-readable title for the evidence",
        required: true,
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "FileName",
        name: 'fileName',
        type: 'string',
        default: "",
        description: "Original file name including extension",
        required: true,
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "Hash",
        name: 'hash',
        type: 'string',
        default: "",
        description: "SHA-256 hex digest of the file content (64 hex chars)",
        required: true,
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "CustodyType",
        name: 'custodyType',
        type: 'options',
        options: [
          { name: "INTERNAL", value: "INTERNAL" },
          { name: "EXTERNAL", value: "EXTERNAL" },
        ],
        default: "INTERNAL",
        description: "INTERNAL = GoCertius stores the file; EXTERNAL = only hash registered",
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "FileUrl",
        name: 'fileUrl',
        type: 'string',
        default: "",
        description: "Optional public URL to download and auto-upload the file to S3 (custodyType INTERNAL only). Eliminates the manual PUT step.",
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_list'] } },
      },
      {
        displayName: "EvidenceGroupId",
        name: 'evidenceGroupId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_list'] } },
      },
      {
        displayName: "Filter",
        name: 'filter',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['evidence_list'] } },
      },
      {
        displayName: "Order",
        name: 'order',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['evidence_list'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['evidence_list'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "Id",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "EvidencesCount",
        name: 'evidencesCount',
        type: 'number',
        default: 0,
        required: true,
        typeOptions: {"minValue":1},
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "DeviceModel",
        name: 'deviceModel',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "DeviceManufacturer",
        name: 'deviceManufacturer',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "DeviceOS",
        name: 'deviceOS',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "LatitudeLocation",
        name: 'latitudeLocation',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "LongitudeLocation",
        name: 'longitudeLocation',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "AltitudeLocation",
        name: 'altitudeLocation',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "LocationAccuracy",
        name: 'locationAccuracy',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "UserAgent",
        name: 'userAgent',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "WebUrl",
        name: 'webUrl',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "Attestation",
        name: 'attestation',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_get'] } },
      },
      {
        displayName: "EvidenceGroupId",
        name: 'evidenceGroupId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_get'] } },
      },
      {
        displayName: "Id",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['evidence_get'] } },
      },
      {
        displayName: "Id",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['evidence_group_create'] } },
      },
      {
        displayName: "EvidenceType",
        name: 'evidenceType',
        type: 'options',
        options: [
          { name: "FILE", value: "FILE" },
          { name: "PHOTO", value: "PHOTO" },
          { name: "VIDEO", value: "VIDEO" },
          { name: "WEB_PLUGIN", value: "WEB_PLUGIN" },
        ],
        default: "FILE",
        required: true,
        displayOptions: { show: { operation: ['evidence_group_create'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_group_create'] } },
      },
      {
        displayName: "Item Description",
        name: 'description',
        type: 'string',
        default: "",
        description: "Short plain-text description (e.g. \"My case file\"). Required by the API.",
        required: true,
        displayOptions: { show: { operation: ['evidence_group_create'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_group_create'] } },
      },
      {
        displayName: "Attestation",
        name: 'attestation',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['evidence_group_create'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_group_list'] } },
      },
      {
        displayName: "Filter",
        name: 'filter',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['evidence_group_list'] } },
      },
      {
        displayName: "Order",
        name: 'order',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['evidence_group_list'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['evidence_group_list'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "DossierTemplateId",
        name: 'dossierTemplateId',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Purpose",
        name: 'purpose',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Id",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "ModelId",
        name: 'modelId',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "en_GB", value: "en_GB" },
          { name: "es_ES", value: "es_ES" },
          { name: "pt_PT", value: "pt_PT" },
        ],
        default: "en_GB",
        required: true,
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "FilledFields",
        name: 'filledFields',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "ValidityFrom",
        name: 'validityFrom',
        type: 'string',
        default: "",
        description: "ISO 8601 datetime (e.g. 2026-01-01T00:00:00.000Z). Leave empty — defaults to now.",
        required: true,
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "ValidityTo",
        name: 'validityTo',
        type: 'string',
        default: "",
        description: "ISO 8601 datetime. Leave empty — defaults to 1 year from now.",
        required: true,
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "AccessToken",
        name: 'accessToken',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "DossierId",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "DossierTemplateId",
        name: 'dossierTemplateId',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Purpose",
        name: 'purpose',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "ModelId",
        name: 'modelId',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "en_GB", value: "en_GB" },
          { name: "es_ES", value: "es_ES" },
          { name: "pt_PT", value: "pt_PT" },
        ],
        default: "en_GB",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "FilledFields",
        name: 'filledFields',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "ValidityFrom",
        name: 'validityFrom',
        type: 'string',
        default: "",
        description: "ISO 8601 datetime (e.g. 2026-01-01T00:00:00.000Z). Leave empty — defaults to now.",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "ValidityTo",
        name: 'validityTo',
        type: 'string',
        default: "",
        description: "ISO 8601 datetime. Leave empty — defaults to 1 year from now.",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "AccessToken",
        name: 'accessToken',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        description: "UUID of the case file that owns this dossier",
        required: true,
        displayOptions: { show: { operation: ['dossier_certify'] } },
      },
      {
        displayName: "DossierId",
        name: 'dossierId',
        type: 'string',
        default: "",
        description: "UUID of the dossier to certify (must be in DRAFT status)",
        required: true,
        displayOptions: { show: { operation: ['dossier_certify'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_list'] } },
      },
      {
        displayName: "Filter",
        name: 'filter',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_list'] } },
      },
      {
        displayName: "Order",
        name: 'order',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_list'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_list'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_get'] } },
      },
      {
        displayName: "DossierId",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_get'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_template_list'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_preview'] } },
      },
      {
        displayName: "DossierId",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_preview'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_document_url'] } },
      },
      {
        displayName: "DossierId",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_document_url'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_package_url'] } },
      },
      {
        displayName: "DossierId",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_package_url'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_visibility'] } },
      },
      {
        displayName: "DossierId",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_visibility'] } },
      },
      {
        displayName: "Visibility",
        name: 'visibility',
        type: 'options',
        options: [
          { name: "ACCESSIBLE", value: "ACCESSIBLE" },
          { name: "PENDING_RECALL", value: "PENDING_RECALL" },
          { name: "RECALLED", value: "RECALLED" },
        ],
        default: "ACCESSIBLE",
        required: true,
        displayOptions: { show: { operation: ['dossier_visibility'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_delete'] } },
      },
      {
        displayName: "DossierId",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_delete'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "EvidenceGroupId",
        name: 'evidenceGroupId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "Id",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "ModelId",
        name: 'modelId',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "EvidenceIds",
        name: 'evidenceIds',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "en_GB", value: "en_GB" },
          { name: "es_ES", value: "es_ES" },
          { name: "pt_PT", value: "pt_PT" },
        ],
        default: "en_GB",
        required: true,
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        description: "UUID of the case file that owns the dossier",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_link'] } },
      },
      {
        displayName: "DossierId",
        name: 'dossierId',
        type: 'string',
        default: "",
        description: "UUID of the DRAFT dossier to link evidences to",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_link'] } },
      },
      {
        displayName: "CaseFileToLinkId",
        name: 'caseFileToLinkId',
        type: 'string',
        default: "",
        description: "UUID of the case file containing the evidences (often same as caseFileId)",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_link'] } },
      },
      {
        displayName: "Ids",
        name: 'ids',
        type: 'json',
        default: {},
        description: "UUIDs of the evidence items to link",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_link'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_list_to_link'] } },
      },
      {
        displayName: "DossierId",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_list_to_link'] } },
      },
      {
        displayName: "CaseFileToLinkId",
        name: 'caseFileToLinkId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_list_to_link'] } },
      },
      {
        displayName: "Filter",
        name: 'filter',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_evidence_list_to_link'] } },
      },
      {
        displayName: "Order",
        name: 'order',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_evidence_list_to_link'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_evidence_list_to_link'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_list'] } },
      },
      {
        displayName: "DossierId",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_list'] } },
      },
      {
        displayName: "DossierEvidenceGroupId",
        name: 'dossierEvidenceGroupId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_list'] } },
      },
      {
        displayName: "Filter",
        name: 'filter',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_evidence_list'] } },
      },
      {
        displayName: "Order",
        name: 'order',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_evidence_list'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_evidence_list'] } },
      },
      {
        displayName: "DossierEvidenceGroupId",
        name: 'dossierEvidenceGroupId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_get'] } },
      },
      {
        displayName: "DossierId",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_get'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_get'] } },
      },
      {
        displayName: "DossierEvidenceId",
        name: 'dossierEvidenceId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_get'] } },
      },
      {
        displayName: "DossierEvidenceGroupId",
        name: 'dossierEvidenceGroupId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_delete'] } },
      },
      {
        displayName: "DossierId",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_delete'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_delete'] } },
      },
      {
        displayName: "DossierEvidenceId",
        name: 'dossierEvidenceId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_delete'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_document_add'] } },
      },
      {
        displayName: "NotificationRequestId",
        name: 'notificationRequestId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_document_add'] } },
      },
      {
        displayName: "Id",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['notification_document_add'] } },
      },
      {
        displayName: "FileName",
        name: 'fileName',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_document_add'] } },
      },
      {
        displayName: "Hash",
        name: 'hash',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_document_add'] } },
      },
      {
        displayName: "FileSize",
        name: 'fileSize',
        type: 'number',
        default: 0,
        displayOptions: { show: { operation: ['notification_document_add'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "Id",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "Type",
        name: 'type',
        type: 'options',
        options: [
          { name: "NO_RESPONSE", value: "NO_RESPONSE" },
          { name: "ACCEPTED_OR_NOT", value: "ACCEPTED_OR_NOT" },
          { name: "RECEIVED_AGREE", value: "RECEIVED_AGREE" },
        ],
        default: "NO_RESPONSE",
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "Subject",
        name: 'subject',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "Content (HTML)",
        name: 'content',
        type: 'string',
        default: "",
        description: "Must be valid HTML. Supported tags only: <p>, <strong>, <em>, <ul><li>, <ol><li>. No other tags or CSS. Example: <p>Your document is <strong>ready</strong> for review.</p>",
        required: true,
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "en_GB", value: "en_GB" },
          { name: "es_ES", value: "es_ES" },
        ],
        default: "en_GB",
        required: true,
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "OtpByDefault",
        name: 'otpByDefault',
        type: 'boolean',
        default: false,
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "SendWaUrlByDefault",
        name: 'sendWaUrlByDefault',
        type: 'boolean',
        default: false,
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_request_send'] } },
      },
      {
        displayName: "NotificationRequestId",
        name: 'notificationRequestId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_request_send'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_request_status'] } },
      },
      {
        displayName: "NotificationRequestId",
        name: 'notificationRequestId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_request_status'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "NotificationRequestId",
        name: 'notificationRequestId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "Id",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "FirstName",
        name: 'firstName',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "LastName",
        name: 'lastName',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "Email",
        name: 'email',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "PhoneNumber",
        name: 'phoneNumber',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "PhonePrefix",
        name: 'phonePrefix',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "OtpRequired",
        name: 'otpRequired',
        type: 'boolean',
        default: false,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "SendWaUrl",
        name: 'sendWaUrl',
        type: 'boolean',
        default: false,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_certificate_get'] } },
      },
      {
        displayName: "NotificationRequestId",
        name: 'notificationRequestId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_certificate_get'] } },
      },
      {
        displayName: "ReceiverId",
        name: 'receiverId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_certificate_get'] } },
      },
      {
        displayName: "Id",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['notification_certificate_get'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "en_GB", value: "en_GB" },
          { name: "es_ES", value: "es_ES" },
        ],
        default: "en_GB",
        displayOptions: { show: { operation: ['notification_certificate_get'] } },
      },
      {
        displayName: "Id",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['case_file_create'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['case_file_create'] } },
      },
      {
        displayName: "Reference",
        name: 'reference',
        type: 'string',
        default: "",
        description: "Optional user-defined reference code (max 32 chars, e.g. \"EXP-2026-001\"). Do not use a UUID.",
        displayOptions: { show: { operation: ['case_file_create'] } },
      },
      {
        displayName: "Item Description",
        name: 'description',
        type: 'string',
        default: "",
        description: "Short plain-text description (e.g. \"My case file\"). Required by the API.",
        required: true,
        displayOptions: { show: { operation: ['case_file_create'] } },
      },
      {
        displayName: "UseCaseId",
        name: 'useCaseId',
        type: 'string',
        default: "063a016a-1d62-4b7b-a24f-7cf4d1d289bf",
        description: "UUID of the use case. Default is the general GoCertius use case (063a016a-1d62-4b7b-a24f-7cf4d1d289bf). Change only if you need a specific use case.",
        required: true,
        displayOptions: { show: { operation: ['case_file_create'] } },
      },
      {
        displayName: "UserId",
        name: 'userId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['case_file_list'] } },
      },
      {
        displayName: "Filter",
        name: 'filter',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['case_file_list'] } },
      },
      {
        displayName: "Order",
        name: 'order',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['case_file_list'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['case_file_list'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['case_file_get'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "Id",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "Title",
        name: 'title',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "ServiceTitle",
        name: 'serviceTitle',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "ServiceDescription",
        name: 'serviceDescription',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "Service",
        name: 'service',
        type: 'options',
        options: [
          { name: "Telegram", value: "Telegram" },
        ],
        default: "Telegram",
        required: true,
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "en_GB", value: "en_GB" },
          { name: "es_ES", value: "es_ES" },
        ],
        default: "en_GB",
        required: true,
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_get'] } },
      },
      {
        displayName: "ChatId",
        name: 'chatId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_get'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_invitation_url'] } },
      },
      {
        displayName: "ChatId",
        name: 'chatId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_invitation_url'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "ChatId",
        name: 'chatId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "Id",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "en_GB", value: "en_GB" },
          { name: "es_ES", value: "es_ES" },
        ],
        default: "en_GB",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "ChatMessagesFrom",
        name: 'chatMessagesFrom',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "ChatMessagesTo",
        name: 'chatMessagesTo',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "CaseFileId",
        name: 'caseFileId',
        type: 'string',
        default: "",
        description: "UUID of the case file that owns the chat",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_get'] } },
      },
      {
        displayName: "ChatId",
        name: 'chatId',
        type: 'string',
        default: "",
        description: "UUID of the chat",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_get'] } },
      },
      {
        displayName: "Id",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_get'] } },
      },
    ],
  };

  async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
    const items = this.getInputData();
    const out: INodeExecutionData[] = [];
    const creds = await this.getCredentials('gocertiusApi');
    const baseUrl = String(creds.baseUrl ?? '').replace(/\/$/, '');

    // --- Obtain Bearer token (once per execute call) ---
    const loginRes = await fetch(`${baseUrl}/session`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        email: creds.MCP_AUTH_EMAIL ?? creds.email ?? '',
        password: creds.MCP_AUTH_PASSWORD ?? creds.password ?? '',
      }),
    });
    if (!loginRes.ok) {
      throw new NodeOperationError(this.getNode(), `Auth failed: HTTP ${loginRes.status}. Check MCP_AUTH_EMAIL and MCP_AUTH_PASSWORD.`);
    }
    const loginBody = await loginRes.json() as { jwt?: string; token?: string; accessToken?: string };
    const bearer = loginBody.jwt ?? loginBody.token ?? loginBody.accessToken ?? '';

    // --- Per-item REST calls ---
    for (let i = 0; i < items.length; i++) {
      try {
        const operation = this.getNodeParameter('operation', i) as string;
        const meta = OPERATION_META[operation];
        if (!meta) {
          throw new NodeOperationError(this.getNode(), `Unknown operation: ${operation}`, { itemIndex: i });
        }
        if (meta.stub) {
          throw new NodeOperationError(
            this.getNode(),
            `Operation '${operation}' requires n8n self-hosted with the @g-digital/mcp-* package. It is not available in n8n Cloud via this connector.`,
            { itemIndex: i },
          );
        }

        // Replace URL path params {paramName} from input; remaining args → body/query
        let url = `${baseUrl}${meta.urlTemplate}`;
        const propsForOp = OPERATION_PROPERTY_NAMES[operation] ?? [];
        const body: IDataObject = {};
        const isCreateOrAdd = operation.endsWith('_create') || operation.endsWith('_add');
        let generatedId: string | undefined;
        for (const propName of propsForOp) {
          let val = this.getNodeParameter(propName, i);
          // Auto-generate UUID for 'id' in _create/_add BEFORE the skip check
          if (propName === 'id' && isCreateOrAdd && (val === '' || val === null || val === undefined)) {
            val = randomUUID();
            generatedId = val as string;
          }
          if (val === '' || val === null || val === undefined) continue;
          if (typeof val === 'object' && !Array.isArray(val) && Object.keys(val as object).length === 0) continue;
          const placeholder = `{${propName}}`;
          if (url.includes(placeholder)) {
            url = url.replace(placeholder, encodeURIComponent(String(val)));
          } else {
            body[propName] = val;
          }
        }
        // Substitute any remaining {placeholder} patterns from credentials.
        // First try exact credential key names, then common API→credential aliases
        // (e.g. {email} in session_info maps to credential field MCP_AUTH_EMAIL).
        const credAliases: Record<string, string> = { email: 'MCP_AUTH_EMAIL' };
        for (const [credKey, credVal] of Object.entries(creds)) {
          const placeholder = `{${credKey}}`;
          if (url.includes(placeholder) && credVal) {
            url = url.replace(placeholder, encodeURIComponent(String(credVal)));
          }
        }
        for (const [alias, credKey] of Object.entries(credAliases)) {
          const placeholder = `{${alias}}`;
          if (url.includes(placeholder) && creds[credKey]) {
            url = url.replace(placeholder, encodeURIComponent(String(creds[credKey])));
          }
        }

        // --- Smart defaults for remaining body fields ---
        // validityFrom: default to now (ISO 8601)
        if ('validityFrom' in body && (body.validityFrom === '' || body.validityFrom === null || body.validityFrom === undefined)) {
          body.validityFrom = new Date().toISOString();
        }
        // validityTo: default to 1 year from now
        if ('validityTo' in body && (body.validityTo === '' || body.validityTo === null || body.validityTo === undefined)) {
          const oneYearLater = new Date();
          oneYearLater.setFullYear(oneYearLater.getFullYear() + 1);
          body.validityTo = oneYearLater.toISOString();
        }

        const isBodyless = meta.method === 'GET' || meta.method === 'DELETE';
        if (isBodyless && Object.keys(body).length > 0) {
          // hey-api client uses bracket notation for nested object query params,
          // matching the qs library used by NestJS on the server:
          // { filter: { ownerId: 'uuid' }, page: { number: 1, size: 20 } }
          //   → filter[ownerId]=uuid&page[number]=1&page[size]=20
          const flattenQs = (obj: IDataObject, prefix = ''): Array<[string, string]> => {
            const pairs: Array<[string, string]> = [];
            for (const [k, v] of Object.entries(obj)) {
              if (v === null || v === undefined || v === '') continue;
              const key = prefix ? `${prefix}[${k}]` : k;
              if (typeof v === 'object' && !Array.isArray(v)) {
                if (Object.keys(v as object).length === 0) continue;
                pairs.push(...flattenQs(v as IDataObject, key));
              } else if (Array.isArray(v)) {
                for (const item of v) pairs.push([`${key}[]`, String(item)]);
              } else {
                pairs.push([key, String(v)]);
              }
            }
            return pairs;
          };
          const pairs = flattenQs(body);
          if (pairs.length > 0) {
            url = `${url}?${new URLSearchParams(pairs).toString()}`;
          }
        }

        const apiRes = await fetch(url, {
          method: meta.method,
          headers: {
            Authorization: `Bearer ${bearer}`,
            ...(isBodyless ? {} : { 'Content-Type': 'application/json' }),
          },
          ...(isBodyless ? {} : { body: JSON.stringify(body) }),
        });

        if (!apiRes.ok) {
          const errText = await apiRes.text().catch(() => '');
          throw new NodeOperationError(
            this.getNode(),
            `${operation} failed: HTTP ${apiRes.status}${errText ? ` — ${errText.slice(0, 200)}` : ''}`,
            { itemIndex: i },
          );
        }

        // 204 No Content or empty body → return empty object
        const contentLength = apiRes.headers.get('content-length');
        const hasBody = apiRes.status !== 204 && contentLength !== '0';
        const json: IDataObject = hasBody
          ? await apiRes.json().catch(() => ({})) as IDataObject
          : {};
        // Inject auto-generated id with semantic field name so downstream nodes
        // can reference it directly (e.g. $json.caseFileId, $json.chatId).
        if (generatedId) {
          const semanticId = AUTO_ID_OUTPUT_FIELD[operation];
          if (semanticId && !json[semanticId]) json[semanticId] = generatedId;
          if (!json['id']) json['id'] = generatedId;
        }
        // chat_certificate_get: when CERTIFIED, fetch documentUrl via a second call
        if (operation === 'chat_certificate_get' && (json as IDataObject).status === 'CERTIFIED' && !json['documentUrl']) {
          try {
            const docUrlRes = await fetch(`${url}/document-url`, {
              headers: { Authorization: `Bearer ${bearer}` },
            });
            if (docUrlRes.ok) {
              const docData = await docUrlRes.json().catch(() => ({})) as IDataObject;
              if (docData.documentUrl) (json as IDataObject).documentUrl = docData.documentUrl;
            }
          } catch { /* non-fatal */ }
        }
        // session_info: inject userId decoded from JWT sub claim so callers
        // don't need a separate step to obtain the userId required by most operations.
        if (operation === 'session_info' && bearer) {
          try {
            const parts = bearer.split('.');
            if (parts.length === 3) {
              const pad = (s: string) => s + '='.repeat((4 - s.length % 4) % 4);
              const payload = JSON.parse(Buffer.from(pad(parts[1] ?? ''), 'base64').toString('utf8')) as IDataObject;
              const sub = payload.sub ?? payload.userId ?? payload.user_id;
              if (sub && !(json as IDataObject).userId) {
                (json as IDataObject).userId = sub;
              }
            }
          } catch { /* ignore decode errors */ }
        }
        out.push({ json: json as IDataObject });
      } catch (error) {
        if (this.continueOnFail()) {
          out.push({ json: this.getInputData(i)[0].json, error: error as NodeOperationError });
          continue;
        }
        throw error;
      }
    }

    return [out];
  }
}

// Semantic output field name for auto-generated 'id' values.
// When a _create/_add operation auto-generates a UUID for 'id', it is also
// injected into the output under this field name so downstream nodes can
// reference it with its domain-specific name (e.g. $json.caseFileId).
const AUTO_ID_OUTPUT_FIELD: Record<string, string> = {
  case_file_create: 'caseFileId',
  evidence_create: 'evidenceId',
  evidence_group_create: 'evidenceGroupId',
  dossier_create: 'dossierId',
  dossier_group_certify: 'dossierId',
  notification_request_create: 'notificationRequestId',
  notification_receiver_add: 'receiverId',
  notification_document_add: 'documentId',
  chat_create: 'chatId',
  chat_certificate_create: 'certificateId',
  signature_request_create: 'requestId',
  signature_group_create: 'groupId',
  signature_participant_create: 'signatoryId',
};

// HTTP metadata per operation — method + URL template.
// 'stub: true' means the tool has no REST annotation and requires self-hosted n8n.
const OPERATION_META: Record<string, { method: string; urlTemplate: string; stub?: true }> = {
  'evidence_create': { method: 'POST', urlTemplate: "/evidences" },
  'evidence_list': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences" },
  'evidence_seal': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/evidence-groups/{id}/close" },
  'evidence_get': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences/{id}" },
  'evidence_group_create': { method: 'POST', urlTemplate: "/evidence-groups" },
  'evidence_group_list': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/evidence-groups" },
  'dossier_create': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/dossiers" },
  'dossier_update': { method: 'PUT', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}" },
  'dossier_certify': { method: 'PUT', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/certify" },
  'dossier_list': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers" },
  'dossier_get': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}" },
  'dossier_template_list': { method: 'GET', urlTemplate: "/dossier-templates" },
  'dossier_preview': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/report-preview" },
  'dossier_document_url': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/document-url" },
  'dossier_package_url': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/package-url" },
  'dossier_visibility': { method: 'PUT', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/visibility" },
  'dossier_delete': { method: 'DELETE', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}" },
  'dossier_group_certify': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/dossier-express" },
  'dossier_evidence_link': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/case-files-to-link/{caseFileToLinkId}/link-evidences" },
  'dossier_evidence_list_to_link': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/case-files-to-link/{caseFileToLinkId}/evidences-to-link" },
  'dossier_evidence_list': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/evidence-groups/{dossierEvidenceGroupId}/evidences" },
  'dossier_evidence_get': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/evidence-groups/{dossierEvidenceGroupId}/evidences/{dossierEvidenceId}" },
  'dossier_evidence_delete': { method: 'DELETE', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/evidence-groups/{dossierEvidenceGroupId}/evidences/{dossierEvidenceId}" },
  'notification_document_add': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/notification-requests/{notificationRequestId}/documents" },
  'notification_request_create': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/notification-requests" },
  'notification_request_send': { method: 'PUT', urlTemplate: "/case-files/{caseFileId}/notification-requests/{notificationRequestId}/send" },
  'notification_request_status': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/notification-requests/{notificationRequestId}" },
  'notification_receiver_add': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers" },
  'notification_certificate_get': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers/{receiverId}/certificates" },
  'case_file_create': { method: 'POST', urlTemplate: "/case-files" },
  'case_file_list': { method: 'GET', urlTemplate: "/users/{userId}/case-files" },
  'case_file_get': { method: 'GET', urlTemplate: "/case-files/{caseFileId}" },
  'chat_create': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/chats" },
  'chat_get': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/chats/{chatId}" },
  'chat_invitation_url': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/chats/{chatId}/invitation-url" },
  'chat_certificate_create': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/chats/{chatId}/certificate-express" },
  'chat_certificate_get': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/chats/{chatId}/certificates/{id}" },
  'session_login': { method: 'POST', urlTemplate: "/session" },
  'session_info': { method: 'GET', urlTemplate: "/session-info/{email}" },
};

// Per-operation input property names for argument gathering.
const OPERATION_PROPERTY_NAMES: Record<string, readonly string[]> = {
  'evidence_create': ['caseFileId', 'evidenceGroupId', 'id', 'title', 'fileName', 'hash', 'custodyType', 'fileUrl'],
  'evidence_list': ['caseFileId', 'evidenceGroupId', 'filter', 'order', 'page'],
  'evidence_seal': ['caseFileId', 'id', 'evidencesCount', 'deviceModel', 'deviceManufacturer', 'deviceOS', 'latitudeLocation', 'longitudeLocation', 'altitudeLocation', 'locationAccuracy', 'userAgent', 'webUrl', 'attestation'],
  'evidence_get': ['caseFileId', 'evidenceGroupId', 'id'],
  'evidence_group_create': ['id', 'evidenceType', 'name', 'description', 'caseFileId', 'attestation'],
  'evidence_group_list': ['caseFileId', 'filter', 'order', 'page'],
  'dossier_create': ['caseFileId', 'dossierTemplateId', 'purpose', 'id', 'modelId', 'name', 'language', 'filledFields', 'validityFrom', 'validityTo', 'accessToken'],
  'dossier_update': ['caseFileId', 'dossierId', 'dossierTemplateId', 'purpose', 'modelId', 'name', 'language', 'filledFields', 'validityFrom', 'validityTo', 'accessToken'],
  'dossier_certify': ['caseFileId', 'dossierId'],
  'dossier_list': ['caseFileId', 'filter', 'order', 'page'],
  'dossier_get': ['caseFileId', 'dossierId'],
  'dossier_template_list': ['page'],
  'dossier_preview': ['caseFileId', 'dossierId'],
  'dossier_document_url': ['caseFileId', 'dossierId'],
  'dossier_package_url': ['caseFileId', 'dossierId'],
  'dossier_visibility': ['caseFileId', 'dossierId', 'visibility'],
  'dossier_delete': ['caseFileId', 'dossierId'],
  'dossier_group_certify': ['caseFileId', 'evidenceGroupId', 'id', 'modelId', 'evidenceIds', 'name', 'language'],
  'dossier_evidence_link': ['caseFileId', 'dossierId', 'caseFileToLinkId', 'ids'],
  'dossier_evidence_list_to_link': ['caseFileId', 'dossierId', 'caseFileToLinkId', 'filter', 'order', 'page'],
  'dossier_evidence_list': ['caseFileId', 'dossierId', 'dossierEvidenceGroupId', 'filter', 'order', 'page'],
  'dossier_evidence_get': ['dossierEvidenceGroupId', 'dossierId', 'caseFileId', 'dossierEvidenceId'],
  'dossier_evidence_delete': ['dossierEvidenceGroupId', 'dossierId', 'caseFileId', 'dossierEvidenceId'],
  'notification_document_add': ['caseFileId', 'notificationRequestId', 'id', 'fileName', 'hash', 'fileSize'],
  'notification_request_create': ['caseFileId', 'id', 'type', 'subject', 'content', 'language', 'otpByDefault', 'sendWaUrlByDefault'],
  'notification_request_send': ['caseFileId', 'notificationRequestId'],
  'notification_request_status': ['caseFileId', 'notificationRequestId'],
  'notification_receiver_add': ['caseFileId', 'notificationRequestId', 'id', 'firstName', 'lastName', 'email', 'phoneNumber', 'phonePrefix', 'otpRequired', 'sendWaUrl'],
  'notification_certificate_get': ['caseFileId', 'notificationRequestId', 'receiverId', 'id', 'language'],
  'case_file_create': ['id', 'name', 'reference', 'description', 'useCaseId'],
  'case_file_list': ['userId', 'filter', 'order', 'page'],
  'case_file_get': ['caseFileId'],
  'chat_create': ['caseFileId', 'id', 'title', 'serviceTitle', 'serviceDescription', 'service', 'language'],
  'chat_get': ['caseFileId', 'chatId'],
  'chat_invitation_url': ['caseFileId', 'chatId'],
  'chat_certificate_create': ['caseFileId', 'chatId', 'id', 'name', 'language', 'chatMessagesFrom', 'chatMessagesTo'],
  'chat_certificate_get': ['caseFileId', 'chatId', 'id'],
  'session_login': [],
  'session_info': [],
 };
