// Auto-generated by the g-digital MCP distribution pipeline.
// Source MCP: @g-digital/mcp-gocertius (1.4.0)
// Architecture: REST-direct (Epic 12 ADR 0008) — pure fetch(), no MCP subprocess.
// Operations: evidence_create, evidence_list, evidence_seal, evidence_get, evidence_group_create, evidence_group_list, dossier_create, dossier_update, dossier_certify, dossier_list, dossier_get, dossier_template_list, dossier_preview, dossier_document_url, dossier_package_url, dossier_visibility, dossier_delete, dossier_group_certify, dossier_evidence_link, dossier_evidence_list_to_link, dossier_evidence_list, dossier_evidence_get, dossier_evidence_delete, notification_document_add, notification_request_create, notification_request_send, notification_request_status, notification_receiver_add, notification_certificate_get, case_file_create, case_file_list, case_file_get, chat_create, chat_get, chat_invitation_url, chat_certificate_create, chat_certificate_get, session_login, session_info

import { randomUUID } from 'node:crypto';
import {
  IDataObject,
  IExecuteFunctions,
  INodeExecutionData,
  INodeType,
  INodeTypeDescription,
  NodeApiError,
  NodeOperationError,
} from 'n8n-workflow';

export class Gocertius implements INodeType {
  description: INodeTypeDescription = {
    displayName: 'GoCertius',
    name: 'gocertius',
    group: ['transform'],
    version: 1,
    icon: 'file:icon.png',
    usableAsTool: true,
    description: "MCP server for GoCertius: certified evidence, dossiers, notifications and chats via AI agents.",
    defaults: { name: 'GoCertius' },
    inputs: ['main'],
    outputs: ['main'],
    credentials: [{ name: 'gocertiusApi', required: true }],
    properties: [
      {
        displayName: 'Resource',
        name: 'resource',
        type: 'options',
        noDataExpression: true,
        options: [
          { name: "Case File", value: 'caseFile' },
          { name: "Evidence", value: 'evidence' },
          { name: "Dossier Evidence", value: 'dossierEvidence' },
          { name: "Dossier", value: 'dossier' },
          { name: "Notification", value: 'notification' },
          { name: "Chat", value: 'chat' },
          { name: "Session", value: 'session' },
        ],
        default: 'caseFile',
      },
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['caseFile'] } },
        options: [
          {
            name: "Create Case File",
            value: 'case_file_create',
            description: "Creates a new case file — the top-level container for all related operations (evidence, notifications, dossiers, chats). Call this first before any other operation. Generate a UUID v4 for `id`. For `useCaseId`, use the general GoCertius use case: `063a016a-1d62-4b7b-a24f-7cf4d1d289bf` unless a specific use case is required. Returns caseFileId needed for all subsequent calls.",
            action: "Create Case File",
          },
          {
            name: "List Case File",
            value: 'case_file_list',
            description: "Lists all case files in your GoCertius account. Pass userId (from session_login or session_info) to scope results to your account. Returns paginated list with IDs, names, and status.",
            action: "List Case File",
          },
          {
            name: "Get Case File",
            value: 'case_file_get',
            description: "Retrieves details of a specific case file. Requires: caseFileId. Use to verify a case file exists before creating evidence groups, dossiers, or notifications.",
            action: "Get Case File",
          },
        ],
        default: 'case_file_create',
      },
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['evidence'] } },
        options: [
          {
            name: "Create Evidence",
            value: 'evidence_create',
            description: "Registers a NEW evidence record inside an evidence group. Requires: evidence_group_create → evidenceGroupId, case_file_create → caseFileId. Generate a UUID v4 for `id`. Compute the SHA-256 hex hash of the file BEFORE calling. Normal INTERNAL flow: call evidence_create with custodyType INTERNAL and NO fileUrl; the API returns uploadFileUrl, a presigned S3 URL. You MUST PUT the exact file bytes to uploadFileUrl, then verify with evidence_get/evidence_list, and ONLY THEN call evidence_seal. Do not seal an evidence group until every INTERNAL evidence file has been uploaded. Convenience flow: if you pass `fileUrl` (public HTTPS, no redirects, under 1 GiB), this tool downloads that URL and PUTs the bytes to uploadFileUrl for you. EXTERNAL flow: use custodyType EXTERNAL only when you intentionally register hash-only evidence; still generate a fresh UUID for each evidence. If an INTERNAL evidence creation/upload failed and you want to retry as EXTERNAL, create a NEW evidence id; do not reuse an id whose outcome is unknown. WARNING: the API sometimes returns {code:'EvidenceCreateError'} even when the evidence was successfully persisted — always verify with evidence_list before retrying.",
            action: "Create Evidence",
          },
          {
            name: "List Evidence",
            value: 'evidence_list',
            description: "Lists all evidence records in a specific evidence group. Use to review uploaded documents before sealing the group, or to find a specific evidenceId. Requires: caseFileId and evidenceGroupId. Returns paginated list with IDs, titles, status, and timestamps.",
            action: "List Evidence",
          },
          {
            name: "Seal Evidence",
            value: 'evidence_seal',
            description: "Seal and certify an evidence group. Closes the group to new additions and triggers async timestamping. Returns immediately — the group transitions OPEN → CLOSING → CLOSED. Poll evidence_group_list until status is CLOSED before linking to a dossier.",
            action: "Seal Evidence",
          },
          {
            name: "Get Evidence",
            value: 'evidence_get',
            description: "Retrieves a specific evidence record. Requires: evidence_create → evidenceId, evidence_group_create → evidenceGroupId, case_file_create → caseFileId. Returns status (COMPLETED|IN_PROCESS|ERROR), hash, and tspTimestamp when certified.",
            action: "Get Evidence",
          },
          {
            name: "Create Evidence Group",
            value: 'evidence_group_create',
            description: "Creates an evidence group inside a case file. Requires: case_file_create → caseFileId. Generate a UUID v4 for `id`. Set evidenceType to FILE, PHOTO, VIDEO, or WEB_PLUGIN. Returns evidenceGroupId. One group can contain multiple evidence records.",
            action: "Create Evidence Group",
          },
          {
            name: "List Evidence Group",
            value: 'evidence_group_list',
            description: "Lists all evidence groups in a case file with their current status (OPEN, CLOSING, CLOSED). Use to find an existing group or check which groups are ready for sealing. Requires: caseFileId.",
            action: "List Evidence Group",
          },
        ],
        default: 'evidence_create',
      },
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['dossierEvidence'] } },
        options: [
          {
            name: "Link Dossier Evidence",
            value: 'dossier_evidence_link',
            description: "Links specific evidence items to a DRAFT dossier. Call once per case file containing evidences to link. After linking all evidences, call dossier_certify to finalize. For a single-group dossier, use dossier_group_certify instead (one step). Example: dossier_evidence_link({ caseFileId: '...', dossierId: '...', caseFileToLinkId: '...', ids: ['ev-uuid-1', 'ev-uuid-2'] })",
            action: "Link Dossier Evidence",
          },
          {
            name: "Dossier Evidence List To Link",
            value: 'dossier_evidence_list_to_link',
            description: "Lists evidence items that are available to be linked to a dossier (CLOSED groups not yet linked). Requires: caseFileId and dossierId.",
            action: "Dossier Evidence List To Link",
          },
          {
            name: "List Dossier Evidence",
            value: 'dossier_evidence_list',
            description: "Lists all evidence items linked to a dossier. Requires: caseFileId and dossierId.",
            action: "List Dossier Evidence",
          },
          {
            name: "Get Dossier Evidence",
            value: 'dossier_evidence_get',
            description: "Retrieves details of a specific evidence item linked to a dossier. Requires: caseFileId, dossierId, evidenceId.",
            action: "Get Dossier Evidence",
          },
          {
            name: "Delete Dossier Evidence",
            value: 'dossier_evidence_delete',
            description: "Removes an evidence item from a dossier. Only available while dossier is in DRAFT status. Requires: caseFileId, dossierId, evidenceId.",
            action: "Delete Dossier Evidence",
          },
        ],
        default: 'dossier_evidence_link',
      },
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['dossier'] } },
        options: [
          {
            name: "Create Dossier",
            value: 'dossier_create',
            description: "Creates a dossier to aggregate certified evidence groups into a single tamper-evident PDF. Requires: case_file_create → caseFileId. Evidence groups must be in CLOSED status before linking. Generate a UUID v4 string for `id`. Returns dossierId. After creation, link evidence with dossier_evidence_link, then certify with dossier_certify.",
            action: "Create Dossier",
          },
          {
            name: "Update Dossier",
            value: 'dossier_update',
            description: "Updates the metadata of an existing dossier (name, template fields, expiry). Requires: dossier_create → dossierId, caseFileId. Only available while dossier is in DRAFT status.",
            action: "Update Dossier",
          },
          {
            name: "Certify Dossier",
            value: 'dossier_certify',
            description: "Certifies a DRAFT dossier, locking in all its associated evidence groups. The dossier must be in DRAFT status. After certification it transitions to CERTIFIED and a tamper-evident PDF is generated. Prerequisites: the dossier must exist (dossier_create) and have evidence groups linked. Use dossier_group_certify instead if you want to create + certify in one step from a single evidence group. Example: dossier_certify({ caseFileId: '...', dossierId: '...' })",
            action: "Certify Dossier",
          },
          {
            name: "List Dossier",
            value: 'dossier_list',
            description: "Lists all dossiers in a case file with their status and metadata. Use to find an existing dossierId or monitor certification progress. Requires: caseFileId. Returns paginated list with IDs, names, status, and creation dates.",
            action: "List Dossier",
          },
          {
            name: "Get Dossier",
            value: 'dossier_get',
            description: "Retrieves the full details of a specific dossier including status, linked evidence, and download URLs. Use to check current state or get certificate download URLs after CERTIFIED. Requires: caseFileId and dossierId.",
            action: "Get Dossier",
          },
          {
            name: "List Dossier Template",
            value: 'dossier_template_list',
            description: "Lists available dossier templates. No prerequisites. Returns template IDs and their translations per language. Use the returned id as dossierTemplateId in dossier_create.",
            action: "List Dossier Template",
          },
          {
            name: "Preview Dossier",
            value: 'dossier_preview',
            description: "Returns an HTML preview URL of a dossier before certification. Requires: caseFileId and dossierId.",
            action: "Preview Dossier",
          },
          {
            name: "Dossier Document Url",
            value: 'dossier_document_url',
            description: "Returns the download URL for the certified dossier PDF. Requires: dossier_certify (CERTIFIED status), caseFileId, dossierId.",
            action: "Dossier Document Url",
          },
          {
            name: "Dossier Package Url",
            value: 'dossier_package_url',
            description: "Returns the download URL for the full dossier package (PDF + evidence files). Requires: dossier_certify (CERTIFIED status), caseFileId, dossierId.",
            action: "Dossier Package Url",
          },
          {
            name: "Dossier Visibility",
            value: 'dossier_visibility',
            description: "Updates the visibility (public/private) of a certified dossier. Requires: dossier_certify (CERTIFIED status), caseFileId, dossierId.",
            action: "Dossier Visibility",
          },
          {
            name: "Delete Dossier",
            value: 'dossier_delete',
            description: "Deletes a dossier. Available in DRAFT status (to discard before certification) or in CERTIFIED status (to permanently remove the certified dossier). Irreversible. Requires: caseFileId and dossierId.",
            action: "Delete Dossier",
          },
          {
            name: "Certify Dossier Group",
            value: 'dossier_group_certify',
            description: "Creates AND certifies a dossier from a single sealed evidence group in one call (express path). Requires: evidence_seal (CLOSED status), case_file_create → caseFileId, evidence_group_create → evidenceGroupId. Generate a UUID v4 string for `id`. Use when you have exactly one sealed evidence group and don't need multi-group aggregation. Returns dossierId immediately with CERTIFYING status → poll until CERTIFIED.",
            action: "Certify Dossier Group",
          },
        ],
        default: 'dossier_create',
      },
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['notification'] } },
        options: [
          {
            name: "Add Notification Document",
            value: 'notification_document_add',
            description: "Performs the notification_document_add operation. Review the API documentation for full field details.",
            action: "Add Notification Document",
          },
          {
            name: "Create Notification Request",
            value: 'notification_request_create',
            description: "Creates a certified notification request. Requires: case_file_create → caseFileId. Generate a UUID v4 for `id`. Set language to en_GB or es_ES. Returns notificationRequestId. Add at least one receiver with notification_receiver_add before sending. IMPORTANT: The `content` field must be valid HTML — plain text without HTML tags will not render on the recipient landing page. Only the following HTML formats are supported: paragraphs (<p>), bold (<strong>), italic (<em>), unordered lists (<ul><li>), ordered lists (<ol><li>). Do not use other HTML tags or CSS. Avoid special typographic characters (em dashes, smart quotes) in `subject`; use standard ASCII equivalents (hyphen, straight quotes) instead.",
            action: "Create Notification Request",
          },
          {
            name: "Send Notification Request",
            value: 'notification_request_send',
            description: "Trigger delivery of a certified notification to all added recipients. Returns immediately — delivery is async. Poll notification_request_status until status is DELIVERED before retrieving certificates.",
            action: "Send Notification Request",
          },
          {
            name: "Notification Request Status",
            value: 'notification_request_status',
            description: "Checks the delivery status of a certified notification. Requires: notificationRequestId, caseFileId. Returns status (CREATING|DRAFT|IN_PROCESS|SENT|PARTIALLY_READ|FULLY_READ|PARTIALLY_ANSWERED|FULLY_ANSWERED). Poll until status is SENT or beyond. Do not call notification_certificate_get while status is CREATING, DRAFT, or IN_PROCESS.",
            action: "Notification Request Status",
          },
          {
            name: "Add Notification Receiver",
            value: 'notification_receiver_add',
            description: "Adds a recipient to a notification request. Requires: notification_request_create → notificationRequestId, case_file_create → caseFileId. The `id` can be a UUID v4 or custom string (e.g. your internal user ID). Returns receiverId — save it for notification_certificate_get. Add all receivers before calling notification_request_send.",
            action: "Add Notification Receiver",
          },
          {
            name: "Get Notification Certificate",
            value: 'notification_certificate_get',
            description: "Creates or retrieves a PDF certificate for a specific notification receiver. Requires notification_request_send and notification_receiver_add. Generate a UUID v4 for `id` the first time and reuse that id when polling. This tool is idempotent: it first lists existing certificates for the receiver and, if `id` already exists, returns it instead of creating it again. If the certificate status is CERTIFIED, the response includes documentUrl when available. If it is CERTIFYING, poll this same tool with the same id.",
            action: "Get Notification Certificate",
          },
        ],
        default: 'notification_document_add',
      },
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['chat'] } },
        options: [
          {
            name: "Create Chat",
            value: 'chat_create',
            description: "Creates a certified chat channel (Telegram). IMPORTANT: Chats can only be created in the user's personal case file (created automatically when the GoCertius account was opened). Do not use a manually created case file — use session_info → case_file_list to find the personal case file (oldest createdAt, owned by the user). Generate a UUID v4 for `id`. Set service to Telegram. Returns immediately and the chat may start in status `creating`; call chat_get and wait until it is registered/active before requesting the invitation URL or certificates.",
            action: "Create Chat",
          },
          {
            name: "Get Chat",
            value: 'chat_get',
            description: "Retrieves details of a certified chat. Requires: personal caseFileId and chat_create → chatId. Returns status, participants, and registeredAt timestamp. After chat_create, poll chat_get until status is active/registered and registeredAt is present; createdAt is not enough for certificate creation.",
            action: "Get Chat",
          },
          {
            name: "Chat Invitation Url",
            value: 'chat_invitation_url',
            description: "Returns the Telegram invitation URL for a certified chat. Requires: chat_create → chatId and the personal caseFileId. Do not call while chat_get still shows status `creating`; wait until the chat is registered/active, otherwise the API can answer Chat not found. Share the returned invitationUrl with participants so they can join the certified channel.",
            action: "Chat Invitation Url",
          },
          {
            name: "Create Chat Certificate",
            value: 'chat_certificate_create',
            description: "Creates a certificate of a range of messages from a certified chat. Requires: chat_create → chatId, personal caseFileId, chat_get → registeredAt, and messages already present in the Telegram channel. Generate a UUID v4 for `id`. Do not use createdAt as a substitute for registeredAt; if registeredAt is missing, the chat is not ready to certify. Specify chatMessagesFrom and chatMessagesTo as ISO timestamps (chatMessagesFrom must be AFTER registeredAt). ASYNC: poll chat_certificate_get until status === CERTIFIED.",
            action: "Create Chat Certificate",
          },
          {
            name: "Get Chat Certificate",
            value: 'chat_certificate_get',
            description: "Retrieves a certified chat certificate including its status, message range, and PDF download URL. Prerequisites: the certificate must have been created with chat_certificate_create. Returns documentUrl when status is CERTIFIED. Example: chat_certificate_get({ caseFileId: '...', chatId: '...', id: '...' })",
            action: "Get Chat Certificate",
          },
        ],
        default: 'chat_create',
      },
      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['session'] } },
        options: [
          {
            name: "Login Session",
            value: 'session_login',
            description: "Authenticate with GoCertius. Reads MCP_AUTH_EMAIL to discover the auth type (Password or OpenId) for that account. For Password accounts: uses MCP_AUTH_PASSWORD to obtain a session JWT. For OpenId accounts: starts an Azure AD device flow — on the FIRST call returns a browser link and code for the user to approve with Microsoft Authenticator; call session_login AGAIN after approving to complete authentication.",
            action: "Login Session",
          },
          {
            name: "Session Info",
            value: 'session_info',
            description: "Returns the authenticated user's session info including userId, session type (Password or OpenId), and for OpenId sessions: issuer, clientId, and scopes. Use this to retrieve the userId (UUID) required by case_file_list and other user-scoped operations. Prerequisites: a valid session (call session_login first if needed). Example: session_info() → { userId: '...uuid...', type: 'Password' }",
            action: "Session Info",
          },
        ],
        default: 'session_login',
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        description: "UUID of the case file",
        required: true,
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "Evidence Group ID",
        name: 'evidenceGroupId',
        type: 'string',
        default: "",
        description: "UUID of the evidence group",
        required: true,
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "Title",
        name: 'title',
        type: 'string',
        default: "",
        description: "Human-readable title for the evidence",
        required: true,
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "File Name",
        name: 'fileName',
        type: 'string',
        default: "",
        description: "Original file name including extension",
        required: true,
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "Hash",
        name: 'hash',
        type: 'string',
        default: "",
        description: "SHA-256 hex digest of the file content (64 hex chars)",
        required: true,
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "Custody Type",
        name: 'custodyType',
        type: 'options',
        options: [
          { name: "Internal", value: "INTERNAL" },
          { name: "External", value: "EXTERNAL" },
        ],
        default: "INTERNAL",
        description: "Who holds the file. INTERNAL = the platform stores and custodies it. EXTERNAL = it lives outside; only its hash is attested.",
        required: true,
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "File URL",
        name: 'fileUrl',
        type: 'string',
        default: "",
        description: "Optional public HTTPS URL to download and auto-upload to the returned uploadFileUrl (custodyType INTERNAL only). Omit this when you want the manual presigned-URL flow.",
        displayOptions: { show: { operation: ['evidence_create'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_list'] } },
      },
      {
        displayName: "Evidence Group ID",
        name: 'evidenceGroupId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_list'] } },
      },
      {
        displayName: "Filter",
        name: 'filter',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['evidence_list'] } },
      },
      {
        displayName: "Order",
        name: 'order',
        type: 'json',
        default: {},
        description: "Sort direction / ordering for the results.",
        displayOptions: { show: { operation: ['evidence_list'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        description: "Zero-based page number for paginated results (e.g. 0 for the first page).",
        displayOptions: { show: { operation: ['evidence_list'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "Evidences Count",
        name: 'evidencesCount',
        type: 'number',
        default: 0,
        required: true,
        typeOptions: {"minValue":1},
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "Web URL",
        name: 'webUrl',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['evidence_seal'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_get'] } },
      },
      {
        displayName: "Evidence Group ID",
        name: 'evidenceGroupId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_get'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        displayOptions: { show: { operation: ['evidence_get'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        displayOptions: { show: { operation: ['evidence_group_create'] } },
      },
      {
        displayName: "Evidence Type",
        name: 'evidenceType',
        type: 'options',
        options: [
          { name: "File", value: "FILE" },
          { name: "Photo", value: "PHOTO" },
          { name: "Video", value: "VIDEO" },
          { name: "Web Plugin", value: "WEB_PLUGIN" },
        ],
        default: "FILE",
        required: true,
        displayOptions: { show: { operation: ['evidence_group_create'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_group_create'] } },
      },
      {
        displayName: "Item Description",
        name: 'description',
        type: 'string',
        default: "",
        description: "Short plain-text description (e.g. \"My case file\"). Required by the API.",
        required: true,
        displayOptions: { show: { operation: ['evidence_group_create'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_group_create'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['evidence_group_list'] } },
      },
      {
        displayName: "Filter",
        name: 'filter',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['evidence_group_list'] } },
      },
      {
        displayName: "Order",
        name: 'order',
        type: 'json',
        default: {},
        description: "Sort direction / ordering for the results.",
        displayOptions: { show: { operation: ['evidence_group_list'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        description: "Zero-based page number for paginated results (e.g. 0 for the first page).",
        displayOptions: { show: { operation: ['evidence_group_list'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Dossier Template ID",
        name: 'dossierTemplateId',
        type: 'string',
        default: "",
        description: "UUID of the dossier template to use. Mandatory — the template also determines which of evidenceIds / filledFields you must supply.",
        required: true,
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Purpose",
        name: 'purpose',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Model ID",
        name: 'modelId',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "English (UK)", value: "en_GB" },
          { name: "Spanish (Spain)", value: "es_ES" },
          { name: "Portuguese (Portugal)", value: "pt_PT" },
        ],
        default: "en_GB",
        description: "Language used for generated documents and notices.",
        required: true,
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Filled Fields",
        name: 'filledFields',
        type: 'json',
        default: {},
        description: "Template field values. REQUIRED by some dossier templates — which ones depends on the dossierTemplateId you chose.",
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Validity From",
        name: 'validityFrom',
        type: 'string',
        default: "",
        description: "ISO 8601 datetime (e.g. 2026-01-01T00:00:00.000Z). Leave empty — defaults to now.",
        required: true,
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Validity To",
        name: 'validityTo',
        type: 'string',
        default: "",
        description: "ISO 8601 datetime. Leave empty — defaults to 1 year from now.",
        required: true,
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Access Token",
        name: 'accessToken',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_create'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Dossier Template ID",
        name: 'dossierTemplateId',
        type: 'string',
        default: "",
        description: "UUID of the dossier template to use. Mandatory — the template also determines which of evidenceIds / filledFields you must supply.",
        required: true,
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Purpose",
        name: 'purpose',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Model ID",
        name: 'modelId',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "English (UK)", value: "en_GB" },
          { name: "Spanish (Spain)", value: "es_ES" },
          { name: "Portuguese (Portugal)", value: "pt_PT" },
        ],
        default: "en_GB",
        description: "Language used for generated documents and notices.",
        required: true,
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Filled Fields",
        name: 'filledFields',
        type: 'json',
        default: {},
        description: "Template field values. REQUIRED by some dossier templates — which ones depends on the dossierTemplateId you chose.",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Access Token",
        name: 'accessToken',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_update'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        description: "UUID of the case file that owns this dossier",
        required: true,
        displayOptions: { show: { operation: ['dossier_certify'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        description: "UUID of the dossier to certify (must be in DRAFT status)",
        required: true,
        displayOptions: { show: { operation: ['dossier_certify'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_list'] } },
      },
      {
        displayName: "Filter",
        name: 'filter',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_list'] } },
      },
      {
        displayName: "Order",
        name: 'order',
        type: 'json',
        default: {},
        description: "Sort direction / ordering for the results.",
        displayOptions: { show: { operation: ['dossier_list'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        description: "Zero-based page number for paginated results (e.g. 0 for the first page).",
        displayOptions: { show: { operation: ['dossier_list'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_get'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_get'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        description: "Zero-based page number for paginated results (e.g. 0 for the first page).",
        displayOptions: { show: { operation: ['dossier_template_list'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_preview'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_preview'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_document_url'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_document_url'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_package_url'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_package_url'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_visibility'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_visibility'] } },
      },
      {
        displayName: "Visibility",
        name: 'visibility',
        type: 'options',
        options: [
          { name: "Accessible", value: "ACCESSIBLE" },
          { name: "Pending Recall", value: "PENDING_RECALL" },
          { name: "Recalled", value: "RECALLED" },
        ],
        default: "ACCESSIBLE",
        required: true,
        displayOptions: { show: { operation: ['dossier_visibility'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_delete'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_delete'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "Evidence Group ID",
        name: 'evidenceGroupId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "Model ID",
        name: 'modelId',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "Evidence IDs",
        name: 'evidenceIds',
        type: 'json',
        default: {},
        description: "Evidence UUIDs to include. REQUIRED by some dossier templates — which ones depends on the dossierTemplateId you chose.",
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "English (UK)", value: "en_GB" },
          { name: "Spanish (Spain)", value: "es_ES" },
          { name: "Portuguese (Portugal)", value: "pt_PT" },
        ],
        default: "en_GB",
        description: "Language used for generated documents and notices.",
        required: true,
        displayOptions: { show: { operation: ['dossier_group_certify'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        description: "UUID of the case file that owns the dossier",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_link'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        description: "UUID of the DRAFT dossier to link evidences to",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_link'] } },
      },
      {
        displayName: "Case File To Link ID",
        name: 'caseFileToLinkId',
        type: 'string',
        default: "",
        description: "UUID of the case file containing the evidences (often same as caseFileId)",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_link'] } },
      },
      {
        displayName: "IDs",
        name: 'ids',
        type: 'json',
        default: {},
        description: "UUIDs of the evidence items to link",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_link'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_list_to_link'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_list_to_link'] } },
      },
      {
        displayName: "Case File To Link ID",
        name: 'caseFileToLinkId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_list_to_link'] } },
      },
      {
        displayName: "Filter",
        name: 'filter',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_evidence_list_to_link'] } },
      },
      {
        displayName: "Order",
        name: 'order',
        type: 'json',
        default: {},
        description: "Sort direction / ordering for the results.",
        displayOptions: { show: { operation: ['dossier_evidence_list_to_link'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        description: "Zero-based page number for paginated results (e.g. 0 for the first page).",
        displayOptions: { show: { operation: ['dossier_evidence_list_to_link'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_list'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_list'] } },
      },
      {
        displayName: "Dossier Evidence Group ID",
        name: 'dossierEvidenceGroupId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_list'] } },
      },
      {
        displayName: "Filter",
        name: 'filter',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['dossier_evidence_list'] } },
      },
      {
        displayName: "Order",
        name: 'order',
        type: 'json',
        default: {},
        description: "Sort direction / ordering for the results.",
        displayOptions: { show: { operation: ['dossier_evidence_list'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        description: "Zero-based page number for paginated results (e.g. 0 for the first page).",
        displayOptions: { show: { operation: ['dossier_evidence_list'] } },
      },
      {
        displayName: "Dossier Evidence Group ID",
        name: 'dossierEvidenceGroupId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_get'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_get'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_get'] } },
      },
      {
        displayName: "Dossier Evidence ID",
        name: 'dossierEvidenceId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_get'] } },
      },
      {
        displayName: "Dossier Evidence Group ID",
        name: 'dossierEvidenceGroupId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_delete'] } },
      },
      {
        displayName: "Dossier ID",
        name: 'dossierId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_delete'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_delete'] } },
      },
      {
        displayName: "Dossier Evidence ID",
        name: 'dossierEvidenceId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['dossier_evidence_delete'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_document_add'] } },
      },
      {
        displayName: "Notification Request ID",
        name: 'notificationRequestId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_document_add'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        displayOptions: { show: { operation: ['notification_document_add'] } },
      },
      {
        displayName: "File Name",
        name: 'fileName',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_document_add'] } },
      },
      {
        displayName: "Hash",
        name: 'hash',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_document_add'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "Type",
        name: 'type',
        type: 'options',
        options: [
          { name: "No Response", value: "NO_RESPONSE" },
          { name: "Accepted Or Not", value: "ACCEPTED_OR_NOT" },
          { name: "Received Agree", value: "RECEIVED_AGREE" },
        ],
        default: "NO_RESPONSE",
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "Subject",
        name: 'subject',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "Content (HTML)",
        name: 'content',
        type: 'string',
        default: "",
        description: "Must be valid HTML. Supported tags only: <p>, <strong>, <em>, <ul><li>, <ol><li>. No other tags or CSS. Example: <p>Your document is <strong>ready</strong> for review.</p>",
        required: true,
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "English (UK)", value: "en_GB" },
          { name: "Spanish (Spain)", value: "es_ES" },
        ],
        default: "en_GB",
        description: "Language used for generated documents and notices.",
        required: true,
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "OTP By Default",
        name: 'otpByDefault',
        type: 'boolean',
        default: false,
        description: "Apply OTP by default to participants that do not state their own setting.",
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "Send WA URL By Default",
        name: 'sendWaUrlByDefault',
        type: 'boolean',
        default: false,
        description: "Deliver over WhatsApp by default for participants that do not state their own setting.",
        displayOptions: { show: { operation: ['notification_request_create'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_request_send'] } },
      },
      {
        displayName: "Notification Request ID",
        name: 'notificationRequestId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_request_send'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_request_status'] } },
      },
      {
        displayName: "Notification Request ID",
        name: 'notificationRequestId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_request_status'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "Notification Request ID",
        name: 'notificationRequestId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "First Name",
        name: 'firstName',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "Last Name",
        name: 'lastName',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "Email",
        name: 'email',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "Phone Number",
        name: 'phoneNumber',
        type: 'string',
        default: "",
        description: "Phone number. REQUIRED when the signature request uses signatureType ADVANCED (set in the Create Signature Request step); optional otherwise.",
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "Phone Prefix",
        name: 'phonePrefix',
        type: 'string',
        default: "",
        description: "International dialling prefix for the phone (e.g. 34 for Spain). REQUIRED whenever a phone is used — OTP or WhatsApp delivery, and ADVANCED signatures.",
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "OTP Required",
        name: 'otpRequired',
        type: 'boolean',
        default: false,
        description: "Require an OTP code to open/sign. REQUIRED (true) for signature types that authenticate the signatory by phone, e.g. ADVANCED — the signatory phone must then also be supplied.",
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "Send WA URL",
        name: 'sendWaUrl',
        type: 'boolean',
        default: false,
        description: "Deliver the access URL over WhatsApp. Needs the signatory phone (with phonePrefix) to be supplied.",
        displayOptions: { show: { operation: ['notification_receiver_add'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_certificate_get'] } },
      },
      {
        displayName: "Notification Request ID",
        name: 'notificationRequestId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_certificate_get'] } },
      },
      {
        displayName: "Receiver ID",
        name: 'receiverId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['notification_certificate_get'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        displayOptions: { show: { operation: ['notification_certificate_get'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "English (UK)", value: "en_GB" },
          { name: "Spanish (Spain)", value: "es_ES" },
        ],
        default: "en_GB",
        description: "Language used for generated documents and notices.",
        required: true,
        displayOptions: { show: { operation: ['notification_certificate_get'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        displayOptions: { show: { operation: ['case_file_create'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['case_file_create'] } },
      },
      {
        displayName: "Item Description",
        name: 'description',
        type: 'string',
        default: "",
        description: "Short plain-text description (e.g. \"My case file\"). Required by the API.",
        required: true,
        displayOptions: { show: { operation: ['case_file_create'] } },
      },
      {
        displayName: "Use Case ID",
        name: 'useCaseId',
        type: 'string',
        default: "063a016a-1d62-4b7b-a24f-7cf4d1d289bf",
        description: "UUID of the use case. Default is the general GoCertius use case (063a016a-1d62-4b7b-a24f-7cf4d1d289bf). Change only if you need a specific use case.",
        required: true,
        displayOptions: { show: { operation: ['case_file_create'] } },
      },
      {
        displayName: "User ID",
        name: 'userId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['case_file_list'] } },
      },
      {
        displayName: "Filter",
        name: 'filter',
        type: 'json',
        default: {},
        displayOptions: { show: { operation: ['case_file_list'] } },
      },
      {
        displayName: "Order",
        name: 'order',
        type: 'json',
        default: {},
        description: "Sort direction / ordering for the results.",
        displayOptions: { show: { operation: ['case_file_list'] } },
      },
      {
        displayName: "Page",
        name: 'page',
        type: 'json',
        default: {},
        description: "Zero-based page number for paginated results (e.g. 0 for the first page).",
        displayOptions: { show: { operation: ['case_file_list'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['case_file_get'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "Title",
        name: 'title',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "Service Title",
        name: 'serviceTitle',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "Service Description",
        name: 'serviceDescription',
        type: 'string',
        default: "",
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "Service",
        name: 'service',
        type: 'options',
        options: [
          { name: "Telegram", value: "Telegram" },
        ],
        default: "Telegram",
        required: true,
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "English (UK)", value: "en_GB" },
          { name: "Spanish (Spain)", value: "es_ES" },
        ],
        default: "en_GB",
        description: "Language used for generated documents and notices.",
        required: true,
        displayOptions: { show: { operation: ['chat_create'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_get'] } },
      },
      {
        displayName: "Chat ID",
        name: 'chatId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_get'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_invitation_url'] } },
      },
      {
        displayName: "Chat ID",
        name: 'chatId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_invitation_url'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "Chat ID",
        name: 'chatId',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "Name",
        name: 'name',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "Language",
        name: 'language',
        type: 'options',
        options: [
          { name: "English (UK)", value: "en_GB" },
          { name: "Spanish (Spain)", value: "es_ES" },
        ],
        default: "en_GB",
        description: "Language used for generated documents and notices.",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "Chat Messages From",
        name: 'chatMessagesFrom',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "Chat Messages To",
        name: 'chatMessagesTo',
        type: 'string',
        default: "",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_create'] } },
      },
      {
        displayName: "Case File ID",
        name: 'caseFileId',
        type: 'string',
        default: "",
        description: "UUID of the case file that owns the chat",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_get'] } },
      },
      {
        displayName: "Chat ID",
        name: 'chatId',
        type: 'string',
        default: "",
        description: "UUID of the chat",
        required: true,
        displayOptions: { show: { operation: ['chat_certificate_get'] } },
      },
      {
        displayName: "ID",
        name: 'id',
        type: 'string',
        default: "",
        description: "UUID v4 identifier. Leave empty — the node generates it automatically.",
        displayOptions: { show: { operation: ['chat_certificate_get'] } },
      },
      {
        displayName: 'Additional Fields',
        name: 'additionalFields',
        type: 'collection',
        placeholder: 'Add Field',
        default: {},
        displayOptions: { show: { operation: ['dossier_update'] } },
        options: [
          {
            displayName: "Validity From",
            name: 'validityFrom',
            type: 'string',
            description: "ISO 8601 datetime (e.g. 2026-01-01T00:00:00.000Z). Leave empty — defaults to now.",
            default: "",
          },
          {
            displayName: "Validity To",
            name: 'validityTo',
            type: 'string',
            description: "ISO 8601 datetime. Leave empty — defaults to 1 year from now.",
            default: "",
          },
        ],
      },
      {
        displayName: 'Additional Fields',
        name: 'additionalFields',
        type: 'collection',
        placeholder: 'Add Field',
        default: {},
        displayOptions: { show: { operation: ['notification_document_add'] } },
        options: [
          {
            displayName: "File Size",
            name: 'fileSize',
            type: 'number',
            default: 0,
          },
        ],
      },
      {
        displayName: 'Additional Fields',
        name: 'additionalFields',
        type: 'collection',
        placeholder: 'Add Field',
        default: {},
        displayOptions: { show: { operation: ['case_file_create'] } },
        options: [
          {
            displayName: "Reference",
            name: 'reference',
            type: 'string',
            description: "Optional user-defined reference code (max 32 chars, e.g. \"EXP-2026-001\"). Do not use a UUID.",
            default: "",
          },
        ],
      },
    ],
  };

  async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
    const items = this.getInputData();
    const out: INodeExecutionData[] = [];
    const creds = await this.getCredentials('gocertiusApi');
    const baseUrl = String(creds.baseUrl ?? '').replace(/\/$/, '');

    // --- Obtain Bearer token (once per execute call) ---
    const tokenParams = new URLSearchParams({
      grant_type: 'client_credentials',
      client_id: String(creds.mcpSvcClientId ?? ''),
      client_secret: String(creds.mcpSvcClientSecret ?? ''),
    });
    const mcpSvcScope = String(creds.mcpSvcScope ?? '');
    if (mcpSvcScope) tokenParams.set('scope', mcpSvcScope);
    const tokenRes = await fetch(String(creds.mcpSvcTokenUrl ?? ''), {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: tokenParams.toString(),
    });
    if (!tokenRes.ok) {
      const tokenErr = await tokenRes.json().catch(() => ({ message: `HTTP ${tokenRes.status}` }));
      throw new NodeApiError(this.getNode(), tokenErr as never, { httpCode: String(tokenRes.status) });
    }
    const tokenBody = await tokenRes.json() as { access_token?: string };
    const bearer = tokenBody.access_token ?? '';

    // --- Per-item REST calls ---
    for (let i = 0; i < items.length; i++) {
      try {
        const operation = this.getNodeParameter('operation', i) as string;
        const meta = OPERATION_META[operation];
        if (!meta) {
          throw new NodeOperationError(this.getNode(), `Unknown operation: ${operation}`, { itemIndex: i });
        }
        if (meta.stub) {
          throw new NodeOperationError(
            this.getNode(),
            `Operation '${operation}' requires n8n self-hosted with the @g-digital/mcp-* package. It is not available in n8n Cloud via this connector.`,
            { itemIndex: i },
          );
        }

        // Replace URL path params {paramName} from input; remaining args → body/query.
        // Story 13.3 (FR53): for multi-manager products, insert the per-operation
        // manager base-path prefix between the credential's gateway-root base URL and
        // the operation path, so one credential serves every manager. Empty for
        // single-API products.
        let url = `${baseUrl}${OPERATION_BASE_PREFIX[operation] ?? ''}${meta.urlTemplate}`;
        const propsForOp = OPERATION_PROPERTY_NAMES[operation] ?? [];
        const body: IDataObject = {};
        // Story 13.2a tier 3: path-param values kept aside so a pre-flight guard can
        // build its own lookup URL after `url` has already been substituted.
        const pathParamValues: IDataObject = {};
        const isCreateOrAdd = operation.endsWith('_create') || operation.endsWith('_add');
        let generatedId: string | undefined;
        for (const propName of propsForOp) {
          let val = this.getNodeParameter(propName, i);
          // Auto-generate UUID for 'id' in _create/_add BEFORE the skip check
          if (propName === 'id' && isCreateOrAdd && (val === '' || val === null || val === undefined)) {
            val = randomUUID();
            generatedId = val as string;
          }
          if (val === '' || val === null || val === undefined) continue;
          if (typeof val === 'object' && !Array.isArray(val) && Object.keys(val as object).length === 0) continue;
          const placeholder = `{${propName}}`;
          const isPathParam = url.includes(placeholder);
          // Story 13.1 (FR51): omit an OPTIONAL body parameter the user left at its
          // declared default — n8n always returns the default from getNodeParameter,
          // so without this a boolean 'false', a number '0', or a defaulted string
          // (e.g. language) would be sent on every call and rejected by the API.
          // Required params and path params are never in OPTIONAL_DEFAULTS, so a real
          // missing-required gap still surfaces as an API error.
          if (!isPathParam) {
            const optDefaults = OPTIONAL_DEFAULTS[operation];
            if (
              optDefaults &&
              Object.prototype.hasOwnProperty.call(optDefaults, propName) &&
              JSON.stringify(val) === JSON.stringify(optDefaults[propName])
            ) {
              continue;
            }
          }
          if (isPathParam) {
            pathParamValues[propName] = val as IDataObject[string];
            url = url.replace(placeholder, encodeURIComponent(String(val)));
          } else {
            body[propName] = val;
          }
        }

        // Story 13.2b (FR52): "Additional Fields" collection — secondary parameters.
        // n8n returns ONLY the keys the user explicitly added, so an unset field is
        // simply absent: no default-comparison (Story 13.1) is needed here. Path
        // params never live in the collection, so these only ever reach body/query.
        const additionalFields = this.getNodeParameter('additionalFields', i, {}) as IDataObject;
        for (const [propName, val] of Object.entries(additionalFields)) {
          if (val === '' || val === null || val === undefined) continue;
          if (typeof val === 'object' && !Array.isArray(val) && Object.keys(val as object).length === 0) continue;
          body[propName] = val;
        }
        // Substitute any remaining {placeholder} patterns from credentials.
        // First try exact credential key names, then common API→credential aliases
        // (e.g. {email} in session_info maps to the 'email' credential field).
        const credAliases: Record<string, string> = { email: 'email' };
        for (const [credKey, credVal] of Object.entries(creds)) {
          const placeholder = `{${credKey}}`;
          if (url.includes(placeholder) && credVal) {
            url = url.replace(placeholder, encodeURIComponent(String(credVal)));
          }
        }
        for (const [alias, credKey] of Object.entries(credAliases)) {
          const placeholder = `{${alias}}`;
          if (url.includes(placeholder) && creds[credKey]) {
            url = url.replace(placeholder, encodeURIComponent(String(creds[credKey])));
          }
        }

        // --- Smart defaults for remaining body fields ---
        // validityFrom: default to now (ISO 8601)
        if ('validityFrom' in body && (body.validityFrom === '' || body.validityFrom === null || body.validityFrom === undefined)) {
          body.validityFrom = new Date().toISOString();
        }
        // validityTo: default to 1 year from now
        if ('validityTo' in body && (body.validityTo === '' || body.validityTo === null || body.validityTo === undefined)) {
          const oneYearLater = new Date();
          oneYearLater.setFullYear(oneYearLater.getFullYear() + 1);
          body.validityTo = oneYearLater.toISOString();
        }

        // --- Story 13.2a tier 3 (FR52): pre-flight guards ---
        // Some parameters are mandatory only in a configuration this node cannot see: the
        // driver was set on a DIFFERENT operation (a previous node), so n8n's displayOptions
        // cannot express it and the API's rejection is opaque. When such a field is left
        // empty we resolve the driver from the server once and explain the problem instead.
        // Zero cost when the user filled the field in — only empty ones trigger a lookup.
        // Best-effort by design: any lookup failure falls through to the real API call
        // rather than inventing a blocker.
        const guards = (PREFLIGHT_GUARDS[operation] ?? []).filter((g) => body[g.field] === undefined);
        if (guards.length > 0) {
          const lookupCache = new Map<string, IDataObject>();
          for (const guard of guards) {
            let lookupUrl = `${baseUrl}${OPERATION_BASE_PREFIX[operation] ?? ''}${guard.lookupUrl}`;
            for (const [k, v] of Object.entries(pathParamValues)) {
              lookupUrl = lookupUrl.replace(`{${k}}`, encodeURIComponent(String(v)));
            }
            if (lookupUrl.includes('{')) continue; // a path param wasn't supplied — can't guard
            let state = lookupCache.get(lookupUrl);
            if (!state) {
              try {
                const lookupRes = await fetch(lookupUrl, { headers: { Authorization: `Bearer ${bearer}` } });
                if (!lookupRes.ok) continue;
                state = await lookupRes.json().catch(() => ({})) as IDataObject;
              } catch { continue; }
              lookupCache.set(lookupUrl, state);
            }
            let scope: IDataObject | undefined = state;
            if (guard.arrayPath && guard.matchParam) {
              const arr = state[guard.arrayPath];
              const wanted = String(pathParamValues[guard.matchParam] ?? '');
              scope = Array.isArray(arr)
                ? (arr as IDataObject[]).find((entry) => String(entry.id) === wanted)
                : undefined;
            }
            const driverVal = scope ? scope[guard.driver] : undefined;
            if (driverVal === undefined || driverVal === null) continue;
            const conditionHolds = guard.equals !== undefined
              ? String(driverVal) === guard.equals
              : new RegExp(guard.matchesRe as string, 'i').test(String(driverVal));
            if (conditionHolds) {
              throw new NodeOperationError(this.getNode(), guard.message, { itemIndex: i });
            }
          }
        }

        const isBodyless = meta.method === 'GET' || meta.method === 'DELETE';
        if (isBodyless && Object.keys(body).length > 0) {
          const pairs: Array<[string, string]> = [];
          if (QUERY_PARAM_STYLE === 'flat') {
            // Story 13.6: the API's search endpoints expect FLAT query params
            // (`?status=OPEN&size=20`) and ignore bracketed ones. A top-level object
            // param (e.g. `filter`) is spread so its fields become the query params.
            const pushVal = (key: string, v: unknown): void => {
              if (v === null || v === undefined || v === '') return;
              if (Array.isArray(v)) { for (const item of v) pairs.push([key, String(item)]); }
              else if (typeof v === 'object') { for (const [k2, v2] of Object.entries(v as IDataObject)) pushVal(`${key}[${k2}]`, v2); }
              else pairs.push([key, String(v)]);
            };
            for (const [k, v] of Object.entries(body)) {
              if (v !== null && typeof v === 'object' && !Array.isArray(v)) {
                // Spread the wrapper object (filter) into flat params.
                for (const [k2, v2] of Object.entries(v as IDataObject)) pushVal(k2, v2);
              } else {
                pushVal(k, v);
              }
            }
          } else {
            // 'bracket' (default): qs/NestJS-style nested notation, matching hey-api:
            // { filter: { ownerId: 'uuid' }, page: { number: 1 } } → filter[ownerId]=uuid&page[number]=1
            const flattenQs = (obj: IDataObject, prefix = ''): Array<[string, string]> => {
              const out: Array<[string, string]> = [];
              for (const [k, v] of Object.entries(obj)) {
                if (v === null || v === undefined || v === '') continue;
                const key = prefix ? `${prefix}[${k}]` : k;
                if (typeof v === 'object' && !Array.isArray(v)) {
                  if (Object.keys(v as object).length === 0) continue;
                  out.push(...flattenQs(v as IDataObject, key));
                } else if (Array.isArray(v)) {
                  for (const item of v) out.push([`${key}[]`, String(item)]);
                } else {
                  out.push([key, String(v)]);
                }
              }
              return out;
            };
            pairs.push(...flattenQs(body));
          }
          if (pairs.length > 0) {
            url = `${url}?${new URLSearchParams(pairs).toString()}`;
          }
        }

        const apiRes = await fetch(url, {
          method: meta.method,
          headers: {
            Authorization: `Bearer ${bearer}`,
            ...(isBodyless ? {} : { 'Content-Type': 'application/json' }),
          },
          ...(isBodyless ? {} : { body: JSON.stringify(body) }),
        });

        if (!apiRes.ok) {
          const errBody = await apiRes.json().catch(() => ({ message: `${operation} failed: HTTP ${apiRes.status}` }));
          throw new NodeApiError(this.getNode(), errBody as never, {
            httpCode: String(apiRes.status),
            itemIndex: i,
          });
        }

        // 204 No Content or empty body → return empty object
        const contentLength = apiRes.headers.get('content-length');
        const hasBody = apiRes.status !== 204 && contentLength !== '0';
        const json: IDataObject = hasBody
          ? await apiRes.json().catch(() => ({})) as IDataObject
          : {};
        // Inject auto-generated id with semantic field name so downstream nodes
        // can reference it directly (e.g. $json.caseFileId, $json.chatId).
        if (generatedId) {
          const semanticId = AUTO_ID_OUTPUT_FIELD[operation];
          if (semanticId && !json[semanticId]) json[semanticId] = generatedId;
          if (!json['id']) json['id'] = generatedId;
        }
        // chat_certificate_get: when CERTIFIED, fetch documentUrl via a second call
        if (operation === 'chat_certificate_get' && (json as IDataObject).status === 'CERTIFIED' && !json['documentUrl']) {
          try {
            const docUrlRes = await fetch(`${url}/document-url`, {
              headers: { Authorization: `Bearer ${bearer}` },
            });
            if (docUrlRes.ok) {
              const docData = await docUrlRes.json().catch(() => ({})) as IDataObject;
              if (docData.documentUrl) (json as IDataObject).documentUrl = docData.documentUrl;
            }
          } catch { /* non-fatal */ }
        }
        // session_info: inject userId decoded from JWT sub claim so callers
        // don't need a separate step to obtain the userId required by most operations.
        if (operation === 'session_info' && bearer) {
          try {
            const parts = bearer.split('.');
            if (parts.length === 3) {
              const pad = (s: string) => s + '='.repeat((4 - s.length % 4) % 4);
              const payload = JSON.parse(Buffer.from(pad(parts[1] ?? ''), 'base64').toString('utf8')) as IDataObject;
              const sub = payload.sub ?? payload.userId ?? payload.user_id;
              if (sub && !(json as IDataObject).userId) {
                (json as IDataObject).userId = sub;
              }
            }
          } catch { /* ignore decode errors */ }
        }
        out.push({ json: json as IDataObject });
      } catch (error) {
        if (this.continueOnFail()) {
          out.push({ json: this.getInputData(i)[0].json, error: error as NodeOperationError });
          continue;
        }
        throw error;
      }
    }

    return [out];
  }
}

// Semantic output field name for auto-generated 'id' values.
// When a _create/_add operation auto-generates a UUID for 'id', it is also
// injected into the output under this field name so downstream nodes can
// reference it with its domain-specific name (e.g. $json.caseFileId).
// Generated per-node from the operations this MCP actually exposes — entries
// for absent operations (e.g. chat_* on a node without chat) are never emitted.
const AUTO_ID_OUTPUT_FIELD: Record<string, string> = {
  'evidence_create': 'evidenceId',
  'evidence_group_create': 'evidenceGroupId',
  'dossier_create': 'dossierId',
  'dossier_group_certify': 'dossierId',
  'notification_document_add': 'documentId',
  'notification_request_create': 'notificationRequestId',
  'notification_receiver_add': 'receiverId',
  'case_file_create': 'caseFileId',
  'chat_create': 'chatId',
  'chat_certificate_create': 'certificateId',
};

// HTTP metadata per operation — method + URL template.
// 'stub: true' means the tool has no REST annotation and requires self-hosted n8n.
const OPERATION_META: Record<string, { method: string; urlTemplate: string; stub?: true }> = {
  'evidence_create': { method: 'POST', urlTemplate: "/evidences" },
  'evidence_list': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences" },
  'evidence_seal': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/evidence-groups/{id}/close" },
  'evidence_get': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences/{id}" },
  'evidence_group_create': { method: 'POST', urlTemplate: "/evidence-groups" },
  'evidence_group_list': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/evidence-groups" },
  'dossier_create': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/dossiers" },
  'dossier_update': { method: 'PUT', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}" },
  'dossier_certify': { method: 'PUT', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/certify" },
  'dossier_list': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers" },
  'dossier_get': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}" },
  'dossier_template_list': { method: 'GET', urlTemplate: "/dossier-templates" },
  'dossier_preview': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/report-preview" },
  'dossier_document_url': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/document-url" },
  'dossier_package_url': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/package-url" },
  'dossier_visibility': { method: 'PUT', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/visibility" },
  'dossier_delete': { method: 'DELETE', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}" },
  'dossier_group_certify': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/dossier-express" },
  'dossier_evidence_link': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/case-files-to-link/{caseFileToLinkId}/link-evidences" },
  'dossier_evidence_list_to_link': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/case-files-to-link/{caseFileToLinkId}/evidences-to-link" },
  'dossier_evidence_list': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/evidence-groups/{dossierEvidenceGroupId}/evidences" },
  'dossier_evidence_get': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/evidence-groups/{dossierEvidenceGroupId}/evidences/{dossierEvidenceId}" },
  'dossier_evidence_delete': { method: 'DELETE', urlTemplate: "/case-files/{caseFileId}/dossiers/{dossierId}/evidence-groups/{dossierEvidenceGroupId}/evidences/{dossierEvidenceId}" },
  'notification_document_add': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/notification-requests/{notificationRequestId}/documents" },
  'notification_request_create': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/notification-requests" },
  'notification_request_send': { method: 'PUT', urlTemplate: "/case-files/{caseFileId}/notification-requests/{notificationRequestId}/send" },
  'notification_request_status': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/notification-requests/{notificationRequestId}" },
  'notification_receiver_add': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers" },
  'notification_certificate_get': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers/{receiverId}/certificates" },
  'case_file_create': { method: 'POST', urlTemplate: "/case-files" },
  'case_file_list': { method: 'GET', urlTemplate: "/users/{userId}/case-files" },
  'case_file_get': { method: 'GET', urlTemplate: "/case-files/{caseFileId}" },
  'chat_create': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/chats" },
  'chat_get': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/chats/{chatId}" },
  'chat_invitation_url': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/chats/{chatId}/invitation-url" },
  'chat_certificate_create': { method: 'POST', urlTemplate: "/case-files/{caseFileId}/chats/{chatId}/certificate-express" },
  'chat_certificate_get': { method: 'GET', urlTemplate: "/case-files/{caseFileId}/chats/{chatId}/certificates/{id}" },
  'session_login': { method: 'POST', urlTemplate: "/session" },
  'session_info': { method: 'GET', urlTemplate: "/session-info/{email}" },
};

// Per-operation input property names for argument gathering.
const OPERATION_PROPERTY_NAMES: Record<string, readonly string[]> = {
  'evidence_create': ['caseFileId', 'evidenceGroupId', 'id', 'title', 'fileName', 'hash', 'custodyType', 'fileUrl'],
  'evidence_list': ['caseFileId', 'evidenceGroupId', 'filter', 'order', 'page'],
  'evidence_seal': ['caseFileId', 'id', 'evidencesCount', 'webUrl'],
  'evidence_get': ['caseFileId', 'evidenceGroupId', 'id'],
  'evidence_group_create': ['id', 'evidenceType', 'name', 'description', 'caseFileId'],
  'evidence_group_list': ['caseFileId', 'filter', 'order', 'page'],
  'dossier_create': ['caseFileId', 'dossierTemplateId', 'purpose', 'id', 'modelId', 'name', 'language', 'filledFields', 'validityFrom', 'validityTo', 'accessToken'],
  'dossier_update': ['caseFileId', 'dossierId', 'dossierTemplateId', 'purpose', 'modelId', 'name', 'language', 'filledFields', 'accessToken'],
  'dossier_certify': ['caseFileId', 'dossierId'],
  'dossier_list': ['caseFileId', 'filter', 'order', 'page'],
  'dossier_get': ['caseFileId', 'dossierId'],
  'dossier_template_list': ['page'],
  'dossier_preview': ['caseFileId', 'dossierId'],
  'dossier_document_url': ['caseFileId', 'dossierId'],
  'dossier_package_url': ['caseFileId', 'dossierId'],
  'dossier_visibility': ['caseFileId', 'dossierId', 'visibility'],
  'dossier_delete': ['caseFileId', 'dossierId'],
  'dossier_group_certify': ['caseFileId', 'evidenceGroupId', 'id', 'modelId', 'evidenceIds', 'name', 'language'],
  'dossier_evidence_link': ['caseFileId', 'dossierId', 'caseFileToLinkId', 'ids'],
  'dossier_evidence_list_to_link': ['caseFileId', 'dossierId', 'caseFileToLinkId', 'filter', 'order', 'page'],
  'dossier_evidence_list': ['caseFileId', 'dossierId', 'dossierEvidenceGroupId', 'filter', 'order', 'page'],
  'dossier_evidence_get': ['dossierEvidenceGroupId', 'dossierId', 'caseFileId', 'dossierEvidenceId'],
  'dossier_evidence_delete': ['dossierEvidenceGroupId', 'dossierId', 'caseFileId', 'dossierEvidenceId'],
  'notification_document_add': ['caseFileId', 'notificationRequestId', 'id', 'fileName', 'hash'],
  'notification_request_create': ['caseFileId', 'id', 'type', 'subject', 'content', 'language', 'otpByDefault', 'sendWaUrlByDefault'],
  'notification_request_send': ['caseFileId', 'notificationRequestId'],
  'notification_request_status': ['caseFileId', 'notificationRequestId'],
  'notification_receiver_add': ['caseFileId', 'notificationRequestId', 'id', 'firstName', 'lastName', 'email', 'phoneNumber', 'phonePrefix', 'otpRequired', 'sendWaUrl'],
  'notification_certificate_get': ['caseFileId', 'notificationRequestId', 'receiverId', 'id', 'language'],
  'case_file_create': ['id', 'name', 'description', 'useCaseId'],
  'case_file_list': ['userId', 'filter', 'order', 'page'],
  'case_file_get': ['caseFileId'],
  'chat_create': ['caseFileId', 'id', 'title', 'serviceTitle', 'serviceDescription', 'service', 'language'],
  'chat_get': ['caseFileId', 'chatId'],
  'chat_invitation_url': ['caseFileId', 'chatId'],
  'chat_certificate_create': ['caseFileId', 'chatId', 'id', 'name', 'language', 'chatMessagesFrom', 'chatMessagesTo'],
  'chat_certificate_get': ['caseFileId', 'chatId', 'id'],
  'session_login': [],
  'session_info': [],
 };

// Per-operation default values for OPTIONAL body parameters (Story 13.1 / FR51).
// A value equal to its default is treated as "unset" and omitted from the request.
// Required params and path params are never listed here, so a genuinely missing
// required field still surfaces as an API error.
const OPTIONAL_DEFAULTS: Record<string, Record<string, unknown>> = {
  'notification_request_create': { 'type': "NO_RESPONSE", 'otpByDefault': false, 'sendWaUrlByDefault': false, },
  'notification_receiver_add': { 'otpRequired': false, 'sendWaUrl': false, },
 };

// Per-operation manager base-path prefix (Story 13.3 / FR53). Non-empty only for
// multi-manager products; inserted between the credential base URL and the op path
// so a single credential (gateway root) serves every manager.
const OPERATION_BASE_PREFIX: Record<string, string> = {
 };

// Per-operation pre-flight guards (Story 13.2a tier 3 / FR52). Each entry says "this
// field is mandatory when the server reports <driver> is X" — a condition set on a
// DIFFERENT operation, which n8n's displayOptions cannot see. execute() resolves it from
// the server ONLY when the field was left empty, and never blocks on a failed lookup.
interface PreflightGuard {
  field: string;
  lookupUrl: string;
  arrayPath?: string;
  matchParam?: string;
  driver: string;
  equals?: string;
  matchesRe?: string;
  message: string;
}
const PREFLIGHT_GUARDS: Record<string, readonly PreflightGuard[]> = {
 };

// GET query-parameter serialization style (Story 13.3/13.6). 'flat' spreads a
// top-level object (e.g. filter) into key=val params; 'bracket' uses qs-style
// filter[key]=val. Empty template value → default 'bracket'.
const QUERY_PARAM_STYLE: 'bracket' | 'flat' = ('' as string) === 'flat' ? 'flat' : 'bracket';
