// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type CreateOpenIdSessionControllerRunData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openid/session';
};

export type CreateOpenIdSessionControllerRunResponses = {
    201: {
        jwt: string;
    };
};

export type CreateOpenIdSessionControllerRunResponse = CreateOpenIdSessionControllerRunResponses[keyof CreateOpenIdSessionControllerRunResponses];

export type CreateOpenIdSessionWithLegalTextsControllerRunData = {
    body: {
        legalTextLanguage: 'en_GB' | 'es_ES';
        acceptServiceTermId?: string;
        acceptPrivacyPolicyId?: string;
    };
    path?: never;
    query?: never;
    url: '/openid/session-with-legal-texts';
};

export type CreateOpenIdSessionWithLegalTextsControllerRunResponses = {
    201: {
        jwt: string;
    };
};

export type CreateOpenIdSessionWithLegalTextsControllerRunResponse = CreateOpenIdSessionWithLegalTextsControllerRunResponses[keyof CreateOpenIdSessionWithLegalTextsControllerRunResponses];

export type CreatePasswordTokenControllerRunData = {
    body: {
        email: string;
        recoveredFrom: 'Web' | 'AppPro' | 'AppLite';
    };
    path?: never;
    query?: never;
    url: '/recover-password';
};

export type CreatePasswordTokenControllerRunResponses = {
    201: unknown;
};

export type DeleteSessionControllerRunData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/session';
};

export type DeleteSessionControllerRunResponses = {
    204: void;
};

export type DeleteSessionControllerRunResponse = DeleteSessionControllerRunResponses[keyof DeleteSessionControllerRunResponses];

export type CreateSessionControllerRunData = {
    body?: unknown;
    path?: never;
    query?: never;
    url: '/session';
};

export type CreateSessionControllerRunResponses = {
    201: {
        jwt: string;
    };
};

export type CreateSessionControllerRunResponse = CreateSessionControllerRunResponses[keyof CreateSessionControllerRunResponses];

export type CreateSessionWithLegalTextsControllerRunData = {
    body: {
        email: string;
        password: string;
        legalTextLanguage: 'en_GB' | 'es_ES';
        acceptServiceTermId?: string;
        acceptPrivacyPolicyId?: string;
    };
    path?: never;
    query?: never;
    url: '/session-with-legal-texts';
};

export type CreateSessionWithLegalTextsControllerRunResponses = {
    201: {
        jwt: string;
    };
};

export type CreateSessionWithLegalTextsControllerRunResponse = CreateSessionWithLegalTextsControllerRunResponses[keyof CreateSessionWithLegalTextsControllerRunResponses];

export type ShowOpenIdUserInfoControllerRunData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openid/user-info';
};

export type ShowOpenIdUserInfoControllerRunResponses = {
    200: {
        firstName: string;
        lastName: string;
        companyId: string;
        email: string;
    };
};

export type ShowOpenIdUserInfoControllerRunResponse = ShowOpenIdUserInfoControllerRunResponses[keyof ShowOpenIdUserInfoControllerRunResponses];

export type ShowSessionInfoControllerRunData = {
    body?: never;
    path: {
        email: string;
    };
    query?: never;
    url: '/session-info/{email}';
};

export type ShowSessionInfoControllerRunResponses = {
    200: {
        type: 'Password' | 'OpenId';
        issuer?: string;
        clientId?: string;
        scope?: Array<string>;
    };
};

export type ShowSessionInfoControllerRunResponse = ShowSessionInfoControllerRunResponses[keyof ShowSessionInfoControllerRunResponses];

export type UpdatePasswordWithPasswordTokenControllerRunData = {
    body: {
        password: string;
        passwordConfirmation: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/recover-password/{id}';
};

export type UpdatePasswordWithPasswordTokenControllerRunResponses = {
    204: void;
};

export type UpdatePasswordWithPasswordTokenControllerRunResponse = UpdatePasswordWithPasswordTokenControllerRunResponses[keyof UpdatePasswordWithPasswordTokenControllerRunResponses];

export type CreateCaseFileControllerRunData = {
    body: {
        id: string;
        name: string;
        reference?: string;
        description?: string;
        useCaseId: string;
    };
    path?: never;
    query?: never;
    url: '/case-files';
};

export type CreateCaseFileControllerRunResponses = {
    201: unknown;
};

export type CreateCaseFilesSharingControllerRunData = {
    body: {
        userIds: Array<string>;
        role: 'COLLABORATOR' | 'EDITOR' | 'MANAGER';
    };
    path: {
        caseFileId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/sharing';
};

export type CreateCaseFilesSharingControllerRunResponses = {
    201: unknown;
};

export type DeleteCaseFilesSharingControllerRunData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/sharing/{id}';
};

export type DeleteCaseFilesSharingControllerRunResponses = {
    204: void;
};

export type DeleteCaseFilesSharingControllerRunResponse = DeleteCaseFilesSharingControllerRunResponses[keyof DeleteCaseFilesSharingControllerRunResponses];

export type UpdateCaseFilesSharingControllerRunData = {
    body: {
        role?: 'COLLABORATOR' | 'EDITOR' | 'MANAGER';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/sharing/{id}';
};

export type UpdateCaseFilesSharingControllerRunResponses = {
    204: void;
};

export type UpdateCaseFilesSharingControllerRunResponse = UpdateCaseFilesSharingControllerRunResponses[keyof UpdateCaseFilesSharingControllerRunResponses];

export type ListCaseFilesControllerRunData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: {
        filter?: {
            search?: string;
            status?: 'OPEN' | 'CLOSED';
            statuses?: Array<'OPEN' | 'CLOSED'>;
            createdById?: string;
            ownerId?: string;
            ownerOrSharedWithId?: string;
            useCaseId?: string;
            id?: string;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/users/{userId}/case-files';
};

export type ListCaseFilesControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            code: string;
            name: string;
            useCaseId: string;
            createdAt: string;
            status: string;
            owner: {
                id: string;
                firstName: string;
                lastName: string;
            };
            createdBy?: {
                id: string;
                firstName: string;
                lastName: string;
            };
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListCaseFilesControllerRunResponse = ListCaseFilesControllerRunResponses[keyof ListCaseFilesControllerRunResponses];

export type ListCaseFilesSharingControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
    };
    query?: {
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/sharing-with-users';
};

export type ListCaseFilesSharingControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            caseFileId: string;
            userId: string;
            role: string;
            user: {
                role: string;
                firstName: string;
                lastName: string;
                email: string;
            };
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListCaseFilesSharingControllerRunResponse = ListCaseFilesSharingControllerRunResponses[keyof ListCaseFilesSharingControllerRunResponses];

export type ShowCaseFileControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}';
};

export type ShowCaseFileControllerRunResponses = {
    200: {
        id: string;
        code: string;
        name: string;
        useCaseId: string;
        createdAt: string;
        status: string;
        owner: {
            id: string;
            firstName: string;
            lastName: string;
        };
        createdBy?: {
            id: string;
            firstName: string;
            lastName: string;
        };
    };
};

export type ShowCaseFileControllerRunResponse = ShowCaseFileControllerRunResponses[keyof ShowCaseFileControllerRunResponses];

export type UpdateCaseFileControllerRunData = {
    body: {
        status?: 'OPEN' | 'CLOSED';
        name?: string;
        reference?: string;
        description?: string;
    };
    path: {
        caseFileId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}';
};

export type UpdateCaseFileControllerRunResponses = {
    204: void;
};

export type UpdateCaseFileControllerRunResponse = UpdateCaseFileControllerRunResponses[keyof UpdateCaseFileControllerRunResponses];

export type ShowCaseFilesSharingControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/my-sharing-role';
};

export type ShowCaseFilesSharingControllerRunResponses = {
    200: {
        id: string;
        caseFileId: string;
        userId: string;
        role: string;
    };
};

export type ShowCaseFilesSharingControllerRunResponse = ShowCaseFilesSharingControllerRunResponses[keyof ShowCaseFilesSharingControllerRunResponses];

export type CertifyChatCertificateControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        chatId: string;
        chatCertificateId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/chats/{chatId}/certificates/{chatCertificateId}/certify';
};

export type CertifyChatCertificateControllerRunResponses = {
    202: unknown;
};

export type ListChatCertificatesControllerRunData = {
    body?: never;
    path: {
        chatId: string;
    };
    query?: {
        filter?: {
            search?: string;
            status?: 'CERTIFYING' | 'DRAFT' | 'CERTIFIED';
            statuses?: Array<'CERTIFYING' | 'DRAFT' | 'CERTIFIED'>;
            createdFrom?: string;
            createdUntil?: string;
            id?: string;
        };
        order?: {
            title?: 'ASC' | 'DESC';
            createdAt?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/chats/{chatId}/certificates';
};

export type ListChatCertificatesControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            chatId: string;
            code: string;
            name: string;
            status: 'CERTIFYING' | 'DRAFT' | 'CERTIFIED';
            createdAt: string;
            certifiedAt?: string;
            chatMessagesFrom: string;
            chatMessagesTo: string;
            visibility: 'ACCESSIBLE' | 'PENDING_RECALL' | 'RECALLED';
            owner: {
                id: string;
                firstName: string;
                lastName: string;
            };
            createdBy?: {
                id: string;
                firstName: string;
                lastName: string;
            };
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListChatCertificatesControllerRunResponse = ListChatCertificatesControllerRunResponses[keyof ListChatCertificatesControllerRunResponses];

export type CreateChatCertificateControllerRunData = {
    body: {
        id: string;
        modelId: string;
        name: string;
        language: 'en_GB' | 'es_ES';
        validityFrom: string;
        validityTo: string;
        chatMessagesFrom: string;
        chatMessagesTo: string;
    };
    path: {
        caseFileId: string;
        chatId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/chats/{chatId}/certificates';
};

export type CreateChatCertificateControllerRunResponses = {
    201: unknown;
};

export type CreateChatCertificateExpressControllerRunData = {
    body: {
        id: string;
        name: string;
        language: 'en_GB' | 'es_ES';
        chatMessagesFrom: string;
        chatMessagesTo: string;
    };
    path: {
        caseFileId: string;
        chatId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/chats/{chatId}/certificate-express';
};

export type CreateChatCertificateExpressControllerRunResponses = {
    201: unknown;
};

export type DeleteChatCertificateControllerRunData = {
    body?: never;
    path: {
        chatId: string;
        chatCertificateId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/chats/{chatId}/certificates/{chatCertificateId}';
};

export type DeleteChatCertificateControllerRunResponses = {
    204: void;
};

export type DeleteChatCertificateControllerRunResponse = DeleteChatCertificateControllerRunResponses[keyof DeleteChatCertificateControllerRunResponses];

export type UpdateChatCertificateControllerRunData = {
    body: {
        name?: string;
        language?: 'en_GB' | 'es_ES';
        validityFrom?: string;
        validityTo?: string;
        chatMessagesFrom?: string;
        chatMessagesTo?: string;
    };
    path: {
        caseFileId: string;
        chatId: string;
        chatCertificateId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/chats/{chatId}/certificates/{chatCertificateId}';
};

export type UpdateChatCertificateControllerRunResponses = {
    204: void;
};

export type UpdateChatCertificateControllerRunResponse = UpdateChatCertificateControllerRunResponses[keyof UpdateChatCertificateControllerRunResponses];

export type ListChatCertificateModelsControllerRunData = {
    body?: never;
    path?: never;
    query?: {
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/users/{userId}/chat-certificate-models';
};

export type ListChatCertificateModelsControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            index: number;
            translations: Array<{
                id: string;
                name: string;
                language: string;
                tipsDescription: string;
                tipsList: Array<string>;
                purposeDossier: string;
            }>;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListChatCertificateModelsControllerRunResponse = ListChatCertificateModelsControllerRunResponses[keyof ListChatCertificateModelsControllerRunResponses];

export type ListChatCertificateRecallRequestsControllerIndexData = {
    body?: never;
    path: {
        chatCertificateId: string;
    };
    query?: {
        filter?: {
            email?: string;
            resolved?: boolean;
            id?: string;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/chats/{chatId}/certificates/{chatCertificateId}/recall-requests';
};

export type ListChatCertificateRecallRequestsControllerIndexResponses = {
    200: {
        data?: Array<{
            id: string;
            chatCertificateId: string;
            firstName: string;
            lastName: string;
            phoneNumber?: string;
            email: string;
            reason: string;
            createdAt: string;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListChatCertificateRecallRequestsControllerIndexResponse = ListChatCertificateRecallRequestsControllerIndexResponses[keyof ListChatCertificateRecallRequestsControllerIndexResponses];

export type NotifyChatCertificateControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        chatId: string;
        chatCertificateId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/chats/{chatId}/certificates/{chatCertificateId}/notify';
};

export type NotifyChatCertificateControllerRunResponses = {
    202: unknown;
};

export type ShowChatCertificateControllerRunData = {
    body?: never;
    path: {
        chatId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/chats/{chatId}/certificates/{id}';
};

export type ShowChatCertificateControllerRunResponses = {
    200: {
        id: string;
        modelId: string;
        code: string;
        name: string;
        language: 'en_GB' | 'es_ES';
        status: 'CERTIFYING' | 'DRAFT' | 'CERTIFIED';
        visibility: 'ACCESSIBLE' | 'PENDING_RECALL' | 'RECALLED';
        chatId: string;
        createdAt: string;
        certifiedAt?: string;
        validityFrom: string;
        validityTo: string;
        chatMessagesFrom: string;
        chatMessagesTo: string;
        owner: {
            id: string;
            firstName: string;
            lastName: string;
        };
        createdBy?: {
            id: string;
            firstName: string;
            lastName: string;
        };
    };
};

export type ShowChatCertificateControllerRunResponse = ShowChatCertificateControllerRunResponses[keyof ShowChatCertificateControllerRunResponses];

export type ShowChatCertificateDocumentUrlControllerRunData = {
    body?: never;
    path: {
        chatId: string;
        chatCertificateId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/chats/{chatId}/certificates/{chatCertificateId}/document-url';
};

export type ShowChatCertificateDocumentUrlControllerRunResponses = {
    200: {
        documentUrl: string;
    };
};

export type ShowChatCertificateDocumentUrlControllerRunResponse = ShowChatCertificateDocumentUrlControllerRunResponses[keyof ShowChatCertificateDocumentUrlControllerRunResponses];

export type ShowChatCertificatePackageUrlControllerRunData = {
    body?: never;
    path: {
        chatId: string;
        chatCertificateId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/chats/{chatId}/certificates/{chatCertificateId}/package-url';
};

export type ShowChatCertificatePackageUrlControllerRunResponses = {
    200: {
        packageUrl: string;
    };
};

export type ShowChatCertificatePackageUrlControllerRunResponse = ShowChatCertificatePackageUrlControllerRunResponses[keyof ShowChatCertificatePackageUrlControllerRunResponses];

export type ShowChatCertificatePreviewControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        chatId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/chats/{chatId}/certificates/{id}/preview';
};

export type ShowChatCertificatePreviewControllerRunResponses = {
    200: {
        preview: string;
    };
};

export type ShowChatCertificatePreviewControllerRunResponse = ShowChatCertificatePreviewControllerRunResponses[keyof ShowChatCertificatePreviewControllerRunResponses];

export type UpdateChatCertificateVisibilityControllerRunData = {
    body: {
        visibility: 'ACCESSIBLE' | 'PENDING_RECALL' | 'RECALLED';
    };
    path: {
        chatId: string;
        chatCertificateId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/chats/{chatId}/certificates/{chatCertificateId}/visibility';
};

export type UpdateChatCertificateVisibilityControllerRunResponses = {
    204: void;
};

export type UpdateChatCertificateVisibilityControllerRunResponse = UpdateChatCertificateVisibilityControllerRunResponses[keyof UpdateChatCertificateVisibilityControllerRunResponses];

export type ListChatsByCaseFileControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
    };
    query?: {
        filter?: {
            search?: string;
            service?: 'Telegram';
            status?: 'creating' | 'active' | 'inactive';
            createdFrom?: string;
            createdUntil?: string;
            id?: string;
        };
        order?: {
            title?: 'ASC' | 'DESC';
            createdAt?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/chats';
};

export type ListChatsByCaseFileControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            caseFileId: string;
            code: string;
            status: 'creating' | 'active' | 'inactive';
            service: 'Telegram';
            title: string;
            createdAt: string;
            owner: {
                id: string;
                firstName: string;
                lastName: string;
            };
            createdBy?: {
                id: string;
                firstName: string;
                lastName: string;
            };
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListChatsByCaseFileControllerRunResponse = ListChatsByCaseFileControllerRunResponses[keyof ListChatsByCaseFileControllerRunResponses];

export type CreateChatControllerRunData = {
    body: {
        id: string;
        title: string;
        serviceTitle?: string;
        serviceDescription?: string;
        service: 'Telegram';
        language: 'en_GB' | 'es_ES';
    };
    path: {
        caseFileId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/chats';
};

export type CreateChatControllerRunResponses = {
    201: unknown;
};

export type ListChatMessagesControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        chatId: string;
    };
    query?: {
        filter?: {
            writtenFrom?: string;
            writtenTo?: string;
        };
        order?: {
            writtenAt?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/chats/{chatId}/messages';
};

export type ListChatMessagesControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            writtenBy: {
                id: string;
                userName?: string;
            };
            replyTo?: {
                id: string;
            };
            reactTo?: {
                id: string;
            };
            writtenAt: string;
            deleted: boolean;
            contentHistory: Array<{
                value?: {
                    [key: string]: unknown;
                };
                contentType: 'AudioOgg' | 'ChatCreated' | 'ChatDescriptionUpdated' | 'ChatDisabled' | 'ChatEnabled' | 'ChatTitleUpdated' | 'DeletedMessage' | 'Empty' | 'ImageJpeg' | 'MessageLocation' | 'MessagePoll' | 'MessagePollAnswer' | 'MessagePollStatus' | 'MessageReaction' | 'Text' | 'TextFormatted' | 'Unknown' | 'UserJoined' | 'UserRemoved';
                capturedAt: string;
                evidenceId: string;
                attachment?: {
                    name: string;
                    contentType: 'AudioOgg' | 'ChatCreated' | 'ChatDescriptionUpdated' | 'ChatDisabled' | 'ChatEnabled' | 'ChatTitleUpdated' | 'DeletedMessage' | 'Empty' | 'ImageJpeg' | 'MessageLocation' | 'MessagePoll' | 'MessagePollAnswer' | 'MessagePollStatus' | 'MessageReaction' | 'Text' | 'TextFormatted' | 'Unknown' | 'UserJoined' | 'UserRemoved';
                    evidenceId: string;
                };
            }>;
            reactions: Array<{
                emoji: string;
                participants: Array<{
                    userName: string;
                }>;
            }>;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListChatMessagesControllerRunResponse = ListChatMessagesControllerRunResponses[keyof ListChatMessagesControllerRunResponses];

export type ListChatParticipantsControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        chatId: string;
    };
    query?: {
        filter?: {
            id?: string;
        };
        order?: {
            [key: string]: unknown;
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/chats/{chatId}/participants';
};

export type ListChatParticipantsControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            userName?: string;
            firstName?: string;
            lastName?: string;
            participationHistory: Array<{
                isActive: boolean;
                joinedAt: string;
                invitedBy?: string;
            }>;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListChatParticipantsControllerRunResponse = ListChatParticipantsControllerRunResponses[keyof ListChatParticipantsControllerRunResponses];

export type ListChatsByUserControllerRunData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: {
        filter?: {
            search?: string;
            service?: 'Telegram';
            status?: 'creating' | 'active' | 'inactive';
            createdFrom?: string;
            createdUntil?: string;
            id?: string;
            caseFileIds?: Array<string>;
        };
        order?: {
            title?: 'ASC' | 'DESC';
            createdAt?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/users/{userId}/chats';
};

export type ListChatsByUserControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            caseFileId: string;
            code: string;
            status: 'creating' | 'active' | 'inactive';
            service: 'Telegram';
            title: string;
            createdAt: string;
            owner: {
                id: string;
                firstName: string;
                lastName: string;
            };
            createdBy?: {
                id: string;
                firstName: string;
                lastName: string;
            };
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListChatsByUserControllerRunResponse = ListChatsByUserControllerRunResponses[keyof ListChatsByUserControllerRunResponses];

export type ProcessChatEventsCallbackControllerRunData = {
    body: {
        chatId: string;
        eventName: string;
        userId?: string;
        title?: string;
        username?: string;
        phoneNumber?: string;
    };
    path?: never;
    query?: never;
    url: '/chat-events/callback';
};

export type ProcessChatEventsCallbackControllerRunResponses = {
    204: void;
};

export type ProcessChatEventsCallbackControllerRunResponse = ProcessChatEventsCallbackControllerRunResponses[keyof ProcessChatEventsCallbackControllerRunResponses];

export type ShowChatControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        chatId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/chats/{chatId}';
};

export type ShowChatControllerRunResponses = {
    200: {
        id: string;
        caseFileId: string;
        status: 'creating' | 'active' | 'inactive';
        title: string;
        code: string;
        service: 'Telegram';
        createdAt: string;
        registeredAt?: string;
        language: 'en_GB' | 'es_ES';
        serviceDescriptionHistory: Array<{
            value?: string;
            contentType: 'AudioOgg' | 'ChatCreated' | 'ChatDescriptionUpdated' | 'ChatDisabled' | 'ChatEnabled' | 'ChatTitleUpdated' | 'DeletedMessage' | 'Empty' | 'ImageJpeg' | 'MessageLocation' | 'MessagePoll' | 'MessagePollAnswer' | 'MessagePollStatus' | 'MessageReaction' | 'Text' | 'TextFormatted' | 'Unknown' | 'UserJoined' | 'UserRemoved';
            capturedAt: string;
        }>;
        serviceTitleHistory: Array<{
            value?: string;
            contentType: 'AudioOgg' | 'ChatCreated' | 'ChatDescriptionUpdated' | 'ChatDisabled' | 'ChatEnabled' | 'ChatTitleUpdated' | 'DeletedMessage' | 'Empty' | 'ImageJpeg' | 'MessageLocation' | 'MessagePoll' | 'MessagePollAnswer' | 'MessagePollStatus' | 'MessageReaction' | 'Text' | 'TextFormatted' | 'Unknown' | 'UserJoined' | 'UserRemoved';
            capturedAt: string;
        }>;
        owner: {
            id: string;
            firstName: string;
            lastName: string;
        };
        createdBy?: {
            id: string;
            firstName: string;
            lastName: string;
        };
        participantsCount: number;
    };
};

export type ShowChatControllerRunResponse = ShowChatControllerRunResponses[keyof ShowChatControllerRunResponses];

export type UpdateChatControllerRunData = {
    body: {
        title?: string;
        language?: 'en_GB' | 'es_ES';
    };
    path: {
        caseFileId: string;
        chatId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/chats/{chatId}';
};

export type UpdateChatControllerRunResponses = {
    200: unknown;
};

export type ShowChatInvitationUrlControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        chatId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/chats/{chatId}/invitation-url';
};

export type ShowChatInvitationUrlControllerRunResponses = {
    200: {
        invitationUrl: string;
    };
};

export type ShowChatInvitationUrlControllerRunResponse = ShowChatInvitationUrlControllerRunResponses[keyof ShowChatInvitationUrlControllerRunResponses];

export type ShowChatMessageControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        chatId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/chats/{chatId}/messages/{id}';
};

export type ShowChatMessageControllerRunResponses = {
    200: {
        id: string;
        writtenBy: {
            id: string;
            userName?: string;
        };
        reactTo?: {
            id: string;
        };
        writtenAt: string;
        deleted: boolean;
        contentHistory: Array<{
            value?: {
                [key: string]: unknown;
            };
            contentType: 'AudioOgg' | 'ChatCreated' | 'ChatDescriptionUpdated' | 'ChatDisabled' | 'ChatEnabled' | 'ChatTitleUpdated' | 'DeletedMessage' | 'Empty' | 'ImageJpeg' | 'MessageLocation' | 'MessagePoll' | 'MessagePollAnswer' | 'MessagePollStatus' | 'MessageReaction' | 'Text' | 'TextFormatted' | 'Unknown' | 'UserJoined' | 'UserRemoved';
            attachment?: {
                name: string;
                contentType: 'AudioOgg' | 'ChatCreated' | 'ChatDescriptionUpdated' | 'ChatDisabled' | 'ChatEnabled' | 'ChatTitleUpdated' | 'DeletedMessage' | 'Empty' | 'ImageJpeg' | 'MessageLocation' | 'MessagePoll' | 'MessagePollAnswer' | 'MessagePollStatus' | 'MessageReaction' | 'Text' | 'TextFormatted' | 'Unknown' | 'UserJoined' | 'UserRemoved';
                evidence: {
                    id: string;
                    tspTimestamp?: {
                        provider: string;
                        token: string;
                        date: string;
                    };
                    dltTimestamp?: {
                        provider: string;
                        blockExplorerLink: string;
                        date: string;
                    };
                };
            };
            capturedAt: string;
            evidence: {
                id: string;
                tspTimestamp?: {
                    provider: string;
                    token: string;
                    date: string;
                };
                dltTimestamp?: {
                    provider: string;
                    blockExplorerLink: string;
                    date: string;
                };
            };
        }>;
        reactionsHistory: Array<{
            value: Array<{
                emoji: string;
                participants: Array<{
                    userName: string;
                }>;
            }>;
            capturedAt: string;
        }>;
    };
};

export type ShowChatMessageControllerRunResponse = ShowChatMessageControllerRunResponses[keyof ShowChatMessageControllerRunResponses];

export type CertifyDossierControllerRunData = {
    body?: never;
    path: {
        dossierId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/dossiers/{dossierId}/certify';
};

export type CertifyDossierControllerRunResponses = {
    202: unknown;
};

export type ListDossiersControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
    };
    query?: {
        filter?: {
            caseFileId?: string;
            search?: string;
            createdFrom?: string;
            createdUntil?: string;
            status?: 'CERTIFYING' | 'DRAFT' | 'CERTIFIED';
            statuses?: Array<'CERTIFYING' | 'DRAFT' | 'CERTIFIED'>;
            createdById?: string;
            ownerIds?: Array<string>;
            id?: string;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/dossiers';
};

export type ListDossiersControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            caseFileId: string;
            code: string;
            name: string;
            status: string;
            createdAt: string;
            certifiedAt?: string;
            evidencesCount: number;
            evidenceGroupsCount: number;
            visibility: string;
            owner: {
                id: string;
                firstName: string;
                lastName: string;
            };
            createdBy?: {
                id: string;
                firstName: string;
                lastName: string;
            };
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListDossiersControllerRunResponse = ListDossiersControllerRunResponses[keyof ListDossiersControllerRunResponses];

export type CreateDossierControllerRunData = {
    body: {
        /**
         * @deprecated
         */
        dossierTemplateId?: string;
        /**
         * @deprecated
         */
        purpose?: string;
        id: string;
        modelId?: string;
        name: string;
        language: 'en_GB' | 'es_ES' | 'pt_PT';
        filledFields?: {
            [key: string]: unknown;
        };
        validityFrom: string;
        validityTo: string;
        accessToken?: string;
    };
    path: {
        caseFileId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/dossiers';
};

export type CreateDossierControllerRunResponses = {
    201: unknown;
};

export type CreateDossierExpressControllerRunData = {
    body: {
        id: string;
        modelId?: string;
        evidenceIds?: Array<string>;
        name: string;
        language: 'en_GB' | 'es_ES' | 'pt_PT';
    };
    path: {
        caseFileId: string;
        evidenceGroupId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/dossier-express';
};

export type CreateDossierExpressControllerRunResponses = {
    201: unknown;
};

export type DeleteDossierControllerRunData = {
    body?: never;
    path: {
        dossierId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/dossiers/{dossierId}';
};

export type DeleteDossierControllerRunResponses = {
    204: void;
};

export type DeleteDossierControllerRunResponse = DeleteDossierControllerRunResponses[keyof DeleteDossierControllerRunResponses];

export type ShowDossierControllerRunData = {
    body?: never;
    path: {
        dossierId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/dossiers/{dossierId}';
};

export type ShowDossierControllerRunResponses = {
    200: {
        /**
         * @deprecated
         */
        dossierTemplateId: string;
        /**
         * @deprecated
         */
        purpose?: string;
        /**
         * @deprecated
         */
        dossierTemplateFilename?: string;
        id: string;
        modelId: string;
        code: string;
        name: string;
        language: string;
        filledFields: {
            [key: string]: unknown;
        };
        status: string;
        visibility: string;
        caseFileId: string;
        createdAt: string;
        evidencesCount: number;
        evidenceGroupsCount: number;
        certifiedAt?: string;
        owner: {
            id: string;
            firstName: string;
            lastName: string;
        };
        createdBy?: {
            id: string;
            firstName: string;
            lastName: string;
        };
        accessToken?: string;
    };
};

export type ShowDossierControllerRunResponse = ShowDossierControllerRunResponses[keyof ShowDossierControllerRunResponses];

export type UpdateDossierControllerRunData = {
    body: {
        /**
         * @deprecated
         */
        dossierTemplateId?: string;
        /**
         * @deprecated
         */
        purpose?: string;
        modelId?: string;
        name?: string;
        language?: 'en_GB' | 'es_ES' | 'pt_PT';
        filledFields?: {
            [key: string]: unknown;
        };
        validityFrom?: string;
        validityTo?: string;
        accessToken?: string;
    };
    path: {
        dossierId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/dossiers/{dossierId}';
};

export type UpdateDossierControllerRunResponses = {
    204: void;
};

export type UpdateDossierControllerRunResponse = UpdateDossierControllerRunResponses[keyof UpdateDossierControllerRunResponses];

export type ListDossierRecallRequestsControllerRunData = {
    body?: never;
    path: {
        dossierId: string;
    };
    query?: {
        filter?: {
            id?: string;
            email?: string;
            resolved?: boolean;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/dossiers/{dossierId}/recall-requests';
};

export type ListDossierRecallRequestsControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            dossierId: string;
            firstName: string;
            lastName: string;
            phoneNumber?: string;
            email: string;
            reason: string;
            createdAt: string;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListDossierRecallRequestsControllerRunResponse = ListDossierRecallRequestsControllerRunResponses[keyof ListDossierRecallRequestsControllerRunResponses];

export type ShowDossierDocumentUrlControllerRunData = {
    body?: never;
    path: {
        dossierId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/dossiers/{dossierId}/document-url';
};

export type ShowDossierDocumentUrlControllerRunResponses = {
    200: {
        documentUrl: string;
    };
};

export type ShowDossierDocumentUrlControllerRunResponse = ShowDossierDocumentUrlControllerRunResponses[keyof ShowDossierDocumentUrlControllerRunResponses];

export type ShowDossierPackageUrlControllerRunData = {
    body?: never;
    path: {
        dossierId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/dossiers/{dossierId}/package-url';
};

export type ShowDossierPackageUrlControllerRunResponses = {
    200: {
        packageUrl: string;
    };
};

export type ShowDossierPackageUrlControllerRunResponse = ShowDossierPackageUrlControllerRunResponses[keyof ShowDossierPackageUrlControllerRunResponses];

export type ShowDossierPreviewControllerRunData = {
    body?: never;
    path: {
        dossierId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/dossiers/{dossierId}/report-preview';
};

export type ShowDossierPreviewControllerRunResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type ShowDossierPreviewControllerRunResponse = ShowDossierPreviewControllerRunResponses[keyof ShowDossierPreviewControllerRunResponses];

export type ShowEvidenceWithLinkedToDossiersControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        evidenceGroupId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences-with-linked-to-dossiers/{id}';
};

export type ShowEvidenceWithLinkedToDossiersControllerRunResponses = {
    200: {
        id: string;
        linkedToDossiers: boolean;
    };
};

export type ShowEvidenceWithLinkedToDossiersControllerRunResponse = ShowEvidenceWithLinkedToDossiersControllerRunResponses[keyof ShowEvidenceWithLinkedToDossiersControllerRunResponses];

export type UpdateDossierVisibilityControllerRunData = {
    body: {
        visibility: 'ACCESSIBLE' | 'PENDING_RECALL' | 'RECALLED';
    };
    path: {
        dossierId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/dossiers/{dossierId}/visibility';
};

export type UpdateDossierVisibilityControllerRunResponses = {
    204: void;
};

export type UpdateDossierVisibilityControllerRunResponse = UpdateDossierVisibilityControllerRunResponses[keyof UpdateDossierVisibilityControllerRunResponses];

export type ListDossierTemplatesControllerRunData = {
    body?: never;
    path?: never;
    query?: {
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/dossier-templates';
};

export type ListDossierTemplatesControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            index: number;
            requiresPurpose: boolean;
            translations: Array<{
                id: string;
                name: string;
                language: string;
                tipsDescription: string;
                tipsList: Array<string>;
                purposeDossier: string;
            }>;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListDossierTemplatesControllerRunResponse = ListDossierTemplatesControllerRunResponses[keyof ListDossierTemplatesControllerRunResponses];

export type CloseEvidenceGroupControllerRunData = {
    body: {
        evidencesCount: number;
        deviceModel?: string;
        deviceManufacturer?: string;
        deviceOS?: string;
        latitudeLocation?: string;
        longitudeLocation?: string;
        altitudeLocation?: string;
        locationAccuracy?: string;
        userAgent?: string;
        webUrl?: string;
        attestation?: {
            provider: 'PlayIntegrity' | 'AppAttest';
            app: 'App' | 'AppPro';
            token?: string;
            keyId?: string;
            assertion?: string;
        };
    };
    path: {
        caseFileId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{id}/close';
};

export type CloseEvidenceGroupControllerRunResponses = {
    202: unknown;
};

export type CreateEvidenceControllerRunData = {
    body: {
        id: string;
        hash: string;
        title: string;
        evidenceGroupId: string;
        caseFileId: string;
        custodyType: 'INTERNAL' | 'EXTERNAL';
        fileName?: string;
    };
    path?: never;
    query?: never;
    url: '/evidences';
};

export type CreateEvidenceControllerRunResponses = {
    202: {
        uploadFileUrl?: string;
        expiration?: string;
    };
};

export type CreateEvidenceControllerRunResponse = CreateEvidenceControllerRunResponses[keyof CreateEvidenceControllerRunResponses];

export type CreateEvidenceGroupControllerRunData = {
    body: {
        id: string;
        evidenceType: 'FILE' | 'PHOTO' | 'VIDEO' | 'WEB_PLUGIN';
        name: string;
        description?: string;
        caseFileId: string;
        attestation?: {
            provider: 'PlayIntegrity' | 'AppAttest';
            app: 'App' | 'AppPro';
            token?: string;
            keyId?: string;
            assertion?: string;
        };
    };
    path?: never;
    query?: never;
    url: '/evidence-groups';
};

export type CreateEvidenceGroupControllerRunResponses = {
    201: unknown;
};

export type DeleteEvidenceControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        evidenceGroupId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences/{id}';
};

export type DeleteEvidenceControllerRunResponses = {
    204: void;
};

export type DeleteEvidenceControllerRunResponse = DeleteEvidenceControllerRunResponses[keyof DeleteEvidenceControllerRunResponses];

export type ShowEvidenceControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        evidenceGroupId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences/{id}';
};

export type ShowEvidenceControllerRunResponses = {
    200: {
        /**
         * @deprecated
         */
        tspTimestamp?: {
            provider: string;
            token: string;
            date: string;
        };
        /**
         * @deprecated
         */
        dltTimestamp?: {
            provider: string;
            blockExplorerLink: string;
            date: string;
        };
        id: string;
        title?: string;
        fileSize?: number;
        fileName: string;
        capturedAt: string;
        status: string;
        hash: string;
        relevant: boolean;
        favorite: boolean;
        custodyType: string;
        tspTimestamps: Array<{
            provider: string;
            token: string;
            date: string;
        }>;
        dltTimestamps: Array<{
            provider: string;
            blockExplorerLink: string;
            date: string;
        }>;
    };
};

export type ShowEvidenceControllerRunResponse = ShowEvidenceControllerRunResponses[keyof ShowEvidenceControllerRunResponses];

export type UpdateEvidenceControllerRunData = {
    body: {
        title?: string;
        relevant?: boolean;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences/{id}';
};

export type UpdateEvidenceControllerRunResponses = {
    204: void;
};

export type UpdateEvidenceControllerRunResponse = UpdateEvidenceControllerRunResponses[keyof UpdateEvidenceControllerRunResponses];

export type DiscardEvidenceGroupControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{id}';
};

export type DiscardEvidenceGroupControllerRunResponses = {
    204: void;
};

export type DiscardEvidenceGroupControllerRunResponse = DiscardEvidenceGroupControllerRunResponses[keyof DiscardEvidenceGroupControllerRunResponses];

export type ShowEvidenceGroupControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{id}';
};

export type ShowEvidenceGroupControllerRunResponses = {
    200: {
        id: string;
        caseFileId: string;
        code: string;
        name: string;
        description?: string;
        type: string;
        status: string;
        evidenceStats: {
            inProcess: number;
            failed: number;
            completed: number;
            total: number;
        };
        evidenceMetadataId?: string;
        createdBy?: {
            id: string;
            firstName: string;
            lastName: string;
        };
        createdAt: string;
    };
};

export type ShowEvidenceGroupControllerRunResponse = ShowEvidenceGroupControllerRunResponses[keyof ShowEvidenceGroupControllerRunResponses];

export type UpdateEvidenceGroupControllerRunData = {
    body: {
        name: string;
        description?: string;
    };
    path: {
        caseFileId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{id}';
};

export type UpdateEvidenceGroupControllerRunResponses = {
    204: void;
};

export type UpdateEvidenceGroupControllerRunResponse = UpdateEvidenceGroupControllerRunResponses[keyof UpdateEvidenceGroupControllerRunResponses];

export type DownloadUrlEvidenceControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        evidenceGroupId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences/{id}/download-url';
};

export type DownloadUrlEvidenceControllerRunResponses = {
    200: {
        downloadFileUrl: string;
    };
};

export type DownloadUrlEvidenceControllerRunResponse = DownloadUrlEvidenceControllerRunResponses[keyof DownloadUrlEvidenceControllerRunResponses];

export type ListEvidenceGroupsControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
    };
    query?: {
        filter?: {
            ids?: Array<string>;
            caseFileId?: string;
            createdById?: string;
            name?: string;
            createdFrom?: string;
            createdUntil?: string;
            status?: 'OPEN' | 'CLOSED' | 'CLOSING';
            type?: 'FILE' | 'PHOTO' | 'VIDEO' | 'WEB_PLUGIN';
            id?: string;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/evidence-groups';
};

export type ListEvidenceGroupsControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            caseFileId: string;
            code: string;
            name: string;
            type: string;
            status: string;
            evidenceStats: {
                inProcess: number;
                failed: number;
                completed: number;
                total: number;
            };
            createdBy?: {
                id: string;
                firstName: string;
                lastName: string;
            };
            createdAt: string;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListEvidenceGroupsControllerRunResponse = ListEvidenceGroupsControllerRunResponses[keyof ListEvidenceGroupsControllerRunResponses];

export type ListEvidencesByCaseFileControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
    };
    query?: {
        filter?: {
            ids?: Array<string>;
            caseFileId?: string;
            evidenceGroupIds?: Array<string>;
            evidenceGroupTypes?: Array<'FILE' | 'PHOTO' | 'VIDEO' | 'WEB_PLUGIN'>;
            title?: string;
            status?: 'COMPLETED' | 'IN_PROCESS' | 'ERROR';
            capturedFrom?: string;
            capturedUntil?: string;
            relevant?: boolean;
            favorite?: boolean;
            collectionMetadata?: boolean;
            id?: string;
        };
        order?: {
            capturedAt?: 'ASC' | 'DESC';
            evidenceGroupName?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/evidences';
};

export type ListEvidencesByCaseFileControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            title?: string;
            fileSize?: number;
            fileName: string;
            capturedAt: string;
            status: string;
            hash: string;
            relevant: boolean;
            favorite: boolean;
            custodyType: string;
            evidenceGroup: {
                id: string;
                code: string;
                name: string;
                type: string;
            };
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListEvidencesByCaseFileControllerRunResponse = ListEvidencesByCaseFileControllerRunResponses[keyof ListEvidencesByCaseFileControllerRunResponses];

export type ListEvidencesControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        evidenceGroupId: string;
    };
    query?: {
        filter?: {
            ids?: Array<string>;
            caseFileId?: string;
            evidenceGroupIds?: Array<string>;
            evidenceGroupTypes?: Array<'FILE' | 'PHOTO' | 'VIDEO' | 'WEB_PLUGIN'>;
            title?: string;
            status?: 'COMPLETED' | 'IN_PROCESS' | 'ERROR';
            capturedFrom?: string;
            capturedUntil?: string;
            relevant?: boolean;
            favorite?: boolean;
            collectionMetadata?: boolean;
            id?: string;
        };
        order?: {
            capturedAt?: 'ASC' | 'DESC';
            evidenceGroupName?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences';
};

export type ListEvidencesControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            title?: string;
            fileSize?: number;
            fileName: string;
            capturedAt: string;
            status: string;
            hash: string;
            relevant: boolean;
            favorite: boolean;
            custodyType: string;
            evidenceGroup: {
                id: string;
                code: string;
                name: string;
                type: string;
            };
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListEvidencesControllerRunResponse = ListEvidencesControllerRunResponses[keyof ListEvidencesControllerRunResponses];

export type ListEvidenceTypesControllerRunData = {
    body?: never;
    path?: never;
    query?: {
        filter?: {
            code?: 'FILE' | 'PHOTO' | 'VIDEO' | 'WEB_PLUGIN';
            id?: string;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
            index?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/evidence-types';
};

export type ListEvidenceTypesControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            code: string;
            index: number;
            translations: Array<{
                id: string;
                name: string;
                language: string;
                tipsDescription: string;
                tipsList: Array<string>;
                purposeDossier: string;
            }>;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListEvidenceTypesControllerRunResponse = ListEvidenceTypesControllerRunResponses[keyof ListEvidenceTypesControllerRunResponses];

export type ListTimestampTypesControllerRunData = {
    body?: never;
    path?: never;
    query?: {
        filter?: {
            id?: string;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
            index?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/timestamp-types';
};

export type ListTimestampTypesControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            category: 'TSP' | 'DLT';
            index: number;
            translations: Array<{
                id: string;
                name: string;
                language: string;
                tipsDescription: string;
                tipsList: Array<string>;
                purposeDossier: string;
            }>;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListTimestampTypesControllerRunResponse = ListTimestampTypesControllerRunResponses[keyof ListTimestampTypesControllerRunResponses];

export type ProcessEvidenceGroupsCallbackControllerRunData = {
    body: {
        operation: string;
        result: 'OK' | 'KO';
        data: {
            evidenceGroupId: string;
            caseFileId: string;
        };
    };
    path?: never;
    query?: never;
    url: '/evidence-groups/callback';
};

export type ProcessEvidenceGroupsCallbackControllerRunResponses = {
    204: void;
};

export type ProcessEvidenceGroupsCallbackControllerRunResponse = ProcessEvidenceGroupsCallbackControllerRunResponses[keyof ProcessEvidenceGroupsCallbackControllerRunResponses];

export type ProcessEvidencesCallbackControllerRunData = {
    body: {
        operation: string;
        result: 'OK' | 'KO';
        data: {
            evidenceId: string;
            evidenceGroupId: string;
            caseFileId: string;
        };
    };
    path?: never;
    query?: never;
    url: '/evidences/callback';
};

export type ProcessEvidencesCallbackControllerRunResponses = {
    204: void;
};

export type ProcessEvidencesCallbackControllerRunResponse = ProcessEvidencesCallbackControllerRunResponses[keyof ProcessEvidencesCallbackControllerRunResponses];

export type ThumbnailEvidenceControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        evidenceGroupId: string;
        id: string;
        size: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences/{id}/thumbnail/{size}';
};

export type ThumbnailEvidenceControllerRunResponses = {
    200: {
        url: string;
    };
};

export type ThumbnailEvidenceControllerRunResponse = ThumbnailEvidenceControllerRunResponses[keyof ThumbnailEvidenceControllerRunResponses];

export type UpdateFavoriteEvidenceControllerRunData = {
    body: {
        favorite: boolean;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences/{id}/favorite';
};

export type UpdateFavoriteEvidenceControllerRunResponses = {
    204: void;
};

export type UpdateFavoriteEvidenceControllerRunResponse = UpdateFavoriteEvidenceControllerRunResponses[keyof UpdateFavoriteEvidenceControllerRunResponses];

export type UploadUrlEvidenceControllerRunData = {
    body: {
        hash: string;
        fileName: string;
    };
    path: {
        caseFileId: string;
        evidenceGroupId: string;
        id: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/evidence-groups/{evidenceGroupId}/evidences/{id}/upload-url';
};

export type UploadUrlEvidenceControllerRunResponses = {
    201: {
        uploadFileUrl: string;
        expiration: string;
    };
};

export type UploadUrlEvidenceControllerRunResponse = UploadUrlEvidenceControllerRunResponses[keyof UploadUrlEvidenceControllerRunResponses];

export type ListNotificationCertificatesControllerRunData = {
    body?: never;
    path: {
        notificationRequestId: string;
        receiverId: string;
    };
    query?: {
        filter?: {
            partial: boolean;
            language?: 'en_GB' | 'es_ES';
            id?: string;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers/{receiverId}/certificates';
};

export type ListNotificationCertificatesControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            notificationRequestId: string;
            receiverId: string;
            partial: boolean;
            status: 'CERTIFYING' | 'DRAFT' | 'CERTIFIED';
            createdAt: string;
            certifiedAt?: string;
            language: 'en_GB' | 'es_ES';
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListNotificationCertificatesControllerRunResponse = ListNotificationCertificatesControllerRunResponses[keyof ListNotificationCertificatesControllerRunResponses];

export type CreateNotificationCertificateControllerRunData = {
    body: {
        id: string;
        language?: 'en_GB' | 'es_ES';
    };
    path: {
        caseFileId: string;
        notificationRequestId: string;
        receiverId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers/{receiverId}/certificates';
};

export type CreateNotificationCertificateControllerRunResponses = {
    201: unknown;
};

export type ProcessNotificationCertificatesCallbackControllerRunData = {
    body: {
        eventType: string;
        data: {
            reportId: string;
        };
    };
    path?: never;
    query?: never;
    url: '/notification-certificates/callback';
};

export type ProcessNotificationCertificatesCallbackControllerRunResponses = {
    204: void;
};

export type ProcessNotificationCertificatesCallbackControllerRunResponse = ProcessNotificationCertificatesCallbackControllerRunResponses[keyof ProcessNotificationCertificatesCallbackControllerRunResponses];

export type ShowNotificationCertificateDocumentUrlControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        notificationRequestId: string;
        receiverId: string;
        certificateId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers/{receiverId}/certificates/{certificateId}/document-url';
};

export type ShowNotificationCertificateDocumentUrlControllerRunResponses = {
    200: {
        documentUrl: string;
    };
};

export type ShowNotificationCertificateDocumentUrlControllerRunResponse = ShowNotificationCertificateDocumentUrlControllerRunResponses[keyof ShowNotificationCertificateDocumentUrlControllerRunResponses];

export type ShowNotificationCertificatePackageUrlControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        notificationRequestId: string;
        receiverId: string;
        certificateId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers/{receiverId}/certificates/{certificateId}/package-url';
};

export type ShowNotificationCertificatePackageUrlControllerRunResponses = {
    200: {
        packageUrl: string;
    };
};

export type ShowNotificationCertificatePackageUrlControllerRunResponse = ShowNotificationCertificatePackageUrlControllerRunResponses[keyof ShowNotificationCertificatePackageUrlControllerRunResponses];

export type ActivateNotificationRequestControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        notificationRequestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/activate';
};

export type ActivateNotificationRequestControllerRunResponses = {
    200: unknown;
};

export type CreateMassiveNotificationReceiversControllerRunData = {
    body: {
        receivers: Array<{
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            phoneNumber?: string;
            phonePrefix?: string;
        }>;
    };
    path: {
        notificationRequestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers/massive';
};

export type CreateMassiveNotificationReceiversControllerRunResponses = {
    201: unknown;
};

export type ListNotificationReceiversControllerRunData = {
    body?: never;
    path: {
        notificationRequestId: string;
    };
    query?: {
        filter?: {
            id?: string;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
            email?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers';
};

export type ListNotificationReceiversControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            notificationRequestId: string;
            status: 'INVALID' | 'READY_TO_SEND' | 'SENT' | 'READ' | 'ANSWERED' | 'ERROR';
            validationError?: 'TAKEN' | 'IS_DEFINED' | 'IS_INVALID';
            answer?: string;
            firstName?: string;
            lastName?: string;
            email?: string;
            phonePrefix?: string;
            phoneNumber?: string;
            statusUpdatedAt: string;
            otpRequired: boolean;
            sendWaUrl: boolean;
            emailBounced: boolean;
            createdAt: string;
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListNotificationReceiversControllerRunResponse = ListNotificationReceiversControllerRunResponses[keyof ListNotificationReceiversControllerRunResponses];

export type CreateNotificationReceiverControllerRunData = {
    body: {
        id: string;
        firstName: string;
        lastName: string;
        email: string;
        phoneNumber?: string;
        phonePrefix?: string;
        otpRequired?: boolean;
        sendWaUrl?: boolean;
    };
    path: {
        notificationRequestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers';
};

export type CreateNotificationReceiverControllerRunResponses = {
    201: unknown;
};

export type CreateNotificationRequestControllerRunData = {
    body: {
        id: string;
        type?: 'NO_RESPONSE' | 'ACCEPTED_OR_NOT' | 'RECEIVED_AGREE';
        subject: string;
        content: string;
        language: 'en_GB' | 'es_ES';
        otpByDefault?: boolean;
        sendWaUrlByDefault?: boolean;
    };
    path: {
        caseFileId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests';
};

export type CreateNotificationRequestControllerRunResponses = {
    201: unknown;
};

export type DeleteInvalidNotificationReceiversControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        notificationRequestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/invalid-receivers';
};

export type DeleteInvalidNotificationReceiversControllerRunResponses = {
    200: unknown;
};

export type DeleteNotificationReceiverControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        notificationRequestId: string;
        receiverId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers/{receiverId}';
};

export type DeleteNotificationReceiverControllerRunResponses = {
    200: unknown;
};

export type UpdateNotificationReceiverControllerRunData = {
    body: {
        firstName?: string;
        lastName?: string;
        email?: string;
        phonePrefix?: string;
        phoneNumber?: string;
    };
    path: {
        caseFileId: string;
        notificationRequestId: string;
        receiverId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers/{receiverId}';
};

export type UpdateNotificationReceiverControllerRunResponses = {
    200: unknown;
};

export type DeleteNotificationRequestControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        notificationRequestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}';
};

export type DeleteNotificationRequestControllerRunResponses = {
    200: unknown;
};

export type ShowNotificationRequestControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        notificationRequestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}';
};

export type ShowNotificationRequestControllerRunResponses = {
    200: {
        id: string;
        code: string;
        subject: string;
        content: string;
        language: 'en_GB' | 'es_ES';
        status: 'CREATING' | 'DRAFT' | 'IN_PROCESS' | 'SENT' | 'PARTIALLY_READ' | 'FULLY_READ' | 'PARTIALLY_ANSWERED' | 'FULLY_ANSWERED';
        type: 'NO_RESPONSE' | 'ACCEPTED_OR_NOT' | 'RECEIVED_AGREE';
        statusUpdatedAt: string;
        sentAt?: string;
        createdAt: string;
        otpByDefault: boolean;
        sendWaUrlByDefault: boolean;
        caseFile: {
            id: string;
            useCaseId: string;
            name: string;
            code: string;
            ownerId: string;
        };
        owner: {
            id: string;
            firstName: string;
            lastName: string;
            role: string;
            email: string;
        };
        createdBy?: {
            id: string;
            firstName: string;
            lastName: string;
            role: string;
            email: string;
        };
        receiverStats: {
            total: number;
            bounced: number;
            valid: number;
        };
    };
};

export type ShowNotificationRequestControllerRunResponse = ShowNotificationRequestControllerRunResponses[keyof ShowNotificationRequestControllerRunResponses];

export type UpdateNotificationRequestControllerRunData = {
    body: {
        type?: 'NO_RESPONSE' | 'ACCEPTED_OR_NOT' | 'RECEIVED_AGREE';
        subject?: string;
        content?: string;
        language?: 'en_GB' | 'es_ES';
    };
    path: {
        caseFileId: string;
        notificationRequestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}';
};

export type UpdateNotificationRequestControllerRunResponses = {
    200: unknown;
};

export type DuplicateNotificationRequestControllerRunData = {
    body: {
        caseFileId?: string;
        id: string;
        subject: string;
    };
    path: {
        caseFileId: string;
        notificationRequestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/duplicate';
};

export type DuplicateNotificationRequestControllerRunResponses = {
    201: unknown;
};

export type ListNotificationRequestsControllerRunData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: {
        filter?: {
            status?: 'CREATING' | 'DRAFT' | 'IN_PROCESS' | 'SENT' | 'PARTIALLY_READ' | 'FULLY_READ' | 'PARTIALLY_ANSWERED' | 'FULLY_ANSWERED';
            statuses?: Array<'CREATING' | 'DRAFT' | 'IN_PROCESS' | 'SENT' | 'PARTIALLY_READ' | 'FULLY_READ' | 'PARTIALLY_ANSWERED' | 'FULLY_ANSWERED'>;
            search?: string;
            caseFileIds?: Array<string>;
            receiversSearch?: string;
        };
        order?: {
            createdAt?: 'ASC' | 'DESC';
        };
        page?: {
            number: number;
            size: number;
        };
    };
    url: '/users/{userId}/notification-requests';
};

export type ListNotificationRequestsControllerRunResponses = {
    200: {
        data?: Array<{
            id: string;
            code: string;
            subject: string;
            status: 'CREATING' | 'DRAFT' | 'IN_PROCESS' | 'SENT' | 'PARTIALLY_READ' | 'FULLY_READ' | 'PARTIALLY_ANSWERED' | 'FULLY_ANSWERED';
            type: 'NO_RESPONSE' | 'ACCEPTED_OR_NOT' | 'RECEIVED_AGREE';
            statusUpdatedAt: string;
            createdAt: string;
            sentAt?: string;
            otpByDefault: boolean;
            receiverStats: {
                firstEmail: string;
                total: number;
            };
            sendWaUrlByDefault: boolean;
            caseFile: {
                id: string;
                useCaseId: string;
                name: string;
                code: string;
            };
            owner: {
                id: string;
                firstName: string;
                lastName: string;
            };
            createdBy?: {
                id: string;
                firstName: string;
                lastName: string;
            };
        }>;
        meta?: {
            totalElements?: number;
        };
    };
};

export type ListNotificationRequestsControllerRunResponse = ListNotificationRequestsControllerRunResponses[keyof ListNotificationRequestsControllerRunResponses];

export type ProcessNotificationsCallbackControllerRunData = {
    body: {
        eventType: string;
        data: {
            notificationId?: string;
            notificationAttachmentId?: string;
        };
    };
    path?: never;
    query?: never;
    url: '/notifications/callback';
};

export type ProcessNotificationsCallbackControllerRunResponses = {
    204: void;
};

export type ProcessNotificationsCallbackControllerRunResponse = ProcessNotificationsCallbackControllerRunResponses[keyof ProcessNotificationsCallbackControllerRunResponses];

export type SendNotificationRequestControllerRunData = {
    body?: never;
    path: {
        caseFileId: string;
        notificationRequestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/send';
};

export type SendNotificationRequestControllerRunResponses = {
    200: unknown;
};

export type UpdateNotificationRequestCaseFileIdControllerRunData = {
    body: {
        caseFileId: string;
    };
    path: {
        caseFileId: string;
        notificationRequestId: string;
    };
    query?: never;
    url: '/case-files/{caseFileId}/notification-requests/{notificationRequestId}/case-file-id';
};

export type UpdateNotificationRequestCaseFileIdControllerRunResponses = {
    200: unknown;
};
