// Auto-generated by the g-digital MCP distribution pipeline.
// Source MCP: @g-digital/mcp-gocertius (1.3.4)
// Architecture: REST-direct (Epic 12 ADR 0008) — Bearer token fetched by the node.

import {
  ICredentialTestRequest,
  ICredentialType,
  INodeProperties,
} from 'n8n-workflow';

export class GocertiusApi implements ICredentialType {
  name = 'gocertiusApi';
  displayName = 'GoCertius API';
  documentationUrl = 'https://www.gocertius.io';

  properties: INodeProperties[] = [
    {
      displayName: 'API Base URL',
      name: 'baseUrl',
      type: 'string',
      default: 'https://api-gocertius.gocertius.io',
      description: 'Base URL of the GoCertius REST API. Leave as-is for the production environment (default: https://api-gocertius.gocertius.io).',
    },
    {
      displayName: 'Auth Email',
      name: 'email',
      type: 'string',
      default: '',
      description: "Your GoCertius account email (Flow 1). Configure one of Flow 1 or Flow 2.",
    },
    {
      displayName: 'Auth Password',
      name: 'password',
      type: 'string',
      typeOptions: { password: true },
      default: '',
      description: "Your GoCertius account password (Flow 1, email/password accounts) (See https://www.gocertius.io for credential acquisition.)",
    },
  ];

  test: ICredentialTestRequest = {
    request: {
      baseURL: '={{$credentials.baseUrl}}',
      url: '/session',
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: {
        email: '={{$credentials.email}}',
        password: '={{$credentials.password}}',
      },
    },
  };
}
