// Auto-generated by the g-digital MCP distribution pipeline.
// Source MCP: @g-digital/mcp-gocertius (1.2.19)
// Architecture: REST-direct (Epic 12 ADR 0008) — Bearer token fetched by the node.

import {
  ICredentialTestRequest,
  ICredentialType,
  INodeProperties,
} from 'n8n-workflow';

export class GocertiusApi implements ICredentialType {
  name = 'gocertiusApi';
  displayName = 'Gocertius API';
  documentationUrl = 'https://www.gocertius.io';

  properties: INodeProperties[] = [
    {
      displayName: 'API Base URL',
      name: 'baseUrl',
      type: 'string',
      default: 'https://api-gocertius.gocertius.io',
      description: 'Base URL of the Gocertius REST API. Leave as-is for the production environment (default: https://api-gocertius.gocertius.io).',
    },
    {
      displayName: 'Auth Email',
      name: 'MCP_AUTH_EMAIL',
      type: 'string',
      default: '',
      description: "Enter the email address associated with your GoCertius account.",
    },
    {
      displayName: 'Auth Password',
      name: 'MCP_AUTH_PASSWORD',
      type: 'string',
      typeOptions: { password: true },
      default: '',
      description: "Enter the password for your GoCertius account, found at gocertius.io.",
    },
    {
      displayName: 'OpenID Client ID',
      name: 'MCP_OPENID_CLIENT_ID',
      type: 'string',
      default: '',
      description: "Enter the OpenID Connect client ID provided by your identity provider.",
    },
    {
      displayName: 'OpenID Issuer URL',
      name: 'MCP_OPENID_ISSUER',
      type: 'string',
      default: '',
      description: "Enter the OpenID Connect issuer URL provided by your identity provider.",
    },
    {
      displayName: 'OpenID Refresh Token',
      name: 'MCP_OPENID_REFRESH_TOKEN',
      type: 'string',
      typeOptions: { password: true },
      default: '',
      description: "Enter the OpenID Connect refresh token issued by your identity provider.",
    },
    {
      displayName: 'HTTP Port',
      name: 'PORT',
      type: 'string',
      default: '',
      description: "Enter the port number to use when running the MCP server in HTTP mode.",
    },
  ];

  test: ICredentialTestRequest = {
    request: {
      baseURL: '={{$credentials.baseUrl}}',
      url: '/session',
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: {
        email: '={{$credentials.MCP_AUTH_EMAIL}}',
        password: '={{$credentials.MCP_AUTH_PASSWORD}}',
      },
    },
  };
}
