// Auto-generated by @suite/generator. Do not edit. (Story 4.2, FR14)
// CI smoke test: spawns the built server over stdio, performs the MCP
// initialize -> notifications/initialized -> tools/list dance, and asserts the
// advertised tool count matches .distribution.yaml's static inventory.
// Dependency-free, credential-free — it never calls the upstream API.
// Event-driven (code review 2026-07-07, P4): each step fires on the previous
// response, under a single 30s deadline — no blind sleeps.
import { spawn } from "node:child_process";
import { readFileSync } from "node:fs";

// Count only entries inside the tools: block — other lists in the file must
// never inflate the expectation (the shape is coupled to the generator's
// distribution.yaml template; adjust together).
const distributionYaml = readFileSync(".distribution.yaml", "utf-8");
const toolsSection = distributionYaml.split(/^tools:/m)[1] ?? "";
const expectedTools = (toolsSection.match(/^ {2}- name: /gm) ?? []).length;
if (expectedTools === 0) {
  console.error("ci-smoke: could not parse any tools from .distribution.yaml's tools: block");
  process.exit(1);
}

const proc = spawn("node", ["dist/server.js"], {
  env: {
    ...process.env,
    MCP_TRANSPORT: "stdio",
    MCP_API_BASE_URL: "https://api.example.com",
    NODE_NO_WARNINGS: "1",
  },
  stdio: ["pipe", "pipe", "pipe"],
});

let stdout = "";
let stderr = "";
let finished = false;
proc.stderr.on("data", (chunk) => {
  stderr += chunk.toString();
});

function finish(code, reason) {
  if (finished) return;
  finished = true;
  if (code !== 0) {
    console.error(`ci-smoke FAILED: ${reason}`);
    if (stderr) console.error(`server stderr (first 800 chars):\n${stderr.slice(0, 800)}`);
  } else {
    console.log(reason);
  }
  clearTimeout(deadline);
  proc.kill();
  // Give SIGTERM a moment, then exit regardless (CI reaps leftovers).
  setTimeout(() => process.exit(code), 200).unref();
  process.exitCode = code;
}

const deadline = setTimeout(() => finish(1, "timeout after 30s"), 30_000);

// A server that dies early must fail WITH its stderr, not as an EPIPE crash.
proc.on("error", (err) => finish(1, `could not spawn server: ${err.message}`));
proc.on("exit", (code) => {
  if (!finished) finish(1, `server exited early (code ${code}) before answering`);
});
proc.stdin.on("error", () => {
  /* EPIPE after early exit — the exit handler reports it */
});

function send(msg) {
  proc.stdin.write(`${JSON.stringify(msg)}\n`);
}

proc.stdout.on("data", (chunk) => {
  stdout += chunk.toString();
  const lines = stdout.split("\n");
  stdout = lines.pop() ?? "";
  for (const line of lines) {
    if (!line.trim()) continue;
    let msg;
    try {
      msg = JSON.parse(line);
    } catch {
      continue; // non-JSON output — ignore
    }
    if (msg.id === 1) {
      if (!msg.result) {
        finish(1, `initialize answered with an error: ${JSON.stringify(msg.error ?? msg)}`);
        return;
      }
      // MCP lifecycle: acknowledge initialization before further requests.
      send({ jsonrpc: "2.0", method: "notifications/initialized" });
      send({ jsonrpc: "2.0", id: 2, method: "tools/list", params: {} });
    } else if (msg.id === 2) {
      if (!msg.result) {
        finish(1, `tools/list answered with an error: ${JSON.stringify(msg.error ?? msg)}`);
        return;
      }
      const count = (msg.result.tools ?? []).length;
      if (count !== expectedTools) {
        finish(1, `tools/list returned ${count} tool(s), .distribution.yaml declares ${expectedTools}`);
      } else {
        finish(0, `ci-smoke OK: initialize answered, ${count}/${expectedTools} tools advertised`);
      }
    }
  }
});

send({
  jsonrpc: "2.0",
  id: 1,
  method: "initialize",
  params: {
    protocolVersion: "2024-11-05",
    capabilities: {},
    clientInfo: { name: "ci-smoke", version: "1.0" },
  },
});
