// Auto-generated by @suite/generator. Do not edit.
// MCP server entry point for GoCertius

import { createServer } from "./core/server.js";
import { evidence_create } from "./tools/evidence_create.js";
import { evidence_list } from "./tools/evidence_list.js";
import { evidence_seal } from "./tools/evidence_seal.js";
import { evidence_get } from "./tools/evidence_get.js";
import { evidence_group_create } from "./tools/evidence_group_create.js";
import { evidence_group_list } from "./tools/evidence_group_list.js";
import { dossier_create } from "./tools/dossier_create.js";
import { dossier_list } from "./tools/dossier_list.js";
import { dossier_get } from "./tools/dossier_get.js";
import { dossier_template_list } from "./tools/dossier_template_list.js";
import { notification_request_create } from "./tools/notification_request_create.js";
import { notification_request_status } from "./tools/notification_request_status.js";
import { notification_receiver_add } from "./tools/notification_receiver_add.js";
import { notification_certificate_get } from "./tools/notification_certificate_get.js";
import { case_file_list } from "./tools/case_file_list.js";
import { case_file_get } from "./tools/case_file_get.js";
import { chat_create } from "./tools/chat_create.js";
import { chat_certificate_get } from "./tools/chat_certificate_get.js";
import { session_login } from "./tools/session_login.js";
import { session_info } from "./tools/session_info.js";

await createServer({
  name: "io.github.g-digital-by-Garrigues/gocertius",
  version: "0.0.1",
  tools: [
    evidence_create,
evidence_list,
evidence_seal,
evidence_get,
evidence_group_create,
evidence_group_list,
dossier_create,
dossier_list,
dossier_get,
dossier_template_list,
notification_request_create,
notification_request_status,
notification_receiver_add,
notification_certificate_get,
case_file_list,
case_file_get,
chat_create,
chat_certificate_get,
session_login,
session_info,
  ],
});
