// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: ListCaseFilesController_run (GET /users/{userId}/case-files)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { listCaseFilesControllerRun } from "../api/sdk.gen.js";
import { zListCaseFilesControllerRunPath } from "../api/zod.gen.js";
import { zListCaseFilesControllerRunQuery } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zListCaseFilesControllerRunPath.shape,
  ...zListCaseFilesControllerRunQuery.shape,
});

export const case_file_list = defineTool({
  name: "case_file_list",
  description: "Lists all case files in your GoCertius account. Pass userId (from session_login or session_info) to scope results to your account. Returns paginated list with IDs, names, and status.",
  inputSchema,
  annotations: {
    title: "Case File List",
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "https://api-gocertius.gocertius.io",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = listCaseFilesControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zListCaseFilesControllerRunPath.parse(inp),
      query: zListCaseFilesControllerRunQuery.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
