// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: ShowChatInvitationUrlController_run (GET /case-files/{caseFileId}/chats/{chatId}/invitation-url)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { showChatInvitationUrlControllerRun } from "../api/sdk.gen.js";
import { zShowChatInvitationUrlControllerRunPath } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zShowChatInvitationUrlControllerRunPath.shape,
});

export const chat_invitation_url = defineTool({
  name: "chat_invitation_url",
  description: "Returns the Telegram invitation URL for a certified chat. Requires: chat_create → chatId and the personal caseFileId. Do not call while chat_get still shows status `creating`; wait until the chat is registered/active, otherwise the API can answer Chat not found. Share the returned invitationUrl with participants so they can join the certified channel.",
  inputSchema,
  annotations: {
    title: "Chat Invitation Url",
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "https://api-gocertius.gocertius.io",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = showChatInvitationUrlControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zShowChatInvitationUrlControllerRunPath.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
