// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: CreateChatCertificateExpressController_run (POST /case-files/{caseFileId}/chats/{chatId}/certificate-express)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { createChatCertificateExpressControllerRun } from "../api/sdk.gen.js";
import { zCreateChatCertificateExpressControllerRunPath } from "../api/zod.gen.js";
import { zCreateChatCertificateExpressControllerRunBody } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zCreateChatCertificateExpressControllerRunPath.shape,
  ...zCreateChatCertificateExpressControllerRunBody.shape,
});

export const chat_certificate_create = defineTool({
  name: "chat_certificate_create",
  description: "Creates a certificate of a range of messages from a certified chat. Requires: chat_create → chatId, case_file_create → caseFileId, messages already present in the Telegram channel. Generate a UUID v4 for `id`. Specify chatMessagesFrom and chatMessagesTo as ISO timestamps (chatMessagesFrom must be AFTER the chat registeredAt timestamp). ASYNC: poll chat_certificate_get until status === CERTIFIED.",
  inputSchema,
  annotations: {
    destructive: false,
    idempotent: false,
    requiresUserConfirmation: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "https://api-gocertius.gocertius.io",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = createChatCertificateExpressControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zCreateChatCertificateExpressControllerRunPath.parse(inp),
      body: zCreateChatCertificateExpressControllerRunBody.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
