// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: ShowChatCertificateController_run (GET /case-files/{caseFileId}/chats/{chatId}/certificates/{id})

import { defineTool } from "../core/index.js";
import { z } from "zod";

const inputSchema = z.object({
  // TODO: replace with generated schema import from ../api/schemas.js
  // This stub is replaced by the agent-assistance layer (E5/E6) with field-level descriptions.
});

export const chat_certificate_get = defineTool({
  name: "chat_certificate_get",
  description: "Performs the chat_certificate_get operation against the GoCertius API. Review the API documentation for full field details.",
  inputSchema,
  annotations: {
    destructive: false,
    idempotent: true,
    requiresUserConfirmation: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(_input, _ctx) {
    // TODO: wire Hey-API generated SDK call here (E5/E6)
    throw new Error("Not implemented — wire in E5/E6 emit phase.");
  },
});
