// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: ListDossierEvidencesToLinkController_run (GET /case-files/{caseFileId}/dossiers/{dossierId}/case-files-to-link/{caseFileToLinkId}/evidences-to-link)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { listDossierEvidencesToLinkControllerRun } from "../api/sdk.gen.js";
import { zListDossierEvidencesToLinkControllerRunPath } from "../api/zod.gen.js";
import { zListDossierEvidencesToLinkControllerRunQuery } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zListDossierEvidencesToLinkControllerRunPath.shape,
  ...zListDossierEvidencesToLinkControllerRunQuery.shape,
});

export const dossier_evidence_list_to_link = defineTool({
  name: "dossier_evidence_list_to_link",
  description: "Performs the dossier_evidence_list_to_link operation against the GoCertius API. Review the API documentation for full field details.",
  inputSchema,
  annotations: {
    destructive: false,
    idempotent: true,
    requiresUserConfirmation: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = listDossierEvidencesToLinkControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zListDossierEvidencesToLinkControllerRunPath.parse(inp),
      query: zListDossierEvidencesToLinkControllerRunQuery.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
