// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: UpdateDossierVisibilityController_run (PUT /case-files/{caseFileId}/dossiers/{dossierId}/visibility)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { updateDossierVisibilityControllerRun } from "../api/sdk.gen.js";
import { zUpdateDossierVisibilityControllerRunPath } from "../api/zod.gen.js";
import { zUpdateDossierVisibilityControllerRunBody } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zUpdateDossierVisibilityControllerRunPath.shape,
  ...zUpdateDossierVisibilityControllerRunBody.shape,
});

export const dossier_visibility = defineTool({
  name: "dossier_visibility",
  description: "Updates the visibility (public/private) of a certified dossier. Requires: dossier_certify (CERTIFIED status), caseFileId, dossierId.",
  inputSchema,
  annotations: {
    destructive: false,
    idempotent: false,
    requiresUserConfirmation: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = updateDossierVisibilityControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zUpdateDossierVisibilityControllerRunPath.parse(inp),
      body: zUpdateDossierVisibilityControllerRunBody.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
