// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: ListDossierTemplatesController_run (GET /dossier-templates)

import { defineTool } from "../core/index.js";
import { z } from "zod";

const inputSchema = z.object({
  // TODO: replace with generated schema import from ../api/schemas.js
  // This stub is replaced by the agent-assistance layer (E5/E6) with field-level descriptions.
});

export const dossier_template_list = defineTool({
  name: "dossier_template_list",
  description: "Performs the dossier_template_list operation against the GoCertius API. Review the API documentation for full field details.",
  inputSchema,
  annotations: {
    destructive: false,
    idempotent: true,
    requiresUserConfirmation: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(_input, _ctx) {
    // TODO: wire Hey-API generated SDK call here (E5/E6)
    throw new Error("Not implemented — wire in E5/E6 emit phase.");
  },
});
