// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: ShowDossierPackageUrlController_run (GET /case-files/{caseFileId}/dossiers/{dossierId}/package-url)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { showDossierPackageUrlControllerRun } from "../api/sdk.gen.js";
import { zShowDossierPackageUrlControllerRunPath } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zShowDossierPackageUrlControllerRunPath.shape,
});

export const dossier_package_url = defineTool({
  name: "dossier_package_url",
  description: "Returns the download URL for the full dossier package (PDF + evidence files). Requires: dossier_certify (CERTIFIED status), caseFileId, dossierId.",
  inputSchema,
  annotations: {
    destructive: false,
    idempotent: true,
    requiresUserConfirmation: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = showDossierPackageUrlControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zShowDossierPackageUrlControllerRunPath.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
