// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: UpdateDossierController_run (PUT /case-files/{caseFileId}/dossiers/{dossierId})

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { updateDossierControllerRun } from "../api/sdk.gen.js";
import { zUpdateDossierControllerRunPath } from "../api/zod.gen.js";
import { zUpdateDossierControllerRunBody } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zUpdateDossierControllerRunPath.shape,
  ...zUpdateDossierControllerRunBody.shape,
});

export const dossier_update = defineTool({
  name: "dossier_update",
  description: "Updates the metadata of an existing dossier (name, template fields, expiry). Requires: dossier_create → dossierId, caseFileId. Only available while dossier is in DRAFT status.",
  inputSchema,
  annotations: {
    title: "Dossier Update",
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "https://api-gocertius.gocertius.io",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = updateDossierControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zUpdateDossierControllerRunPath.parse(inp),
      body: zUpdateDossierControllerRunBody.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
