// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: CreateEvidenceGroupController_run (POST /evidence-groups)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { createEvidenceGroupControllerRun } from "../api/sdk.gen.js";
import { zCreateEvidenceGroupControllerRunBody } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zCreateEvidenceGroupControllerRunBody.shape,
});

export const evidence_group_create = defineTool({
  name: "evidence_group_create",
  description: "Performs the evidence_group_create operation against the GoCertius API. Review the API documentation for full field details.",
  inputSchema,
  annotations: {
    destructive: false,
    idempotent: false,
    requiresUserConfirmation: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "",
        headers: { Authorization: `Bearer ${token}` },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = createEvidenceGroupControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      body: zCreateEvidenceGroupControllerRunBody.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
