// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: ListEvidenceGroupsController_run (GET /case-files/{caseFileId}/evidence-groups)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { listEvidenceGroupsControllerRun } from "../api/sdk.gen.js";
import { zListEvidenceGroupsControllerRunPath } from "../api/zod.gen.js";
import { zListEvidenceGroupsControllerRunQuery } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zListEvidenceGroupsControllerRunPath.shape,
  ...zListEvidenceGroupsControllerRunQuery.shape,
});

export const evidence_group_list = defineTool({
  name: "evidence_group_list",
  description: "Lists all evidence groups in a case file with their current status (OPEN, CLOSING, CLOSED). Use to find an existing group or check which groups are ready for sealing. Requires: caseFileId.",
  inputSchema,
  annotations: {
    destructive: false,
    idempotent: true,
    requiresUserConfirmation: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = listEvidenceGroupsControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zListEvidenceGroupsControllerRunPath.parse(inp),
      query: zListEvidenceGroupsControllerRunQuery.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
