// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: UpdateNotificationRequestCaseFileIdController_run (PUT /case-files/{caseFileId}/notification-requests/{notificationRequestId}/case-file-id)

import { defineTool, UpstreamHttpError } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { updateNotificationRequestCaseFileIdControllerRun } from "../api/sdk.gen.js";
import { zUpdateNotificationRequestCaseFileIdControllerRunPath } from "../api/zod.gen.js";
import { zUpdateNotificationRequestCaseFileIdControllerRunBody } from "../api/zod.gen.js";
const rawInputSchema = z.object({
  ...zUpdateNotificationRequestCaseFileIdControllerRunPath.shape,
  ...zUpdateNotificationRequestCaseFileIdControllerRunBody.shape,
});
// Story 6.5 (FR-27/P-A5): fills in descriptions for commonly reused field names
// (e.g. caseFileId) that Hey API's generated schema doesn't carry on its own.
const inputSchema = rawInputSchema;

export const notification_request_case_file_move = defineTool({
  name: "notification_request_case_file_move",
  description: "Moves a notification to a different case file. Note the two caseFileId values: the one in the path is where the notification is NOW, and the one in the body is the destination. Notifications are grouped by case file, and this is the only way to change that grouping without duplicating.",
  inputSchema,
  annotations: {
    title: "Notification Request Case File Move",
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "https://api-gocertius.gocertius.io",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = updateNotificationRequestCaseFileIdControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zUpdateNotificationRequestCaseFileIdControllerRunPath.parse(inp),
      body: zUpdateNotificationRequestCaseFileIdControllerRunBody.parse(inp),
    });

    if (response.error !== undefined) {
      // Story 10.2: constructs a status-aware UpstreamHttpError instead of a plain
      // Error — mapUpstreamError's 422 field-hint / 5xx transient-retry branches can
      // only be reached this way; a plain Error always fell through to the generic
      // "transient failure" text, discarding the real HTTP status/detail. Uses
      // fromParsedError (not fromResponse) because @hey-api/client-fetch has already
      // consumed response.response's body to populate response.error by this point.
      throw UpstreamHttpError.fromParsedError(response.response?.status ?? 0, response.error, "notification_request_case_file_move");
    }
    return response.data;
  },
});
