// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: CreateNotificationRequestController_run (POST /case-files/{caseFileId}/notification-requests)

import { defineTool } from "../core/index.js";
import { z } from "zod";

const inputSchema = z.object({
  // TODO: replace with generated schema import from ../api/schemas.js
  // This stub is replaced by the agent-assistance layer (E5/E6) with field-level descriptions.
});

export const notification_request_create = defineTool({
  name: "notification_request_create",
  description: "Performs the notification_request_create operation against the GoCertius API. Review the API documentation for full field details.",
  inputSchema,
  annotations: {
    destructive: false,
    idempotent: false,
    requiresUserConfirmation: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(_input, _ctx) {
    // TODO: wire Hey-API generated SDK call here (E5/E6)
    throw new Error("Not implemented — wire in E5/E6 emit phase.");
  },
});
