// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: UpdateNotificationRequestController_run (PUT /case-files/{caseFileId}/notification-requests/{notificationRequestId})

import { defineTool, UpstreamHttpError } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { updateNotificationRequestControllerRun } from "../api/sdk.gen.js";
import { zUpdateNotificationRequestControllerRunPath } from "../api/zod.gen.js";
import { zUpdateNotificationRequestControllerRunBody } from "../api/zod.gen.js";
const rawInputSchema = z.object({
  ...zUpdateNotificationRequestControllerRunPath.shape,
  ...zUpdateNotificationRequestControllerRunBody.shape,
});
// Story 6.5 (FR-27/P-A5): fills in descriptions for commonly reused field names
// (e.g. caseFileId) that Hey API's generated schema doesn't carry on its own.
const inputSchema = rawInputSchema;

export const notification_request_update = defineTool({
  name: "notification_request_update",
  description: "Edits a notification that has not been sent: subject, content, type and language. Requires notificationRequestId and caseFileId. `content` must be valid HTML — plain text is accepted by the API but does NOT render on the recipient landing page. Supported tags only: <p>, <strong>, <em>, <ul><li>, <ol><li>; no other tags and no CSS. Keep `subject` to plain ASCII (no em dashes, no smart quotes), 100 characters maximum. TESTED: once the notification has been sent the API rejects this with 403 Forbidden, so editing only works before the send. To change which case file it belongs to use notification_request_case_file_move — this tool does not move it.",
  inputSchema,
  annotations: {
    title: "Notification Request Update",
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: false,
    openWorldHint: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "https://api-gocertius.gocertius.io",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = updateNotificationRequestControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zUpdateNotificationRequestControllerRunPath.parse(inp),
      body: zUpdateNotificationRequestControllerRunBody.parse(inp),
    });

    if (response.error !== undefined) {
      // Story 10.2: constructs a status-aware UpstreamHttpError instead of a plain
      // Error — mapUpstreamError's 422 field-hint / 5xx transient-retry branches can
      // only be reached this way; a plain Error always fell through to the generic
      // "transient failure" text, discarding the real HTTP status/detail. Uses
      // fromParsedError (not fromResponse) because @hey-api/client-fetch has already
      // consumed response.response's body to populate response.error by this point.
      throw UpstreamHttpError.fromParsedError(response.response?.status ?? 0, response.error, "notification_request_update");
    }
    return response.data;
  },
});
