// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: CreateNotificationRequestController_run (POST /case-files/{caseFileId}/notification-requests)

import { defineTool } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { createNotificationRequestControllerRun } from "../api/sdk.gen.js";
import { zCreateNotificationRequestControllerRunPath } from "../api/zod.gen.js";
import { zCreateNotificationRequestControllerRunBody } from "../api/zod.gen.js";
const inputSchema = z.object({
  ...zCreateNotificationRequestControllerRunPath.shape,
  ...zCreateNotificationRequestControllerRunBody.shape,
});

export const notification_request_create = defineTool({
  name: "notification_request_create",
  description: "Creates a certified notification request. Requires: case_file_create → caseFileId. Generate a UUID v4 for `id`. Set language to en_GB or es_ES. Returns notificationRequestId. Add at least one receiver with notification_receiver_add before sending.",
  inputSchema,
  annotations: {
    destructive: false,
    idempotent: false,
    requiresUserConfirmation: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = createNotificationRequestControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zCreateNotificationRequestControllerRunPath.parse(inp),
      body: zCreateNotificationRequestControllerRunBody.parse(inp),
    });

    if (response.error !== undefined) {
      const msg = typeof response.error === "object" && response.error !== null && "message" in response.error
        ? String(response.error.message)
        : JSON.stringify(response.error);
      throw new Error(msg);
    }
    return response.data;
  },
});
