// Auto-generated by @suite/generator. Do not edit.
// Sourced from operation: ListNotificationReceiversController_run (GET /case-files/{caseFileId}/notification-requests/{notificationRequestId}/receivers)

import { defineTool, UpstreamHttpError } from "../core/index.js";
import { z } from "zod";
import { createClient, createConfig } from "../api/client/index.js";
import { listNotificationReceiversControllerRun } from "../api/sdk.gen.js";
import { zListNotificationReceiversControllerRunPath } from "../api/zod.gen.js";
import { zListNotificationReceiversControllerRunQuery } from "../api/zod.gen.js";
const rawInputSchema = z.object({
  ...zListNotificationReceiversControllerRunPath.shape,
  ...zListNotificationReceiversControllerRunQuery.shape,
});
// Story 6.5 (FR-27/P-A5): fills in descriptions for commonly reused field names
// (e.g. caseFileId) that Hey API's generated schema doesn't carry on its own.
const inputSchema = rawInputSchema;

export const notification_receiver_list = defineTool({
  name: "notification_receiver_list",
  description: "Lists a notification's recipients with their individual delivery state. Returns per recipient: id, firstName, lastName, email, phonePrefix/phoneNumber, status (INVALID, READY_TO_SEND, SENT, READ, ANSWERED, ERROR), statusUpdatedAt, `answer` once they respond, emailBounced, and validationError (TAKEN, IS_DEFINED, IS_INVALID) for a rejected address. Worth calling before notification_request_send to see whether any address came back INVALID, and after sending to see who read or answered. Also the way to recover a receiverId for notification_certificate_get. Paginated; filterable by id.",
  inputSchema,
  annotations: {
    title: "Notification Receiver List",
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: false,
  },
  pollable: false,
  idempotencyWindowSeconds: 60,
  async execute(input, ctx) {
    const token = ctx.auth?.token ?? "";
    const sdkClient = createClient(
      createConfig({
        baseUrl: process.env.MCP_API_BASE_URL ?? "https://api-gocertius.gocertius.io",
        headers: {
          Authorization: `Bearer ${token}`,
          ...(ctx.correlationId ? { "X-Correlation-Id": ctx.correlationId } : {}),
        },
      }),
    );

    // biome-ignore lint/suspicious/noExplicitAny: generated SDK call — input shape validated above
    const inp = input as any;
    // biome-ignore lint/suspicious/noExplicitAny: generated SDK function — types validated at generation time
    const sdkFn = listNotificationReceiversControllerRun as (opts: any) => Promise<any>;
    const response = await sdkFn({
      client: sdkClient,
      path: zListNotificationReceiversControllerRunPath.parse(inp),
      query: zListNotificationReceiversControllerRunQuery.parse(inp),
    });

    if (response.error !== undefined) {
      // Story 10.2: constructs a status-aware UpstreamHttpError instead of a plain
      // Error — mapUpstreamError's 422 field-hint / 5xx transient-retry branches can
      // only be reached this way; a plain Error always fell through to the generic
      // "transient failure" text, discarding the real HTTP status/detail. Uses
      // fromParsedError (not fromResponse) because @hey-api/client-fetch has already
      // consumed response.response's body to populate response.error by this point.
      throw UpstreamHttpError.fromParsedError(response.response?.status ?? 0, response.error, "notification_receiver_list");
    }
    return response.data;
  },
});
